### ISSUE TITLE
OpenWrt 中无法执行, -ash: ./nginx-ui: not found

### ISSUE THREAD

**Issue by jamebal** [0xJacky/nginx-ui#10]
系统
主机名	OpenWrt
型号	AMD Ryzen 7 5700U with Radeon Graphics : 4 Core 16 Thread (CpuMark : 129514.455702 Scores)
CPU 信息	1810.579 MHz
固件版本	OpenWrt R20.12.12 / Mask Ver.D201231 / LuCI Master (git-20.343.54716-6fc079f)
内核版本	5.4.85
```shell
root@OpenWrt:~/nginx-ui# ls
README-zh_CN.md              app.ini                      nginx-ui-linux-amd64.tar.gz
README.md                    nginx-ui
root@OpenWrt:~/nginx-ui# ./nginx-ui
-ash: ./nginx-ui: not found
root@OpenWrt:~/nginx-ui#
```

**Comment by 0xJacky** [comment]
在终端中运行 Nginx UI

nginx-ui -config app.ini
Jacky

**Comment by jamebal** [comment]
也是这样
```shell
root@OpenWrt:~/nginx-ui# nginx-ui -config app.ini
-ash: nginx-ui: not found
```

**Comment by Hintay** [comment]
Should be fixed in [v1.2.0 RC1](https://github.com/0xJacky/nginx-ui/releases/tag/v1.2.0-rc.1), please try again with the latest pre-compiled file.
