### ISSUE TITLE
Fresh install with Linux Script does not recognize LE ssl config

### ISSUE THREAD

**Issue by cpjet64** [0xJacky/nginx-ui#100]
**Describe the bug**
I installed nginx-ui to a cloned dedicated reverse proxy VM to test this out.
The VM is already using certbot and certbot-nginx to autorenew ssl certs for all sites.

When I open a site in nginx-ui that already exists with ssl configured through certbot everything looks ok in the advanced view but in the basic view the option Encrypt Website with Lets Encrypt is disabled as shown in the following screen shot 
![image](https://user-images.githubusercontent.com/38527447/232157268-46f37fa1-e1ec-45cb-964b-d6836af97fa7.png)
![image](https://user-images.githubusercontent.com/38527447/232157560-f1fdf1c2-a0ee-46c3-b548-36d89f0e6aa4.png)

**Expected behavior**
Certbot preconfiguration enables the button

**Info (please complete the following information):**
 - Server OS: Ubuntu 22.04
 - Server Arch: amd64
 - Nginx UI Version: 1.7.9
 - Your Browser: Brave

**Comment by 0xJacky** [comment]
To be honst, this is not a bug. The switch is used to enable or disable the auto-renew certification function of Nginx UI, and we did not detact the third-party configuration of auto-renew.

However, we may add a new feature that allow users to use the custom command to obtain certifications from other providers like certbot. #16

**Comment by cpjet64** [comment]
it would be awesome to add a feature that can detect if the ssl certificate lines followed by the # managed by certbot could be detected and toggle on that option. it would be even better if the already made certificates showed up in the cert page.

**Comment by 0xJacky** [comment]
You can add the exist cert in cert manager, and the click 'Change certificate' buton to replace cert.

**Comment by cpjet64** [comment]
So proper usage of the cert portion would be to add the cert manually using the ssl pathing in the conf file and then toggle on the manage button? Would be nice to get some documentation on that portion. thank you!

**Comment by 0xJacky** [comment]
No, the original design is not support users to use other auto-cert services. In v1.7.x, the proper usage is toggle the switch on, and then in the pop modal, you will see the nginx-ui obtaining the cert automatically. After obtained the cert, it will be store to the cert manger, and you just need to click the save button in the footer bar, and then the site is encrypted.

**Comment by 0xJacky** [comment]
I decided not to implement the automatic detection of "# managed by certbot" for toggling on the switch. The reason is that the switch's value would be stored in the database, and a background scheduled task is responsible for automatically updating the certificates. This task will query the certificates that have enabled auto-renewal. Therefore, adding this feature might lead to errors in the scheduled task.

Instead, I think the better solution is to add a feature that uses custom commands to obtain certificates. Once this feature is developed, you can toggle the switch on and use a custom command to obtain the certificate. Meanwhile, the background scheduled task will also call that command to auto-renew the certificate.

**Comment by cpjet64** [comment]
> 

^^^^ THIS!!! That sounds perfect!

**Comment by leic4u** [comment]
> Instead, I think the better solution is to add a feature that uses custom commands to obtain certificates. Once this feature is developed, you can toggle the switch on and use a custom command to obtain the certificate. Meanwhile, the background scheduled task will also call that command to auto-renew the certificate.

may I ask that does there is any progress for the feature, which uses custom commands to issuing certificates?

**Comment by 0xJacky** [comment]
> > Instead, I think the better solution is to add a feature that uses custom commands to obtain certificates. Once this feature is developed, you can toggle the switch on and use a custom command to obtain the certificate. Meanwhile, the background scheduled task will also call that command to auto-renew the certificate.
> 
> may I ask that does there is any progress for the feature, which uses custom commands to issuing certificates?

Sorry, I have not plan to implement this feature due to https://github.com/0xJacky/nginx-ui/issues/100#issuecomment-1509485925
