### ISSUE TITLE
Can‘t LogIn in WebUI.. 

### ISSUE THREAD

**Issue by iSp33dy** [0xJacky/nginx-ui#101]
Where to reset password for WebUI?

Can‘t Login..

pls help..

**Comment by 0xJacky** [comment]
Delete the database.db and then visit http://domain-of-nginxui/#/install to reinstall.

If you used https://github.com/0xJacky/nginx-ui#script-for-linux to install, the database should be located in /usr/local/etc/nginx-ui.

**Comment by Luccifer** [comment]
The "not found" error raised...

**Comment by Luccifer** [comment]
![image](https://github.com/0xJacky/nginx-ui/assets/1053009/c61c384e-f022-4688-8eec-273ec46f8e3b)

**Comment by 0xJacky** [comment]
Can you post your nginx configuration? It seems like a reverse proxy issue.

**Comment by Luccifer** [comment]
Somehow I did managed to reinstall nginx-ui, the problem was db-file was recreated every time with the (same?) data inside.. So I did the clean reinstall with purge and it made a deal
