### ISSUE TITLE
选择证书出现错误

### ISSUE THREAD

**Issue by homegu** [0xJacky/nginx-ui#105]
![image](https://user-images.githubusercontent.com/34022483/233832582-62aabc8a-ca7f-4135-be6e-cf9007fa6578.png)

点击确定出现错误

**Comment by 0xJacky** [comment]
指令里的 ssl_certificate 和 ssl_certificate_key 是不是不存在？

**Comment by 0xJacky** [comment]
感谢您的反馈，已在 26938ae 中优化。当 ssl_certificate 和 ssl_certificate_key 指令不存在时会先自动添加指令。
