### ISSUE TITLE
运行一段时间很快就 CPU 负载高

### ISSUE THREAD

**Issue by sbilly** [0xJacky/nginx-ui#108]
**Describe the bug**
运行一段时间很快就 CPU 负载高

**To Reproduce**
反复访问菜单里面的 `访问日志` 和 `错误日志` 就会让 CPU 负载 100%

**Expected behavior**
低 CPU 负载

**Screenshots**
<img width="1777" alt="image" src="https://user-images.githubusercontent.com/123563/234942283-9c1de515-4120-427d-8c49-11a55fafc869.png">

<img width="678" alt="image" src="https://user-images.githubusercontent.com/123563/234942116-b6ebf800-4525-4ade-bdf3-f738237840dc.png">

**Info (please complete the following information):**
 - Server OS: Ubuntu 22.04 + docker (uozi/nginx-ui:latest  d53dffd3d255）
 - Server Arch: x64
 - Nginx UI Version: 1.8.3(105)
 - Your Browser: Edge

**Additional context**

```
[nginx_log]
AccessLogPath = /va/log/nginx/access.log
ErrorLogPath  = /var/log/nginx/error.log

[openai]
BaseUrl =
Token   =
Proxy   =
Model   =

[git]
Url                =
AuthMethod         =
Username           =
Password           =
PrivateKeyFilePath =

[server]
HttpPort          = 9000
RunMode           = release
JwtSecret         = xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
HTTPChallengePort = 9180
Email             = xxx@xxx.com
Database          = database
StartCmd          = bash
CADir             =
Demo              = false
PageSize          = 10
GithubProxy       =
NginxConfigDir    =
NginxPIDPath      =
```

**Comment by 0xJacky** [comment]
我这边试了两台服务器，均无法复现...

**Comment by 0xJacky** [comment]
您用的是哪个浏览器

**Comment by 0xJacky** [comment]
CPU占用100%的时候，可以用 docker logs nginx-ui 看一下日志吗

**Comment by 0xJacky** [comment]
复现了，你的 access log path 设置错了，应该是 /var。对于不存在的记录，会造成 CPU 满载，这是个 bug，明天修复

**Comment by 0xJacky** [comment]
Fixed in 2c675be，感谢您的反馈
