### ISSUE TITLE
Force HTTPS

### ISSUE THREAD

**Issue by Germwalker** [0xJacky/nginx-ui#109]
Hello, 

Can you force the HTTPS redirection like the _certbot --nginx_ plugin ? 
It's more safe than the current implementation.

Like appending this to the conf file :
```
server {
    if ($host = example.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    server_name example.com;
    listen 80;
    return 404; # managed by Certbot
}
```

Maybe it could be a button to force the HTTPS redirection ?

**Comment by 0xJacky** [comment]
I am sorry that we cannot implement this feature, I had explained the reason why we cannot do this in issue #100.

**Comment by Germwalker** [comment]
I understand the problem you faced with this snippet added by certbot by reading #100.

But I only gave this code as an example of the forced http to https redirection, I have no interest in using certbot if nginx-ui can deal with certificates and auto renew on it's own. 

What do you think about the 80 to 443 forced redirection ?

**Comment by 0xJacky** [comment]
We have the forced redirection template, please check it in your site edit page 😄

<img width="933" alt="image" src="https://user-images.githubusercontent.com/13096985/235308334-0f030857-19f7-4b99-976e-71231feae326.png">

**Comment by 0xJacky** [comment]
Sorry, I misunderstood. We will modify the current template as soon as possible.

**Comment by 0xJacky** [comment]
Added in c2a3cb6, and maybe we will make it as a button in v2.0, thanks for your sugguestion.
