### ISSUE TITLE
[AutoCert] Recover runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ZoutigeWolf** [0xJacky/nginx-ui#110]
I just installed nginx-ui on ubuntu server with the linux installscript but when i start the service with `sudo systemctl start nginx-ui` it gives me this output in the systemctl status:

```
nginx-ui.service - Yet another WebUI for Nginx
     Loaded: loaded (/etc/systemd/system/nginx-ui.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2023-04-29 17:37:08 UTC; 7min ago
       Docs: https://github.com/0xJacky/nginx-ui
   Main PID: 1147044 (nginx-ui)
      Tasks: 20 (limit: 9155)
     Memory: 34.9M
        CPU: 3.859s
     CGroup: /system.slice/nginx-ui.service
             ├─1147044 /usr/local/bin/nginx-ui -config /usr/local/etc/nginx-ui/app.ini
             └─1147070 /usr/local/bin/nginx-ui -config /usr/local/etc/nginx-ui/app.ini

Apr 29 17:37:08 zoutige-server systemd[1]: Started Yet another WebUI for Nginx.
Apr 29 17:37:09 zoutige-server nginx-ui[1147070]: 2023/04/29 17:37:09 Nginx config dir path: /etc/nginx
Apr 29 17:37:09 zoutige-server nginx-ui[1147070]: 2023/04/29 17:37:09 [AutoCert] Start
Apr 29 17:37:09 zoutige-server nginx-ui[1147070]: 2023/04/29 17:37:09 [Nginx UI] RecordServerAnalytic Started
Apr 29 17:37:09 zoutige-server nginx-ui[1147070]: 2023/04/29 17:37:09 [AutoCert] Recover runtime error: invalid memory address or nil pointer dereference
```

It looks like AutoCert is having memory issues.
Would it be possible to run nginx-ui without ssl?

**To Reproduce**
1. Install nginx-ui with the linux installscript
2. Run the service with `sudo systemctl start nginx-ui`
3. Run `sudo systemctl status nginx-ui`

**Expected behavior**
I was expecting to see the install screen when visiting `<server_ip>:9000/install` but i got a timeout instead

**Info**
 - Server OS: Ubuntu 22.04.2
 - Server Arch: LTS x86_64
 - Nginx UI Version: 1.8.3
 - Browser: Arc, Safari

**Comment by ZoutigeWolf** [comment]
Looks like nginx-ui requires you to run it with ssl through nginx.
I added the nginx-ui to my nginx configuration with an ssl certificate and now it works.

**Comment by 0xJacky** [comment]
If you’re using a cloud server, please make sure that port 9000 is open.

**Comment by ZoutigeWolf** [comment]
Yeah port 9000 wasn't forwarded so I had to run it through Nginx on port 443
