### ISSUE TITLE
网站管理-添加站点-location内容无保存

### ISSUE THREAD

**Issue by m00zh33** [0xJacky/nginx-ui#116]
网站管理-添加站点-location内容无保存

**To Reproduce**
1. Go to '网站管理，添加站点，location部分'
2. Click on 'add'
3. 输入
4. 保存

**Expected behavior**
网站管理-添加站点-location-add，输入内容后保存，显示保存的输入内容；

**Screenshots**

![111](https://github.com/0xJacky/nginx-ui/assets/4264383/d0b1c34c-31ec-4c8b-b7bc-b2fa1490ebc2)

**Info (please complete the following information):**
 - Server OS: MacOS Monterey
 - Server Arch:  x86_64
 - Nginx UI Version: 1.9.9
 - Your Browser: Edge 112.0.1722.68

**Comment by 0xJacky** [comment]
感谢反馈，已在 6c38b11 中修复，目前您可以先直接下一步，在站点修改中修改 Locations

**Comment by m00zh33** [comment]
验证一下6c38b11,8c5ee48两个版本，还是add location，save之后，no data；这2个版本是我直接在页面切换，然后download下来，安装运行的
