### ISSUE TITLE
nginx-ui use 100% CPU

### ISSUE THREAD

**Issue by skrilax91** [0xJacky/nginx-ui#129]
**Describe the bug**
Nginx-ui use all cpu resources from the server

**To Reproduce**
1. Install nginx-ui with installer

**Expected behavior**
a normal consumption

**Screenshots**
![image](https://github.com/0xJacky/nginx-ui/assets/6585219/1dec658d-3e35-458f-bec9-c7cc5d471fa5)

**Info (please complete the following information):**
 - Server OS: Ubuntu 22.04
 - Server Arch: amd64
 - Nginx UI Version: v1.9.9
 - Your Browser: Firefox

**Comment by 0xJacky** [comment]
Hello, can you provide us with more information? I just installed nginx-ui v1.9.9-4 via install shell on my Ubuntu 22.04 vm, it works normally. Please execute this command `journalctl -u nginx-ui -n 100` to fetch the latest 100 lines of logs and share them to us, thanks for your report.

**Comment by skrilax91** [comment]
I just checked if nginx-ui consume all resource today but all is good now.
For information, i was trying to upgrade to latest version before nginx-ui start to take 100% CPU, i tried 4 time because nothing append after i request the upgrade.
Maybe my spam on the upgrade feature make nginx-ui crazy.

**Comment by 0xJacky** [comment]
Ok, if you find any further  details related to this problem, feel free to reopen it for further investigation.
