### ISSUE TITLE
Cant enable/save files due to a warning derived from using nginx-ultimate-bad-bot-blocker

### ISSUE THREAD

**Issue by FlurryNight** [0xJacky/nginx-ui#132]
**Describe the bug**
First, thank you for this project, This is the best UI I've found for NGINX since i remember, I've been using it several times flawlessly.

However i started using [nginx-ultimate-bad-bot-blocker](https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker) and since its has several rules and checks, `nginx -t` thinks the configuration is incorrect giving the following output in the screenshot

But it's not https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/issues/516, 

**To Reproduce**
Add nginx-ultimate-bad-bot-blocker to a NGINX server and try to enable/disable sites in Nginx UI

**Expected behavior**
This behavior is expected as it its a good measure to check before applying changes, however if its was possible to override it in the UI, like a toggle: Allow to continue if warn?: on/off, or other better way

**Screenshots**
![image](https://github.com/0xJacky/nginx-ui/assets/47457170/e27c31c0-30c9-490f-9365-221f2faa4a34)

**Info (please complete the following information):**
 - Server OS: Ubuntu 22.04
 - Server Arch: amd64
 - Nginx UI Version: v1.9.9
 - Your Browser: Firefox
 
**Additional**
Also, but not related, it was nice that the custom templates could be loaded from a folder like /etc/nginx/templates, instead of the bundled ones, It would be easier to manage them instead of needing to compile it whenever i need to change the template or update nginx-ui, also it helps not "bloat" the server or other machine with build tools.

I would appreciate, Thanks again. 
Waiting for feedback on how to solve this

**Comment by 0xJacky** [comment]
Hello, this issue has been resolved in v2.0.0, and you can upgrade the nginx-ui via the upgrader in web ui.
