### ISSUE TITLE
Russian & English switched

### ISSUE THREAD

**Issue by massitheduck** [0xJacky/nginx-ui#134]
**Describe the bug**
On the latest docker image the Russian and English Languages are switched.

**To Reproduce**
1. Pull & Start Image
2. See that you cant understand anything because of the russian text
3. Change the language to "Ru" to make it English

**Expected behavior**
It shouldnt be switched

**Screenshots**
![Screenshot from 2023-06-09 05-34-23](https://github.com/0xJacky/nginx-ui/assets/130237406/708b8856-e1c1-42b7-9950-9333157ad025)

**Info (please complete the following information):**
 - Server OS: Debian 11
 - Server Arch: amd64
 - Nginx UI Version: 2.0.0-beta.2 (5)
 - Your Browser: Firefox

**Comment by 0xJacky** [comment]
OK, I will try to reproduction this issue. I just pulled the latest codes from dev branch and built it, howerver it works normally.

**Comment by 0xJacky** [comment]
Oh, the demo also has this problem. I will fix it as soon as possible, thanks for your report.

**Comment by 0xJacky** [comment]
Well, I just re-executed the GitHub Action workflow this github action workflow(https://github.com/0xJacky/nginx-ui/actions/runs/5133640644) and this issue is fixed now.
