### ISSUE TITLE
What are Environement?

### ISSUE THREAD

**Issue by Buco7854** [0xJacky/nginx-ui#137]
Hi, just wanted to know what was the "Environement" tab please.
Also, the demo site seems to have some issue btw, 'no such file or directory' error when consulting the configurations and sites tab.
![image](https://github.com/0xJacky/nginx-ui/assets/80671351/27727f24-9761-4471-88bc-399258a581a6)

![image](https://github.com/0xJacky/nginx-ui/assets/80671351/e44c414c-36e9-489c-bbb8-a0c64e18a63b)

**Comment by 0xJacky** [comment]
Maybe someone delete the site configurations directory in demo container, and I recreated the container, now you can visit the sites list page in demo.

The "Environement" tab is use to add multiple nginx-ui servers, so you can manage other servers in a single web ui, please note that this feature is still under development.

**Comment by Buco7854** [comment]
Oh I see, thanks. I'll go and see then, I wasnt really sure if it was that and i'm gonna go and see if it can meet what I was planning on doing. keeping you in touch if I succed or if I need more information.

**Comment by Buco7854** [comment]
Just checked, its perfect. Thanks a lot for your help and to you and Hintay for the software.
