### ISSUE TITLE
Upstream backend and load balancing

### ISSUE THREAD

**Issue by mosaati** [0xJacky/nginx-ui#138]
**Is your feature request related to a problem? Please describe.**
No option to set a multi host backend. Has to be set manually through entering them in the config for proxy pass.

**Describe the solution you'd like**
It would be easier if there was an interface setting to enable or disable an option to set a backend of multiple hosts and define them with multiple options for the load balancing algorithm.

**Describe alternatives you've considered**
manual edit.

nginx-ui looks great. Great job.

**Comment by 0xJacky** [comment]
Thanks, we are very busy recently, this feature will be added in v2.0.

**Comment by graphicfox** [comment]
Is there any estimate when 2.0 will be ready? Love the work you did and looking forward to an ui for load balancing.

**Comment by 0xJacky** [comment]
> Is there any estimate when 2.0 will be ready? Love the work you did and looking forward to an ui for load balancing.

Maybe later this month😄

**Comment by leic4u** [comment]
Expecting this feature.
