### ISSUE TITLE
Can't login to demo

### ISSUE THREAD

**Issue by arye321** [0xJacky/nginx-ui#139]
https://demo.nginxui.com/

![image](https://github.com/0xJacky/nginx-ui/assets/9559551/de11afdc-d3f3-4dc2-bf44-3ecc236ca581)

**Comment by 0xJacky** [comment]
Fixed, thanks for your report!JackyOn Jul 10, 2023, at 11:43 AM, arye321 ***@***.***> wrote:﻿
https://demo.nginxui.com/

**Comment by AlexTryHarder** [comment]
Still erroring for me.

**Comment by 0xJacky** [comment]
> 

There might be some issues in our cron job worker which is used to automatically restart demo container, I just restart it manually, and I will fix it later this week.


Thanks for your report.

**Comment by AlexTryHarder** [comment]
Works fine after you restarted it, thanks!
