### ISSUE TITLE
Can´t activate Logs

### ISSUE THREAD

**Issue by iSp33dy** [0xJacky/nginx-ui#147]
If I want to activate the access logs and error logs, I get the error that the path is empty.
If I follow the instructions (https://nginxui.com/guide/config-nginx-log.html), I get the same result...

How do I enter the correct path to be able to evaluate the log in the web UI?

**Info **
 - Server OS: Debian 11.7 LXC
- Server Host: Proxmox v8.0.3
 - Nginx UI Version:  2.0.0-beta.3
 - Your Browser: Firefox, Safari, Chrome

Greetings

**Comment by 0xJacky** [comment]
Hi, we metion this changes in release https://github.com/0xJacky/nginx-ui/releases/tag/v2.0.0-beta.3

v2.0.0 is still under development, once we release stable version, we will upgrade the document site.
