### ISSUE TITLE
无法删除，新增也不显示

### ISSUE THREAD

**Issue by homegu** [0xJacky/nginx-ui#149]
![image](https://github.com/0xJacky/nginx-ui/assets/34022483/dbb493cd-a11f-448f-9ec3-4d1b47c2c165)

删除列表不消失，出现错误，增加也显示增加成功 列表不显示

**Comment by homegu** [comment]
![image](https://github.com/0xJacky/nginx-ui/assets/34022483/0c8d5101-eebb-4ad1-a8eb-082f2905e976)

**Comment by 0xJacky** [comment]
Nginx UI 遵循 Debian 的网页服务器配置文件标准。创建的网站配置文件将会放置于 Nginx 配置文件夹（自动检测）下的 sites-available 中，启用后的网站将会创建一份配置文件软连接到 sites-enabled 文件夹。您可能需要提前调整配置文件的组织方式。

对于非 Debian (及 Ubuntu) 系统，您可能需要将 nginx.conf 配置文件中的内容修改为如下所示的 Debian 风格。

http {
	# ...
	include /etc/nginx/conf.d/*.conf;
	include /etc/nginx/sites-enabled/*;
}
更多信息请参阅：[debian/conf/nginx.conf](https://salsa.debian.org/nginx-team/nginx/-/blob/master/debian/conf/nginx.conf#L59-L60)

**Comment by homegu** [comment]
![Uploading image.png…]()
那这几个无法删除，怎么办

**Comment by homegu** [comment]
新增的也看不到，刚添加了一个域名，已经加入这个：



http {
# ...
include /etc/nginx/conf.d/.conf;
include /etc/nginx/sites-enabled/;
}

**Comment by 0xJacky** [comment]
麻烦请检查一下 /etc/nginx 目录下是否存在 sites-enabled 和 sites-available 两个文件夹，并确保 sites-enabled 中的文件都是 sites-available 文件的软连接JackyOn Aug 1, 2023, at 2:48 PM, homegu ***@***.***> wrote:﻿
新增的也看不到，刚添加了一个域名，已经加入这个：
http {
...
include /etc/nginx/conf.d/.conf;
include /etc/nginx/sites-enabled/;
}

**Comment by 0xJacky** [comment]
参考：https://github.com/0xJacky/nginx-ui/issues/153
