### ISSUE TITLE
不考虑支持一下armbian吗，例如玩客云32位系统。

### ISSUE THREAD

**Issue by indiboy** [0xJacky/nginx-ui#15]

**Comment by 0xJacky** [comment]
现在 Release 页面里的 Linux-386 版本可以用吗，那个就是支持32位 Linux 的版本。

**Comment by indiboy** [comment]
测试了一下不可以的，安装脚本提示 The architecture is not supported   uname 如下
Linux onecloud902 5.18.0-rc3-meson #trunk SMP Fri Jun 3 21:54:57 UTC 2022 armv7l GNU/Linux
-------------
Release 页面里的 Linux-386 版本 提示 可执行文件格式错误

**Comment by 0xJacky** [comment]
好的 我们看一下

**Comment by 0xJacky** [comment]
@Hintay 我使用了小米路由器 R1D (BCM4709, armv7l, 不支持 vfp) 作为测试，使用 armv5 的发行版，可以正常运行。

<img width="1996" alt="image" src="https://user-images.githubusercontent.com/13096985/177678519-d05ddb70-f302-4f2c-8815-72c8093b931c.png">

![image](https://user-images.githubusercontent.com/13096985/177678531-6ca7062e-0832-4905-a79b-4959693ab982.png)

**Comment by 0xJacky** [comment]
好的 后面我们看看

Jacky
