### ISSUE TITLE
Conf files not found

### ISSUE THREAD

**Issue by Spleenftw** [0xJacky/nginx-ui#156]
Hello,

I got multiple files on my nginx vm : 

```
root@nginx:/etc/nginx/conf.d# ls -l
total 16
-rw-r--r-- 1 root root 1061 Jul  6 11:57 default.mydomainname.xyz.conf
-rw-r--r-- 1 root root 1428 Aug  2 16:10 site1.mydomainname.xyz.conf
-rw-r--r-- 1 root root  862 Jul 27 19:28 site2.mydomainname.xyz.conf
-rw-r--r-- 1 root root 1491 Jul  6 11:55 site3.mydomainname.xyz.conf
```

and i got this line in my nginx.conf : 

```
include /etc/nginx/conf.d/*.conf;
```

But in my "Sites List", it's juste giving me an error that /etc/nginx/sites-enabled: no such file or directory. 

i kinda don't get it

**Comment by 0xJacky** [comment]
This is a common issue, please check our documentation: https://nginxui.com/guide/getting-started.html

## Before Use
The Nginx UI follows the Debian web server configuration file standard. Created site configuration files will be placed in the sites-available folder that under the Nginx configuration folder (auto-detected). The configuration files for an enabled site will create a soft link to the sites-enabled folder. You may need to adjust the way the configuration files are organised.

For non-Debian (and Ubuntu) systems, you may need to change the contents of the nginx.conf configuration file to the Debian style as shown below.

```nginx
http {
	# ...
	include /etc/nginx/conf.d/*.conf;
	include /etc/nginx/sites-enabled/*;
}
```
For more information: [debian/conf/nginx.conf](https://salsa.debian.org/nginx-team/nginx/-/blob/master/debian/conf/nginx.conf#L59-L60)


In your case, you need to create `/etc/nginx/sites-enabled` and `/etc/nginx/sites-available`, move `/etc/nginx/conf.d/*` to `/etc/nginx/sites-available/`, then add `include /etc/nginx/sites-enabled/*;` under `include /etc/nginx/conf.d/*.conf;`, finally reload nginx, and you will see the sites list.
