### ISSUE TITLE
Is it possible to auto-request certificates from not-only Let's Encrypt service?

### ISSUE THREAD

**Issue by Arustinal** [0xJacky/nginx-ui#16]
UI allows to automatically request certificates from Let's Encrypt.

I am using certbot, but not a Let's Encrypt service, just other.
Can i setup nginx-ui for that case?

**Comment by 0xJacky** [comment]
Sorry, we currently support only Let's Encrypt service. Maybe we will add this feature in the future.

**Comment by 0xJacky** [comment]
Sorry, we currently support only Let’s Encrypt service. Maybe we will add this feature in the future.

Jacky

**Comment by xuandung38** [comment]
Please support zerossl
