### ISSUE TITLE
Add support for stream sites (not just http sites)

### ISSUE THREAD

**Issue by BlindBadgerStudios** [0xJacky/nginx-ui#166]
**Is your feature request related to a problem? Please describe.**
Enhancement - Add support for stream sites (not just http sites).  

**Describe the solution you'd like**
I'd want a duplication of the setup for http sites, but for stream sites (stream-available/stream-enabled folders, etc).  This would easily and quickly allow adding non http sites to the config and add functionality (first version could just be the "advanced view" until all the fields could be developed for the "basic view".

**Describe alternatives you've considered**
Manual config of the base nginx.conf is what I'm doing now, which puts me at the CLI (which reduces the value of the nginx-ui setup for me)

**Additional context**
Stream sites are especially needed when front-ending kubernetes clusters and simplifying this would expand the usefulness of this to even better compete with nginx-proxy-manager and provide a good option for those of us who don't want to run a docker image to manage our nginx instances.

**Comment by AravindhStanley** [comment]
I second the addition of streams with health checks
