### ISSUE TITLE
Can't update Let's encrypt certs because port 9180 isn't listening

### ISSUE THREAD

**Issue by iterprise** [0xJacky/nginx-ui#167]
Can't update Let's encrypt certs because port 9180 isn't listening

 - Server OS: Ubuntu 22.04.3 LTS
 - Server Arch: x64
 - Nginx UI Version:  v1.9.9

curl http://127.0.0.1:9180
curl: (7) Failed to connect to 127.0.0.1 port 9180 after 0 ms: Connection refused

![image](https://github.com/0xJacky/nginx-ui/assets/19260096/5b983935-c97c-4947-ae88-8f5ab3bdd75b)

**Comment by 0xJacky** [comment]
Hi, port 9180 only listening when issuing the cert, we need to check logs for more details.JackyOn Sep 13, 2023, at 4:07 AM, iterprise ***@***.***> wrote:﻿
Can't update Let's encrypt certs because port 9180 isn't listening

Server OS: Ubuntu 22.04.3 LTS
Server Arch: x64
Nginx UI Version:  v1.9.9

curl http://127.0.0.1:9180
curl: (7) Failed to connect to 127.0.0.1 port 9180 after 0 ms: Connection refused

**Comment by iterprise** [comment]
What logs do you need?

For ex:
`13.59.60.96 - - [12/Sep/2023:19:49:34 +0000] "GET /.well-known/acme-challenge/c0d3 HTTP/1.1" 307 180 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"`

We got 307 because nginx can't connect to 9180

```
server {
    listen 80;
    listen [::]:80;
    server_name interprise.me;
    location /.well-known/acme-challenge {
        proxy_set_header Host $host;
        proxy_set_header X-Real_IP $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr:$remote_port;
        proxy_pass http://127.0.0.1:9180;
    }
    return 307 https://$server_name$request_uri;
}
```

**Comment by 0xJacky** [comment]
Try to move this block to 443 server

```
location /.well-known/acme-challenge {
        proxy_set_header Host $host;
        proxy_set_header X-Real_IP $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr:$remote_port;
        proxy_pass http://127.0.0.1:9180;
    }
```

**Comment by 0xJacky** [comment]
Let's Encrpty try to connect to http (port 80) in the beginning, but you added`return 307 https://$server_name$request_uri;` so the request was redirect to https (port 443), however there was no rule for acme-challenge in your 443 server, so Let's encrypt challenge failed.

**Comment by iterprise** [comment]
```
server {
    listen 80;
    listen [::]:80;
    server_name interprise.me;
    location /.well-known/acme-challenge {
        proxy_set_header Host $host;
        proxy_set_header X-Real_IP $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr:$remote_port;
        proxy_pass http://127.0.0.1:9180;
    }
    return 307 https://$server_name$request_uri;
}
```
I thought that the location /.well-known/acme-challenge worked before return. I understand that it isn't a problem with nginx-ui, but it's still strange. I wanted to avoid adding a rule about .well-known to the HTTPS section. Than you for you help.
