### ISSUE TITLE
integration with terminal/shell

### ISSUE THREAD

**Issue by mohamad-supangat** [0xJacky/nginx-ui#17]
Maybe instead of adding a lot of features, it's better to add one feature that is used very often.
  **terminal/shell**
maybe like a webmin terminal, making this a complete application, without having to ssh into the server

thank you for this very cool application, I use it to handle my proxy

**Comment by 0xJacky** [comment]
We added online Terminal fearture in v1.4.0, you can try the [v1.4.0-rc1](https://github.com/0xJacky/nginx-ui/releases/tag/v1.4.0-rc1) version to test.

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/13096985/177596073-d1d1f8a2-9d91-4a5e-b08a-a5ba8b1023b2.png">

**Comment by mohamad-supangat** [comment]
Tanks @0xJacky work perfect for my android server

![image](https://user-images.githubusercontent.com/48933993/177914249-5ac19e29-1c28-47b7-b2a2-b32a841eca4e.png)

![image](https://user-images.githubusercontent.com/48933993/177914320-0e48cde5-f6f9-4c21-aa0a-d2901a055ed0.png)
