### ISSUE TITLE
NginxUI port

### ISSUE THREAD

**Issue by RizqiSyahrendra** [0xJacky/nginx-ui#171]
**Is your feature request related to a problem? Please describe.**
I am confused, in docker container how to define custom port for admin page (nginx ui) but keep using 80/443 as default built-in nginx http/https port? just for security purposes, so there's no one can access the admin page (nginx ui) unless owner

**Describe the solution you'd like**
Using dockerfile or docker compose environment variable, for example : NGINXUI_PORT=9090

**Comment by 0xJacky** [comment]
You can add a port mapping in docker_compose.yml as follows:
```
- "9000:9090" 
```

Alternatively, add a port mapping parameter `-p9000:9090` when starting the nginx ui container. Additionally, remove the `conf.d/nginx-ui.conf` file from the nginx configuration directory on your host, then recreate the container. This should meet your requirements.

**Comment by RizqiSyahrendra** [comment]
> You can add a port mapping in docker_compose.yml as follows:
> 
> ```
> - "9000:9090" 
> ```
> 
> Alternatively, add a port mapping parameter `-p9000:9090` when starting the nginx ui container. Additionally, remove the `conf.d/nginx-ui.conf` file from the nginx configuration directory on your host, then recreate the container. This should meet your requirements.

I see, I didn't realize that default port of the nginxui is 9000 and you already proxied it to 80 through nginx, thank you it meets my requirement now. btw a little typo, the mapping should be "9090:9000"
