### ISSUE TITLE
Need DNS Credentials Documents

### ISSUE THREAD

**Issue by leic4u** [0xJacky/nginx-ui#175]
I configured the DNS Credentials, but still I don't know how to issue a cert.

Is there some guide to tell me how to use the panel?

**Comment by 0xJacky** [comment]
Please refer to this post: https://github.com/0xJacky/nginx-ui/discussions/174

**Comment by leic4u** [comment]
> You don't need to install a acme.sh, please refer to this post for more infomations: #174 

感谢开发者。我在站点管理的详情页去配置指令的时候发现了在这里可以申请证书。

不过我建议应该有一个地方允许用户申请通配符证书，并在站点配置中让用户可以选择该通配符证书。
