### ISSUE TITLE
Demo website not working with admin/admin

### ISSUE THREAD

**Issue by LodiAleardo** [0xJacky/nginx-ui#176]
**Describe the bug**
When I try to access to https://demo.nginxui.com/#/login?next=/dashboard with admin/admin the website is not allowing me inside with this credentials

**Comment by Hintay** [comment]
We have identified that the operation synchronization feature was causing crashes. As a temporary measure, we have disabled this feature and plan to refactor it in the future.

We are pleased to inform you that the demo site is now fully functional for logins. Should you encounter any further issues, please do not hesitate to leave a comment.
