### ISSUE TITLE
日志路径怎么设置通配符

### ISSUE THREAD

**Issue by zouchengli** [0xJacky/nginx-ui#179]
例如，我想查看/var/log/nginx/access*.log

**Comment by zouchengli** [comment]
<img width="952" alt="image" src="https://github.com/0xJacky/nginx-ui/assets/27568522/bb39397a-a088-4b14-ba6d-d4004562a09e">

**Comment by zouchengli** [comment]
<img width="346" alt="image" src="https://github.com/0xJacky/nginx-ui/assets/27568522/54ce3bc3-5bd3-42dc-b3e2-4052e7a35db8">

**Comment by 0xJacky** [comment]
暂不支持使用通配符查看噢
