### ISSUE TITLE
使用2.0.0-beta.3出现的两个问题

### ISSUE THREAD

**Issue by White1221** [0xJacky/nginx-ui#181]
1.通过仪表盘链接到另一个环境时，仪表盘按钮上方显示本地的地方会出现名称叠加的现象；
2.使用终端界面每点进去一次就会有一个衍生进程login，如果不重启nginx-ui服务会造成cpu爆满。

**Comment by 0xJacky** [comment]
收到，我周末确认一下

**Comment by 0xJacky** [comment]
问题1 方便截个图看看不，我这边用的最新的Chrome浏览器，没有遇到呢

**Comment by 0xJacky** [comment]
问题2 已经在 2982782 修正，预计这两天会发 beta.4

**Comment by White1221** [comment]
> 问题1 方便截个图看看不，我这边用的最新的Chrome浏览器，没有遇到呢

> 问题1 方便截个图看看不，我这边用的最新的Chrome浏览器，没有遇到呢

![Uploading 问题截图01.jpg…]()

**Comment by White1221** [comment]
> 问题1 方便截个图看看不，我这边用的最新的Chrome浏览器，没有遇到呢

![Uploading 问题截图01.jpg…]()

**Comment by White1221** [comment]
> 问题2 已经在 [2982782](https://github.com/0xJacky/nginx-ui/commit/298278272195b126120f96ef3d96bd7939e46644) 修正，预计这两天会发 beta.4

这个我为了登陆方便，会把app.ini配置文件的StartCmd = login改为bash，可以免密登陆应该不影响吧；还有ReloadCmd和RestartCmd的值应该怎么写呢

**Comment by White1221** [comment]
> 问题1 方便截个图看看不，我这边用的最新的Chrome浏览器，没有遇到呢

**Comment by White1221** [comment]
> 问题1 方便截个图看看不，我这边用的最新的Chrome浏览器，没有遇到呢

**Comment by White1221** [comment]
> 问题1 方便截个图看看不，我这边用的最新的Chrome浏览器，没有遇到呢

**Comment by 0xJacky** [comment]
不影响，是我没有kill exec.Command

**Comment by 0xJacky** [comment]
这两个是自定义 nginx 重启或重载的命令的，一般不需要改

**Comment by 0xJacky** [comment]
问题1 方便截个图看看不，我这边用的最新的Chrome浏览器，没有遇到呢

**Comment by White1221** [comment]
> 问题1 方便截个图看看不，我这边用的最新的Chrome浏览器，没有遇到呢

这个我这里图片贴不进去，我邮箱回复了，不知道您能看见吗；我用文字再描述一遍：在环境选项里添加，名称如果写的过长，在仪表盘链接此环境后，仪表盘上方会无法正常显示名称，呈现的是叠加样式，我用的浏览器是Microsoft Edge版本 119.0.2151.44 (正式版本) (64 位)

**Comment by 0xJacky** [comment]
我这边看不到

**Comment by 0xJacky** [comment]
行，我试试

**Comment by White1221** [comment]
> 行，我试试

![img_v3_024u_1bfa44eb-9d17-4d5a-bfcf-9670bba1d13g](https://github.com/0xJacky/nginx-ui/assets/86450840/c07a5e07-a8ae-44ba-9c97-1116936b6ba5)
![img_v3_024u_271e5295-6d4a-416f-93a6-e8e8975adc1g](https://github.com/0xJacky/nginx-ui/assets/86450840/3ca869ee-1e88-46c8-a4f3-a7a6f180a924)

**Comment by 0xJacky** [comment]
看到了

**Comment by White1221** [comment]
> 这两个是自定义 nginx 重启或重载的命令的，一般不需要改

可是默认等号右边是空的呀，什么都不要写么？在页面点重启和重载进程并没有改变

**Comment by 0xJacky** [comment]
是这样，默认的命令是 nginx -s reopen 和 nginx -s reload，如果因为环境原因导致这两个命令执行不了或者是说你需要用自定义的命令，才需要写

**Comment by White1221** [comment]
> 是这样，默认的命令是 nginx -s reopen 和 nginx -s reload，如果因为环境原因导致这两个命令执行不了或者是说你需要用自定义的命令，才需要写

我的重启是nginx -s restart，重载是nginx -s reload；目前配置文件ReloadCmd和RestartCmd是默认空着的，页面点击重载后worker进程无变化我该怎么排查

**Comment by 0xJacky** [comment]
改了配置文件之后，点这两个按钮之后有效果不，有效果就不用管了

**Comment by White1221** [comment]
> 改了配置文件之后，点这两个按钮之后有效果不，有效果就不用管了

默认空白是没有效果的，我自定义命令也没有效果，但无论哪种在页面点击都提示成功
![Uploading img_v3_024u_606c6a1b-0348-4f30-bb72-325b692621ag.jpeg…]()

**Comment by 0xJacky** [comment]
直接在 ssh 执行这两个命令有效果吗

**Comment by White1221** [comment]
终端执行是好的

**Comment by 0xJacky** [comment]
方便说一下主机的系统，nginx 的版本，以及 nginx 安装的方式？我看看能否复现

**Comment by White1221** [comment]
> 方便说一下主机的系统，nginx 的版本，以及 nginx 安装的方式？我看看能否复现

Linux version 3.10.0-957.el7.x86_64
nginx version: nginx/1.20.2
configure arguments: --prefix=/usr/local/nginx --with-http_ssl_module --with-http_v2_module --with-http_realip_module --with-http_addition_module --with-http_sub_module --with-http_stub_status_module --with-http_gzip_static_module --with-http_addition_module --with-pcre --with-stream
安装的时候都是root用户操作的

**Comment by 0xJacky** [comment]
ubuntu、centos还是什么系统呢

**Comment by White1221** [comment]
CentOS Linux release 7.6.1810 (Core)

**Comment by 0xJacky** [comment]
nginx 是怎么安装的，yum 吗

**Comment by White1221** [comment]
tar包本地编译安装的，版本是1.20.2

**Comment by 0xJacky** [comment]
试试在 ReloadCmd 和 RestartCmd 中配置完整的 nginx 可执行路径，猜测可能是 go 没读到环境变量

**Comment by White1221** [comment]
可以了，使用绝对路径就可以，感谢
