### ISSUE TITLE
Update deprecated TLS directives 

### ISSUE THREAD

**Issue by ollie-galbraith** [0xJacky/nginx-ui#183]
**Is your feature request related to a problem? Please describe.**
Hoping you can update the default TLS directives from the deprecated 
```
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
...
}
```
to the current directive of 
```
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
...
}
```

reference - https://www.nginx.com/blog/nginx-plus-r30-released/

**Comment by 0xJacky** [comment]
Thanks
