### ISSUE TITLE
启动异常，页面可以打开，但是运行不了，网站列表提示

### ISSUE THREAD

**Issue by StoneNBS** [0xJacky/nginx-ui#186]
这个很奇怪，有没有不连接github的国内网速很慢
![image](https://github.com/0xJacky/nginx-ui/assets/14786494/79b414ba-838c-4aba-9bd3-6763b2c09297)

**Comment by 0xJacky** [comment]
请参考：https://nginxui.com/zh_CN/guide/getting-started.html#%E4%BD%BF%E7%94%A8%E5%89%8D%E6%B3%A8%E6%84%8F
