### ISSUE TITLE
在 install 页面选择语言之后页面在 login 和 install 之间疯狂跳转

### ISSUE THREAD

**Issue by leic4u** [0xJacky/nginx-ui#189]
**Describe the bug**
docker compose 部署，v2.0.0 beta 4。

通过 `域名:9000` 进入面板，自动跳转 install 页面。

不点注册，点切换语言。

页面就开始在 install 和 login 之间来回跳。

只能 `docker restart nginx-ui` ，页面停止跳转，但不能刷新，刷新又开始了。

运气好停在 install 页面就能注册，运气不好停在 login 页面，只能再来一次，直到停到 install 页面。

![image](https://github.com/0xJacky/nginx-ui/assets/32786903/c86a4637-430f-4fac-8331-9f2c6d1ad59d)

**Comment by 0xJacky** [comment]
感谢反馈，已在 ba4aeb8 中修复
