### ISSUE TITLE
添加站点功能导致404

### ISSUE THREAD

**Issue by BeanKaKa** [0xJacky/nginx-ui#19]
因站点目前已404无法做相关截图，见谅。
我在演示站点中使用添加网站功能，随便输入字符单击下一步后报错。这可能是导致目前站点404的原因，这可能是个漏洞，没有对用户输入过滤。并且页面css似乎有问题，可能是设计出错。
如果可以我喜欢能够提供一些建议，比如：反向代理、负载均衡、站点流量统计等

**Comment by 0xJacky** [comment]
目前站点404已修复，是因为演示站点的 default 配置文件被禁用了（虽然每个小时会恢复），我这边后面会考虑做禁止关闭 nginx ui 所在的配置，

用户输入过滤的问题后面会优化，css 的样式是已知问题，请等待下一次更新，

感谢您对 Nginx UI 功能的建议，后续有空应该会进一步完善。
