### ISSUE TITLE
Add support Angie web server

### ISSUE THREAD

**Issue by adammakowskidev** [0xJacky/nginx-ui#191]
Hi. 
Can you add support for Angie Web server as well?  This is a very nice fork of nginx.  It is also being developed rapidly.

https://angie.software/en/
Angie is an efficient, powerful, and scalable web server that was forked from nginx:
- Conceived by nginx ex-devs to extend the functionality far beyond the original.
- Acts as a drop-in replacement for nginx without major configuration changes. 

I tried using it and already tested it, but there is a problem with finding the executable file in Path location in nginx-ui

`"exec: "nginx": executable file not found in $PATH"`

How to solve this problem?

**Comment by 0xJacky** [comment]
Please use v2-beta of Nginx UI, and you can set the configuration directory, reload command and restart command maually. Once you set these parameters, Nginx UI will not try to exec the default nginx command.

You can modify the app.ini file to set them.
```
[nginx]
AccessLogPath = /var/log/nginx/access.log
ErrorLogPath  = /var/log/nginx/error.log
ConfigDir    =
PIDPath       =
ReloadCmd     =
RestartCmd    =
```

**Comment by adammakowskidev** [comment]
[nginx]
AccessLogPath = /var/log/angie/access.log
ErrorLogPath  = /var/log/angie/error.log
ConfigDir    = /etc/angie
PIDPath       = /run/angie.pid
ReloadCmd     =  sudo service angie reload
RestartCmd    =  sudo service angie restart

I set it this way but the problem still persists.  I am also using the latest version of nginx UI.

**Comment by 0xJacky** [comment]
Have you restarted the nginx ui service?

**Comment by adammakowskidev** [comment]
Of course. Even the server.  Could you test this on your own server?

**Comment by 0xJacky** [comment]
Did you encounter this issue while attempting to save a configuration?

**Comment by adammakowskidev** [comment]
Yes, always when saving, although the config is created.  Issuing an SSL certificate also does not work.

**Comment by 0xJacky** [comment]
https://github.com/0xJacky/nginx-ui/blob/dev/server/internal/nginx/nginx.go

Oops, I forgot to provide a custom command for config test, it always exec `nginx -t`, I will fix it.

**Comment by 0xJacky** [comment]
> Yes, always when saving, although the config is created. Issuing an SSL certificate also does not work.

Nginx UI will try to save a config automatically when you issuing a ssl certificate, and before save, it will also test the config,. However in your case, test config is not works, so you can't obtain the certification.

**Comment by adammakowskidev** [comment]
Of course I understand all this.  Is there any way to solve this problem now?

**Comment by 0xJacky** [comment]
Download the artifact from this link https://github.com/0xJacky/nginx-ui/actions/runs/6940853036, and replace the nginx-ui in `/usr/local/bin/nginx-ui`.

**Comment by 0xJacky** [comment]
I released a new v2.0.0-beta.4 verison, and this issue should be fixed.

Please set your command for testing configuration in app.ini.
```
[nginx]
TestConfigCmd = 
```

**Comment by adammakowskidev** [comment]
So I need setup

[nginx]
TestConfigCmd =  sudo angie -t

Yes?

**Comment by 0xJacky** [comment]
yes

**Comment by adammakowskidev** [comment]
Thank you Jacky.
I will test it today and let you know if it works.

**Comment by adammakowskidev** [comment]
@0xJacky 
Hi
I'm back with a small problem, I can't run the current version with Angie.
During installation, I get two errors:

```
Nginx.conf includes sites-enabled directory
Check if the nginx.conf includes the sites-enabled directory
Failed to read nginx.conf
```

```
Nginx.conf includes conf.d directory
Check if the nginx.conf includes the conf.d directory
Failed to read nginx.conf
```

My config:
```
[nginx]
AccessLogPath   = /var/log/angie/access.log
ErrorLogPath    = /var/log/angie/error.log
LogDirWhiteList = 
ConfigDir       = /etc/angie
ConfigPath      = /etc/angie.conf
PIDPath         = /run/angie.pid
TestConfigCmd   = sudo angie -t
ReloadCmd       = sudo angie -s reload
RestartCmd      = sudo systemctl restart angie
StubStatusPort  = 0
ContainerName   = 
```

How to change nginx.conf to angie.conf?

**Comment by adammakowskidev** [comment]
oh sory, my mistake... 
`ConfigPath      = /etc/angie/angie.conf`
is correct
