### ISSUE TITLE
Add support to set notifications for renew certs.

### ISSUE THREAD

**Issue by leic4u** [0xJacky/nginx-ui#192]
According to acme.sh repo's wiki of [notify](https://github.com/acmesh-official/acme.sh/wiki/notify), there is a function to send notifications to users, which could notify the status of renewing.

It will be awesome feature to support config it in webUI. 

Please consider it. Thanks for your developing.

**Comment by 0xJacky** [comment]
This feature is nice, I will develop this, and it will be released in next beta verison of v2.0.0

**Comment by leic4u** [comment]
> This feature is nice, I will develop this, and it will be released in next beta verison of v2.0.0

感谢开发者。请问下 2.0 预计啥时候发布测试版呢。

**Comment by 0xJacky** [comment]
> > This feature is nice, I will develop this, and it will be released in next beta verison of v2.0.0这个功能很好，我会开发这个，它将在 v2.0.0 的下一个 beta 版本中发布
> 
> 感谢开发者。请问下 2.0 预计啥时候发布测试版呢。
测试版已经发了，现在在 beta.4 还有些功能没做完，然后最近比较忙，更新的速度会稍慢😂

**Comment by leic4u** [comment]
> > > This feature is nice, I will develop this, and it will be released in next beta verison of v2.0.0这个功能很好，我会开发这个，它将在 v2.0.0 的下一个 beta 版本中发布
> > 
> > 感谢开发者。请问下 2.0 预计啥时候发布测试版呢。
>
> 测试版已经发了，现在在 beta.4 还有些功能没做完，然后最近比较忙，更新的速度会稍慢😂

嗯嗯好的，加油！🫡

顺便问下，你用的啥翻译插件啊？

**Comment by 0xJacky** [comment]
vue3-gettextJackyOn Nov 21, 2023, at 7:20 PM, leic4u ***@***.***> wrote:﻿



This feature is nice, I will develop this, and it will be released in next beta verison of v2.0.0这个功能很好，我会开发这个，它将在 v2.0.0 的下一个 beta 版本中发布

感谢开发者。请问下 2.0 预计啥时候发布测试版呢。

测试版已经发了，现在在 beta.4 还有些功能没做完，然后最近比较忙，更新的速度会稍慢😂

嗯嗯好的，加油！🫡
顺便问下，你用的啥翻译插件啊？
