### ISSUE TITLE
Buttons disappear when a sidebar opened

### ISSUE THREAD

**Issue by leic4u** [0xJacky/nginx-ui#195]
When I open the sidebar of the Monica extension, all elements of the edit page respond correctly except the save and return buttons.

![image](https://github.com/0xJacky/nginx-ui/assets/32786903/c224b60a-f831-447a-a223-7d93982070c9)

**Comment by 0xJacky** [comment]
It seems like a browser issue

**Comment by leic4u** [comment]
> It seems like a browser issue

but the other elements response correctly, except the Save and Back buttons only.

**Comment by 0xJacky** [comment]
Actually, this is not my fault. I use `positon: fixed; bottom: 0; right: 0` to make the FooterToolBar fix in the bottom of the screen. 

The following documentation is about `positon: fixed`, excerpted from https://developer.mozilla.org/en-US/docs/Web/CSS/position
<img width="791" alt="image" src="https://github.com/0xJacky/nginx-ui/assets/13096985/323723b0-3637-4571-a90a-b9713043c24b">

In my opinon, the browser should change the width of viewport to make sure that elements are not covered by the sidebar extensions. 

I also install Monica in Chrome, and it has the same behavior with Edge, it looks like a Chromium issue. Fortunately, I found that using `position: sticky` can also fix the element in the bottom, so I "fix" this issue in 
91817a3.
