### ISSUE TITLE
Add support to view all config files in one file

### ISSUE THREAD

**Issue by leic4u** [0xJacky/nginx-ui#198]
Now I can only view the config files in three different file directories, that's so inconvenient.

Please consider generating all configuration files into one file, to make viewing config simple.

Thanks to developers.

**Comment by 0xJacky** [comment]
Sorry, I have no plan to implement this feture. I think generating all configuration files into one file will make the output of `nginx -t` becomes unclear, plus, it also conflicts with the standard of **Debian web server configuration file.**

From my personal perspective, adding a notification of config inpection in sites list is more graceful.

![image](https://github.com/0xJacky/nginx-ui/assets/13096985/5063f363-eec5-422a-a13c-6547ad97425d)

**Comment by leic4u** [comment]
Good job. that's a nice solution either.
