### ISSUE TITLE
When I enable a incorrect config file Nginx goes wrong without changing the config file status.

### ISSUE THREAD

**Issue by leic4u** [0xJacky/nginx-ui#199]
1. Nginx works correctly.
2. then I enabled a incorrect config file.
3. nginx goes wrong without changing the config file status.
4. the file status won't become disable until I refresh the page.

![image](https://github.com/0xJacky/nginx-ui/assets/32786903/f34e12bb-2a00-4f68-a121-24000b845198)

![image](https://github.com/0xJacky/nginx-ui/assets/32786903/c07be32f-00d7-4912-9ef5-60feaa0ac6d2)

Expected behavior:

The status of config file should be changed immediately after users click the enable or disable button.

**Comment by 0xJacky** [comment]
Fix in 9a4174e, If you try to enable a wrong configuration file, nginxui will prevent you from doing so.
