### ISSUE TITLE
Docker 支持

### ISSUE THREAD

**Issue by cainb** [0xJacky/nginx-ui#20]
如标题所述，未来会考虑支持 Docker 方式部署嘛？

**Comment by 0xJacky** [comment]
嗯 这两天我在玩 unraid nas，准备实现 docker 部署

Jacky

**Comment by cainb** [comment]
> 嗯 这两天我在玩 unraid nas，准备实现 docker 部署 Jacky
> […](#)
> 在 2022年7月21日，上午1:06，cainb ***@***.***> 写道： ﻿ 如标题所述，未来会考虑支持 Docker 方式部署嘛？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

好耶！期待 ♪(^∇^*)

**Comment by 0xJacky** [comment]
我这边在 Unraid NAS 上调试了一下，v1.4.2 已支持 Docker 部署。 目前是把 nginx-ui 和 nginx 打包在同一个镜像里面，以后可能会考虑将它们分开，通过 docker.sock 来控制 nginx 容器的重载。

**Comment by cainb** [comment]
> 我这边在 Unraid NAS 上调试了一下，v1.4.2 已支持 Docker 部署。 目前是把 nginx-ui 和 nginx 打包在同一个镜像里面，以后可能会考虑将它们分开，通过 docker.sock 来控制 nginx 容器的重载。

好耶！但是我觉得并不需要考虑分开吧，统一在一个镜像里简单便携好控制，分开的话其实还要麻烦。

统一在一个镜像里，用户只需要一条命令或者一个 docker-compose.yml 拉取镜像容器就行，分开的话还需要另外再单独安装或拉取一个 Nginx 的 Docker 镜像容器（~

**Comment by 0xJacky** [comment]
嗯

Jacky

**Comment by cainb** [comment]
唔，创建并启动容器时直接使用 '--net=host' 参数, 直接映射本机所有端口怎么样, 毕竟容器内的  Nginx（Nginx UI） 可能会使用任意一个端口, 直接映射本机所有端口还阔以省去频繁的映射端口（~

**Comment by 0xJacky** [comment]
是可以的，不过内部的nginx-ui监听在了9000端口，要避免与宿主机上其他程序的冲突

Jacky

**Comment by cainb** [comment]
> 是可以的，不过内部的nginx-ui监听在了9000端口，要避免与宿主机上其他程序的冲突
> 
> Jacky
> 
> > 在 2022年7月23日，下午2:42，cainb ***@***.***> 写道：
> > 
> > ﻿
> > 唔，创建并启动容器时直接使用 '--net=host' 参数, 直接映射本机所有端口怎么样, 毕竟容器内的 Nginx（Nginx UI） 可能会使用任意一个端口, 直接映射本机所有端口还阔以省去频繁的映射端口（~
> > 
> > —
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> > You are receiving this because you were assigned.
> 

这个一般看了部署文档的都会留意吧，或者还可以给启动时加个自定义参数来让用户自定义修改 Nginx UI 的监听端口（？

> ps：README 里的 Docker 部署介绍里，那条 'docker run' 命令似乎没映射 9000 端口（~

**Comment by 0xJacky** [comment]
噢 有配置文件的，自动安装完成后会自动生成 app.ini，也可以将 app.example.ini 复制一份为 app.ini 修改监听的端口
