### ISSUE TITLE
Nginx logs manual link error

### ISSUE THREAD

**Issue by leic4u** [0xJacky/nginx-ui#201]
![image](https://github.com/0xJacky/nginx-ui/assets/32786903/c020062e-8e8d-4e8e-a50e-018d61509638)

[https://github.com/0xJacky/nginx-ui/wiki/Nginx-Log-Configuration](https://github.com/0xJacky/nginx-ui/wiki/Nginx-Log-Configuration )
The page pointed to by this link  no longer exists.

The right link is the following url:
[https://nginxui.com/zh_CN/guide/config-nginx-log.html](https://nginxui.com/zh_CN/guide/config-nginx-log.html)

Please fix the error url in the Nginx Logs to the correct url, in the situation that users didn't fill the log path in Preference.

**Comment by leic4u** [comment]
@0xJacky The url mentioned in nginx logs(in beta19) not exists anymore. I didn't find the right url.

**Comment by 0xJacky** [comment]
Fixed in 0863143
