### ISSUE TITLE
Add a template which could block access to sites via unconfigured domain names

### ISSUE THREAD

**Issue by leic4u** [0xJacky/nginx-ui#203]
I configured the DNS record with `*.abc.xyz` to my server IP, and I can access nginx-ui via any name with the abc.xyz suffix.

It's not my willing.

Could you please add a template to block it?

just like the following config:
```
    server {
    listen 80 default_server;
    listen [::]:80 default_server;
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    server_name _;
    return 404;
    }
```

Or how about putting it in the nginx.conf?

**Comment by 0xJacky** [comment]
No, template can only use in sites config. I will consider to put these configs in document for starter.

**Comment by leic4u** [comment]
> No, template can only use in sites config. I will consider to put these configs in document for starter.

我的意思就是在站点配置中新加一个模板，类似于我给 nginx-ui 面板配置一个反代一样。我也可以给站点配置一个 404 页面。

现在就是新建一个站点配置就行，但问题是上面的 `listen` `server_name`得自己去手动填，我寻思能不能搞成一个模板？
