### ISSUE TITLE
CPU usage 100% nginx-ui process

### ISSUE THREAD

**Issue by ethaniel86** [0xJacky/nginx-ui#209]
would like to find out why nginx-ui process taking 100% most of the time. Is there logs we can debug? Thanks!
<img width="916" alt="Screenshot 2023-11-28 at 3 11 53 PM" src="https://github.com/0xJacky/nginx-ui/assets/11464581/529628f0-4e55-4c08-8be7-0312176ac1b7">

**Comment by 0xJacky** [comment]
Which version are you using?

**Comment by ethaniel86** [comment]
![Screenshot 2023-11-28 at 4 02 56 PM](https://github.com/0xJacky/nginx-ui/assets/11464581/e9d9f6e9-28c5-49ee-b81f-761aeea44119)
Judging from About page, it's Version: 1.9.9 (110)

**Comment by 0xJacky** [comment]
Did you use the web terminal?

You can use `journalctl -u nginx-ui -n 100` to fetch the latest 100 rows of logs to provide more details for this issue.

**Comment by DenisKevljanin** [comment]
Problem still persists for me. It appears the CPU usage is spiking when you try to check the logs from the webui. Tested with v2.0.0-beta.11

**Comment by DenisKevljanin** [comment]
> Problem still persists for me. It appears the CPU usage is spiking when you try to check the logs from the webui. Tested with v2.0.0-beta.11

Update:  it seems to be fine if I change the access and error log path in the app.ini to a non-existant location.

**Comment by 0xJacky** [comment]
Hi @DenisKevljanin, can you provide us more details about the environment of your server, like os version.

**Comment by DenisKevljanin** [comment]
> Hi @DenisKevljanin, can you provide us more details about the environment of your server, like os version and the size of the logs.

```
Virtualization: kvm
Operating System: Debian GNU/Linux 12 (bookworm)
Kernel: Linux 6.1.0-17-amd64
Architecture: x86-64
Hardware Vendor: QEMU
Hardware Model: Standard PC _Q35 + ICH9, 2009_
Firmware Version: 4.2023.08-3
```

I have it running in the docker-container. As I have not mounted the log directory it is empty with every restart.

**Comment by 0xJacky** [comment]
Hi @DenisKevljanin, try to set the AccessLogPath to /var/log/nginx/access.local.log, and ErrorLogPath to /var/log/nginx/error.local.log, it should not taking 100% CPU in your situation.
