### ISSUE TITLE
Docker 映射静态页面部署文件夹

### ISSUE THREAD

**Issue by cainb** [0xJacky/nginx-ui#21]
Docker 部署时，是不是可以映射出一个特定文件夹来支持静态页面的部署，然后或许还可以在添加站点的界面上提示下路径什么的（~

**Comment by 0xJacky** [comment]
是的 直接映射就行，建议映射到 /var/ww 下面

Jacky

**Comment by cainb** [comment]
> 是的 直接映射就行，建议映射到 /var/ww 下面

好的，我刚刚主要是不知道映射到哪里，有点迷茫，嘿嘿

**Comment by cainb** [comment]
> 是的 直接映射就行，建议映射到 /var/ww 下面

`/var` 文件夹下面似乎没有 www 文件夹斯~

![image](https://user-images.githubusercontent.com/48700331/180641461-9bec3bcf-fb39-40d2-a1d4-0a6e0d3d0420.png)

**Comment by 0xJacky** [comment]
会自动创建的 随便映射到一个目录就行

Jacky

**Comment by cainb** [comment]
> 会自动创建的 随便映射到一个目录就行

喔！好嘞~
