### ISSUE TITLE
终端一直提示 Login incorrect

### ISSUE THREAD

**Issue by cainb** [0xJacky/nginx-ui#22]
刚刚心血来潮想试试 Nginx UI 附带的终端，但是发现用户和密码正确的情况下，一直都是提示 Login incorrect，是因为部署在了 Docker 容器里还是为什么嘞（~

![-1a7a79df2c9885ed.jpg](https://user-images.githubusercontent.com/48700331/180644023-48d58a62-5d57-48a8-884d-569fd5244f6c.jpg)

**Comment by 0xJacky** [comment]
使用 Docker 部署的话，终端只能登录到容器内（因此不推荐使用 Docker部署

对于容器部署，需要先进入容器执行  passwd sshd 设置密码，然后可以用 sshd 账号和设置的密码登录

后续考虑对于容器部署自动登录终端

**Comment by cainb** [comment]
> 使用 Docker 部署的话，终端只能登录到容器内（因此不推荐使用 Docker部署
> 
> 对于容器部署，需要先进入容器执行  passwd sshd 设置密码，然后可以用 sshd 账号和设置的密码登录
> 
> 后续考虑对于容器部署自动登录终端

喔！原来如此（~

**Comment by 0xJacky** [comment]
刚更新的镜像已支持修改 WebShell 启动命令，可以在 app.ini 中增加 `StartCmd=bash` 即可覆盖原有的 login 指令。

**Comment by cainb** [comment]
> 刚更新的镜像已支持修改 WebShell 启动命令，可以在 app.ini 中增加 `StartCmd=bash` 即可覆盖原有的 login 指令。

好耶！我一会回窝了就去试试（~

**Comment by cainb** [comment]
> 刚更新的镜像已支持修改 WebShell 启动命令，可以在 app.ini 中增加 `StartCmd=bash` 即可覆盖原有的 login 指令。

可以啦！太棒啦（~
