### ISSUE TITLE
AccessLogPath not being properly retrieved in pre-release 6

### ISSUE THREAD

**Issue by Buco7854** [0xJacky/nginx-ui#227]
**Describe the bug**
The access log path is not being retrieved correctly, in the last pre-release there was some modification done to get the settings it seems and I think there was a small mistake that were pushed. It seems PIDPath was put instead of AccessLogPath 

https://github.com/0xJacky/nginx-ui/blob/0a4c1cd1acca056ad668989761de586976bf9077/internal/nginx/config_args.go#L78

**To Reproduce**
1. Set AccessLogPath in config
2. Click on access log in the ui

**Expected behavior**
Show access log

**Comment by 0xJacky** [comment]
Thanks
