### ISSUE TITLE
网站管理操作的 ‘启用/禁用’ 按钮点击后不会自动刷新显示

### ISSUE THREAD

**Issue by cainb** [0xJacky/nginx-ui#23]
如标题所示，刚刚发现点击 `启用/禁用` 按钮后，它不会自动刷新显示，需要手动刷新。

比如：点击 `禁用` 后，需要手动刷新页面才会变成显示启用。但是，虽然不刷新页面的话，显示的字不会变，但它的功能是会正常变化的，也就是如下图所示时，我再次点击 `禁用` 按钮，网站会正常启用，反之亦然：

![image](https://user-images.githubusercontent.com/48700331/180652808-f2c66f7e-8111-4d49-bc7b-6cf5dc885844.png)

**Comment by 0xJacky** [comment]
翻译插件的锅，已修复
