### ISSUE TITLE
Reduce the items required to create the Cloudflare DNS credentials

### ISSUE THREAD

**Issue by leic4u** [0xJacky/nginx-ui#231]
According to [acme.sh wiki](https://github.com/acmesh-official/acme.sh/wiki/dnsapi#dns_cf), users could use Cloudflare DNS api by using restrictive API token OR using global API key.

when I use the restrictive API, I just need to provide the `CF_Token` and `CF_Account_Id` to acme.sh.
OR when I use the global API, I just need to provide the `CF_Key` and `CF_Email` to acme.sh.

And nginx-ui requires too much items to be must filled now.

![image](https://github.com/0xJacky/nginx-ui/assets/32786903/e97506d5-50eb-450d-9ec9-8b46fd880bf1)

Please considering reduce the items of Cloudflare DNS credentials.

**Comment by 0xJacky** [comment]
These items are downloaded from https://github.com/go-acme/lego/tree/master/providers/dns, the only thing I can do is to remove all the vaildate rules.

**Comment by leic4u** [comment]
> These items are downloaded from https://github.com/go-acme/lego/tree/master/providers/dns, the only thing I can do is to remove all the vaildate rules.

啊？我一直以为本项目是用的 acme.sh，原来不是吗😂

根据 go-acme/lego 项目的 [wiki 介绍](https://go-acme.github.io/lego/dns/cloudflare/#description)，也不是都必填，我理解也是可以取消必填的。
You may use `CF_API_EMAIL` and `CF_API_KEY` to authenticate, or `CF_DNS_API_TOKEN`, or `CF_DNS_API_TOKEN` and `CF_ZONE_API_TOKEN`.

建议在 DNS 凭证页面上，把这个项目的 wiki 地址放一下，不然可能会有点懵，不知道怎么填。我一直对照着 acme.sh 的 wiki 在看😂

**Comment by 0xJacky** [comment]
应该参考这个 https://go-acme.github.io/lego/dns/

**Comment by 0xJacky** [comment]
但是校验器确实应该去掉

**Comment by leic4u** [comment]
> 应该参考这个 https://go-acme.github.io/lego/dns/

是的，我也是看的这个，从项目主页 readme 跳过去的。

> 但是校验器确实应该去掉

那其他 DNS Provider 是不是也有这个问题，我没一个一个去看，要不全部去掉算了。

顺便问下，当初集成 acme 的时候，为啥选择集成 go-acme 项目，没选择 acme.sh 项目呢，我感觉 acme,sh 的功能挺强大的。

**Comment by 0xJacky** [comment]
两年前确实用的 acme.sh，但是为了适应不同的环境，改用 lego 直接集成进代码，后续会开发自定义 command，届时可以自行安装 acme.sh 并配置自己的命令

**Comment by 0xJacky** [comment]
而且 acme.sh 还带一个 Python，不太优雅

**Comment by leic4u** [comment]
好的，了解了。那我感觉自定义通知这个功能是不是一时半会儿不好实现了，我开始还以为用的 acme.sh，那直接加个配置页面就行了呢，但是这个 go-acme/lego 项目好像没有实现通知的功能。

**Comment by 0xJacky** [comment]
未来可期

**Comment by 0xJacky** [comment]
好了，去掉了
