### ISSUE TITLE
 REST/gRPC API key for user

### ISSUE THREAD

**Issue by alex-ac-ir** [0xJacky/nginx-ui#248]
Frontend is not always a way to manage vhosts in Nginx UI, I have some other projects that it would be nice to integrate with a tool that parse and manage nginx configs and do not write own parsers. 

But for now, even if I'll use a POST request to have auth in NGINX UI and use some requests that are making frontend to backend, I still feeling a luck of quick and easy method to have a list of server_name of all "Sites". To have some, I should iterate all "Sites" to have a server_name for every of them. So please consider, maybe an API could be a nice addition for a project.

**Comment by 0xJacky** [comment]
Hi, you can upgrade to v2.0.0-rc, we add a settings of `NodeSecret` in the server section of app.ini. You can request the backend with the header `X-Node-Secret`, this can also be used to auth in Nginx UI.
