### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by ismael-su** [0xJacky/nginx-ui#252]

**Comment by Hintay** [comment]
Thank you for bringing this to our attention. We take the security of our open-source projects seriously. Nginx-UI is an open-source project, and its code is available for everyone to review. We want to ensure the community's trust and welcome any collaboration to address potential security concerns.

To investigate the issue you've encountered, we need more information. Could you please provide details on the antivirus software that flagged and shut down the VMs? This information will assist us in conducting a thorough review and addressing any potential security issues.

We appreciate your cooperation and look forward to resolving this matter promptly.
