### ISSUE TITLE
Better breadcrumbs to be able to navigate back to lists

### ISSUE THREAD

**Issue by jtrumpio** [0xJacky/nginx-ui#258]
**Describe the solution you'd like**
I'd like for the prior breadcrumb to take you back to the list.  For example when modifying a certificate, there is no way to use the breadcrumbs to navigate back to the list of certificates unless you use the left menu.  I understand this is more or less due to the way the menu is structured.  It would be nice if you could simply click certificates in this breadcrumb to return to the list:

![image](https://github.com/0xJacky/nginx-ui/assets/34916044/d3b45ea6-6bb4-411e-9867-abd8fa644944)

Otherwise I absolutely love this tool, what an awesome job!

Thank you for your consideration!

**Comment by 0xJacky** [comment]
Hi @jtrumpio,
Sorry for the delayed response. I has been focusing on other priorities, which caused the delay in addressing user experience improvements. I’m pleased to inform you that the issue with breadcrumb navigation has been resolved. This enhancement will be included in the next release of Nginx UI.

**Comment by jtrumpio** [comment]
Awesome!  I love this project so much.  Keep up the wonderful work!!!
