### ISSUE TITLE
可否新增选择自动申请ecc证书或rsa证书的选项

### ISSUE THREAD

**Issue by avsba001** [0xJacky/nginx-ui#264]
如上所述，因项目集成度非常高（二进制执行文件和DB数据库），我貌似没有找到能修改类似acme.sh命令的地方。
而ecc证书在兼容性上看貌似还不错（除了WINXP）

**Comment by 0xJacky** [comment]
项目没有用到 acme.sh，用的是 lego。我看好像支持 EC256 和 EC384 https://github.com/go-acme/lego/blob/7fd17042823a3f1f33375db021b343b9d5c347f2/certcrypto/crypto.go#L26

**Comment by avsba001** [comment]
换句话说，除了自己编译，或者是看项目组有没有计划了对吧？

**Comment by 0xJacky** [comment]
精力有限，下个测试版主要修复 bug，如果等不及可以尝试自己编译

**Comment by avsba001** [comment]
感谢解惑

**Comment by 0xJacky** [comment]
已在 v2.0.0-beta.15 中添加这个功能。
