### ISSUE TITLE
Docker 部署错误

### ISSUE THREAD

**Issue by cainb** [0xJacky/nginx-ui#27]
今天拉取了最新的 Docker 镜像构建后，感觉不对劲，于是下午花了点时间搭了个环境手动构建了一遍，发现了两个小问题（？

1. dockerfile 文件里的 `rm -f /etc/nginx/conf.d/default.conf` 命令似乎没有效果，因为 `default.conf` 还是存在且正常映射，导致直接访问 80 端口显示的页面是 nginx 欢迎页，而不是 nginx-ui 后台，需要手动删除然后重启容器；但是这么一来便没有了意义，甚至不如直接开放 9000 端口 (
2. 初次访问的时候，不会自动跳转到 `/install` 页面进行初始化，而是直接跳到了 `/login?next=/dashboard` 进行账号登录（应该是近几天提交里才出现的 bug，因为我另一台机子上的老镜像是没问题的

> ps: docker hub 上的镜像版本除了始终最新的 `latest` ，能否按 Nginx-UI 的版本号进行二次区分，比如：v1.4.2 等等（~

![image](https://user-images.githubusercontent.com/48700331/182840012-8e41c997-80f1-47c8-8c3a-432fc214f921.png)

**Comment by 0xJacky** [comment]
1. 已修复
2. 重构的时候漏写代码了，已补上
3. 后续有计划按版本和通道分 docker 镜像，但目前还处于新版本的开发阶段，等 v1.5.0 正式发布之后会加上
