### ISSUE TITLE
SSL Certificate cannot be imported anymore.

### ISSUE THREAD

**Issue by bitsky6** [0xJacky/nginx-ui#270]
**Describe the bug**

**To Reproduce**
1. Go to 'Certifcates'
2. Click on 'Import'

**Expected behavior**

**Screenshots**
![image](https://github.com/0xJacky/nginx-ui/assets/57507315/531cb2fe-f640-475a-b7f2-0e959fd18d92)
![image](https://github.com/0xJacky/nginx-ui/assets/57507315/e029d4bf-fe32-4695-aa38-e6895690a277)

**Info (please complete the following information):**
 - Server OS: official docker:latest
 - Server Arch: [e.g. x86, aach64]
 - Nginx UI Version: [e.g. 2.0.0-beta13-patch]
 - Your Browser: [Chrome]

**Additional context**
This works ok before version 2.
If I add only key works but cert is not.

**Comment by 0xJacky** [comment]
Thank you for your report, this issue should be resolved in 979347. I will release a new version soon.

**Comment by bitsky6** [comment]
Thanks
