### ISSUE TITLE
Sites-enabled always stays empty all the time

### ISSUE THREAD

**Issue by bitsky6** [0xJacky/nginx-ui#272]
**Describe the bug**

**To Reproduce**
1. Go to 'Manage Config'
2. Click on 'sites-enabled'

**Expected behavior**
It should show the content from the sites-enabled folder if it has been enabled from Manage sites -> sites-list

**Screenshots**
![image](https://github.com/0xJacky/nginx-ui/assets/57507315/51fd384d-3f3a-45a0-a97a-f9a433e10332)
![image](https://github.com/0xJacky/nginx-ui/assets/57507315/5a6e202c-1412-4782-9109-7f7bd8d47300)
![image](https://github.com/0xJacky/nginx-ui/assets/57507315/085e0a5c-19d0-4c1a-ba4e-1950f6b0fd5f)

**Info (please complete the following information):**
 - Server OS: [e.g. Ubuntu 22.04]
 - Server Arch: [e.g. x86, aach64]
 - Nginx UI Version: [e.g. 1.8.0]
 - Your Browser: [e.g. Chrome, Safari, Firefox]

**Additional context**

**Comment by 0xJacky** [comment]
Thank you for your report, this issue should be resolved in abe43c5c4df0d3f2fa8749bb3d640e8fe12ba948. I will release a new version soon.
