### ISSUE TITLE
Unable to create a certificate from a second environment

### ISSUE THREAD

**Issue by mateo08c** [0xJacky/nginx-ui#273]
**Describe the bug**
It is impossible to generate a self-signed certificate from another environment linked to nginx-ui.

**To Reproduce**
1. Go to 'Environment'
2. Click on 'Add.'
3. Add new node
4. Go to 'Dashboard'
5. Click on second 'Environment'
6. Go to 'Certificates'
7. Generate certificate
8. Certificate not generated

**Console log**
```log
2024-02-02 15:47:42	ERROR	certificate/issue.go:60	websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
```

**Expected behavior**
Unable to generate an automatic certificate.

**Screenshots**
![image](https://github.com/0xJacky/nginx-ui/assets/36140949/2940a2bf-c754-493f-9714-3120bf22ede7)
![image](https://github.com/0xJacky/nginx-ui/assets/36140949/026b34f7-d36b-42b0-9936-d2d1b1815379)

**Comment by 0xJacky** [comment]
Thanks for your report, this issue has been resolved in 2526d71c0e4156b01f441aa01b68082ce98721d3, and it will be released with the next beta verison.
