### ISSUE TITLE
Let's Encrypt "Cron" Job does not run reliably

### ISSUE THREAD

**Issue by wsewrftgyhujikolp** [0xJacky/nginx-ui#280]
**Describe the bug**
When `auto_cert -> AutoObtain` runs into a problem, the `gocron` Background task stops and does not run anymore.

**To Reproduce**
1. Have a many certificates, so that the rate limit of let's encrypt is exceeded. (Or have some other problem where let's encrypt certificate validation does not succeed.)
2. Have certificates that are close to expiring
3. Look at the nginx-ui logs, it stopped trying to renew the certificates that need to be renewed.

**Expected behavior**
`gocron` should continue trying to renew all the certificates every 30 minutes, even if last time there was a problem. (See `InitAutoObtainCert`)

**Screenshots**
![image](https://github.com/0xJacky/nginx-ui/assets/153927261/75bdc4cc-8bed-4274-9bdd-0f24e604634d)

**Info (please complete the following information):**
 - Server OS: Ubuntu 22.04
 - Server Arch: aach64
 - Nginx UI Version: 1.9.9 (110)
 - Your Browser: N/A
 
**Additional context**
I don't know golang, or I would make a PR

**Comment by 0xJacky** [comment]
Please upgrade to v2.0.0-beta.x, this bug has been fixed.
