### ISSUE TITLE
Empty Modal After Certificate Generation Failure

### ISSUE THREAD

**Issue by mateo08c** [0xJacky/nginx-ui#281]
**Describe the bug**
If you generate a certificate and it times out, an error will be displayed. When you try to close the page and generate a certificate again, an empty modal will appear. It will also create an empty certificate in the list when the page loads.

(I'm not talking about the error itself but rather the interface's reaction after an error)

**To Reproduce**
1. Go to 'https://xxxx.x/#/certificates/list'
2. Click on 'Issue Wildcard Certificate'
3. Add fake DNS (ex: test.fr)
4. Wait timeout
5. Close the popup
6. Click on 'Issue Wildcard Certificate'
7. See the empty modal

**Screenshots**

https://github.com/0xJacky/nginx-ui/assets/36140949/28b9a206-e465-4e7b-8d58-15c4f13b6297

I waited for 2 minutes for the timeout to occur when I started the video.

**Info:**
 - Server OS: Ubuntu 22.04 
 - Server Arch: amd64
 - Nginx UI Version: 2.0.0-beta.14 (113)
 - Your Browser: Edge
 - Docker: Yes

**Comment by 0xJacky** [comment]
Fixed in 98a6689.
