### ISSUE TITLE
Where can I request Lets Encrypt Cert for my Site?

### ISSUE THREAD

**Issue by rho-kk** [0xJacky/nginx-ui#287]
Hey,

I cant find out where I can get a lets encrypt cert.

Maybe someone can help me.

Best Wishes

**Comment by 0xJacky** [comment]
Hi, you can create a new site via Manage Sites > Add Site or add a new server block to an existing site. Then, add the directives shown in the picture below. Finally, a switcher will appear above the Directives list.

<img width="835" alt="image" src="https://github.com/0xJacky/nginx-ui/assets/13096985/07c49d41-e662-4f20-986f-3eafb908ef29">
