### ISSUE TITLE
能否支持自动续签双SSL证书？

### ISSUE THREAD

**Issue by jearton** [0xJacky/nginx-ui#288]
我想要给一个站点加上 RSA + ECC 双证书，可以支持吗？

**Comment by 0xJacky** [comment]
你可以在 证书管理 中，用 DNS Challenge 的方式签一个 RSA 再签一个 ECC 的泛域名证书，然后修改配置文件

**Comment by jearton** [comment]
@0xJacky 这个方法不行啊，先申请了RSA，再去申请ECC，你的列表里还是一个，ECC把RSA覆盖掉了
