### ISSUE TITLE
文档中的一处错误

### ISSUE THREAD

**Issue by jearton** [0xJacky/nginx-ui#289]
Docker 部署示例的端口映射写反了

![image](https://github.com/0xJacky/nginx-ui/assets/10370433/21932f59-e2ed-4abf-93e3-6f0430da5549)

而且应该是访问：http://<your_server_ip>

**Comment by jearton** [comment]
![image](https://github.com/0xJacky/nginx-ui/assets/10370433/e288e807-ef3c-48c4-acff-6246d99997f2)

**Comment by 0xJacky** [comment]
感谢反馈，有空修复
