### ISSUE TITLE
使用过程中的几个小问题

### ISSUE THREAD

**Issue by suiyueou** [0xJacky/nginx-ui#29]
1. SSL 证书管理功能：上传、删除、快速选择/取消绑定至站点等，有在计划内嘛？
2. 初始安装完成后，可以将 `nginx-ui.conf` 的配置内容添加到 `网站管理/站点列表` 里，以便更加便捷的对 Nginx UI 管理后台进行域名分配等操作嘛？
3. 新版本的 `编辑站点` 界面体验感觉不太好：
    * 点击指令项输入框时，会弹出注释框，但是当焦点完全消失时，注释框不会自动收起
    * 注释框里也有一个 `在下面添加指令` 按钮，是多出来了，还是设计便是如此？
    * `Locations` 下的 `Location` 节点无法直接便捷的进行删除或者添加新节点，需要进入 `高级模式`

4. `nginx/modules` 是个软连接文件（源文件是个目录），在 `配置管理` 界面中是否应该隐藏显示，因为它无法进行编辑和修改操作：
![image](https://user-images.githubusercontent.com/48700331/185109564-f30cab97-b05a-4e68-87bb-a12556e4e3ce.png)

5. 在 `网站管理/添加站点` 界面新增站点时，基本信息填写完毕点击下一步后，SSL 配置页显示不正常，只有一个 `启用 TLS` 开关按钮，没有 `Server 2` 界面，但此时点击这个开关按钮后， `Server 2` 界面就会出现，不过是一片空白，只剩下一个 `下一步` 按钮，并且点击下一步会报错，无法完成：

点击按钮前：

![image](https://user-images.githubusercontent.com/48700331/185110912-8261374c-8b2d-4812-9370-7e13e65da81c.png)

点击按钮后：

![image](https://user-images.githubusercontent.com/48700331/185110964-a9c4e157-40cb-461f-b324-855c6a7ce7cd.png)

此时点击下一步后出现的报错：

![image](https://user-images.githubusercontent.com/48700331/185111058-108c786a-99b0-47b0-af62-2e1eee0fb5ce.png)

虽然报错，但此时，在 `站点列表` 页面可以对其进行修改，但是显示照样不正常，没有 `ssl_certificate` 和 `ssl_certificate_key` 指令项：

![image](https://user-images.githubusercontent.com/48700331/185113690-7ed6d88d-b69f-4710-a92a-bb481906ad4a.png)

**Comment by 0xJacky** [comment]
诶 有试过更新浏览器吗……JackyOn Aug 17, 2022, at 8:29 PM, cainb ***@***.***> wrote:﻿


SSL 证书管理功能：上传、删除、快速选择/取消绑定至站点等，有在计划内嘛？


初始安装完成后，可以将 nginx-ui.conf 的配置内容添加到 网站管理/站点列表 里，以便更加便捷的对 Nginx UI 管理后台进行域名分配等操作嘛？


新版本的 编辑站点 界面体验感觉不太好：

点击指令项输入框时，会弹出注释框，但是当焦点完全消失时，注释框不会自动收起
注释框里也有一个 在下面添加指令 按钮，是多出来了，还是设计便是如此？
Locations 下的 Location 节点无法直接便捷的进行删除或者添加新节点，需要进入 高级模式



nginx/modules 是个软连接文件（源文件是个目录），在 配置管理 界面中是否应该隐藏显示，因为它无法进行编辑和修改操作：



在 网站管理/添加站点 界面新增站点时，基本信息填写完毕点击下一步后，SSL 配置页显示不正常，只有一个 启用 TLS 开关按钮，没有 Server 2 界面，但是点击这个开关按钮后， Server 2 界面就会出现，但是一片空白，只剩下一个 下一步 按钮，并且点击下一步会报错，无法完成：


点击按钮前：

点击按钮后：

此时点击下一步后出现的报错：

虽然报错，但此时，在 站点列表 页面可以对其进行修改，但是显示照样不正常，没有 ssl_certificate 和 ssl_certificate_key 指令项：

**Comment by cainb** [comment]
> 诶 有试过更新浏览器吗…… 我这边无法复现第五点

有的，我这边在 InPrivate 标签页下也是一样的：

![image](https://user-images.githubusercontent.com/48700331/185147620-550472b5-a260-4172-8578-cacb7b3fbd7c.png)

我刚刚特意用我弟的电脑浏览器也试了，一样的错误（~

**Comment by 0xJacky** [comment]
1. 可能下个大版本会加
2. 可以考虑在安装脚本中加入 @Hintay 
3. 添加按钮设计如此，Location 删除漏做了
4. 是的应该隐藏
5. 下个小版本修复

**Comment by 0xJacky** [comment]
行吧 我加个失去焦点的事件

**Comment by 0xJacky** [comment]
v1.5.1 应该修复了上述 bug（3,4,5）希望不要引起更多的bug（逃

**Comment by cainb** [comment]
> v1.5.1 应该修复了上述 bug（3,4,5）希望不要引起更多的bug（逃

一切正常啦！太棒了！

而且新版本的性能比之前高非常多，从页面的首次加载速度就能体验出来（~

**Comment by 0xJacky** [comment]
嗯 打包体积降了一半，缺点是抛弃了iOS13之前的浏览器刚重构完可能有不少 bug，感谢您的反馈第二点如果是指的 docker部署，应该这两天能优化JackyOn Aug 18, 2022, at 12:22 AM, cainb ***@***.***> wrote:﻿

v1.5.1 应该修复了上述 bug（3,4,5）希望不要引起更多的bug（逃

一切正常啦！太棒了！
而且新版本的性能比之前高非常多，从页面的首次加载速度就能体验出来（~

**Comment by 0xJacky** [comment]
第二点想了一下，如果是用 docker 部署，万一不小心把配置文件禁用了，就很麻烦，所以之前就把配置文件丢到了 `conf.d` 里面，这样就不能改动。但现在要做域名的分配的话，还得把它放回 `sites-available` 下面，然后计划是在配置文件的首行加入 `#nginx-ui:force_enabled` 或者是其他注释，这个我再想想

**Comment by cainb** [comment]
> 第二点想了一下，如果是用 docker 部署，万一不小心把配置文件禁用了，就很麻烦，所以之前就把配置文件丢到了 `conf.d` 里面，这样就不能改动。但现在要做域名的分配的话，还得把它放回 `sites-available` 下面，然后计划是在配置文件的首行加入 `#nginx-ui:force_enabled` 或者是其他注释，这个我再想想

嗯，确实是需要强制启用

除了正常的站点配置修改，可以在界面 ui 上将 `禁用/删除` 按钮设置为不可点击（~

**Comment by cainb** [comment]
有什么新的进展了嘛 (〃∇〃)

**Comment by 0xJacky** [comment]
暂时没有，最近比较忙

**Comment by cainb** [comment]
> 暂时没有，最近比较忙

嗯嗯，好哒（~

**Comment by 0xJacky** [comment]
`nginx-ui.conf` 的配置模板块已加入 v1.7 模板库中
