### ISSUE TITLE
使用 Docker 部署时，是否需要将 app.ini 从主机映射到容器中?

### ISSUE THREAD

**Issue by jearton** [0xJacky/nginx-ui#291]
![image](https://github.com/0xJacky/nginx-ui/assets/10370433/dd8c867a-bae3-4371-9115-c4498d611973)

如图，在宿主机上的 /mnt/user/appdata/nginx-ui 目录下是否需要提前放好 app.ini 配置文件？

**Comment by 0xJacky** [comment]
不需要，文档也没说呀

**Comment by jearton** [comment]
> 不需要，文档也没说呀

不对，如果没有 app.ini，会报错

```shell
docker run --rm -e TZ=Asia/Shanghai -p 80:80 -p 443:443 uozi/nginx-ui:latest
``` 

![image](https://github.com/0xJacky/nginx-ui/assets/10370433/47cfad9d-16bb-4a17-b041-920b63c38884)



![image](https://github.com/0xJacky/nginx-ui/assets/10370433/a34b45df-0e74-4c04-b2cf-4ebcb88d9ef5)

**Comment by 0xJacky** [comment]
我重新确认了一下，需要映射目录或者映射数据卷，不能直接启动容器，否则 /etc/nginx-ui 目录为空，无法写入配置文件。
