### ISSUE TITLE
最新版UI所有的下拉列表，都没法修改值

### ISSUE THREAD

**Issue by jearton** [0xJacky/nginx-ui#295]
下拉列表选中一个值后，想修改成另一个值时，不停闪烁，鼠标根本选不中

**Comment by 0xJacky** [comment]
刷新几次，好像是 antdv 的锅

**Comment by jearton** [comment]
> 刷新几次，好像是 antdv 的锅

我正在配置站点，正好在选这个单行指令和多行指令，页面一刷新，所有指令都要重新配，有点坑。等你们修复吧。

![image](https://github.com/0xJacky/nginx-ui/assets/10370433/0456fc55-a489-4ab9-8601-8baa0fb65fc2)

**Comment by 0xJacky** [comment]
相关 issue 和 pr
https://github.com/vueComponent/ant-design-vue/issues/7339

https://github.com/vueComponent/ant-design-vue/pull/7346

**Comment by jearton** [comment]
![image](https://github.com/0xJacky/nginx-ui/assets/10370433/0d23469c-6e12-4ba8-9b4a-46cb68b64861)
