### ISSUE TITLE
docker容器内出现了两个nginx-ui进程

### ISSUE THREAD

**Issue by jearton** [0xJacky/nginx-ui#297]
如图，是否存在问题？

![image](https://github.com/0xJacky/nginx-ui/assets/10370433/3c47bcd6-8a23-4a85-a00a-af8997200e27)

**Comment by 0xJacky** [comment]
有执行了什么前置操作吗，比如在线更新

**Comment by jearton** [comment]
我在线更新了nginx.conf文件。nginx-ui会开9000端口，两个进程不会端口冲突吗？

**Comment by 0xJacky** [comment]
<img width="975" alt="image" src="https://github.com/0xJacky/nginx-ui/assets/13096985/0c7b7610-47ac-40af-ae99-dd99dcb7c6c6">

<img width="850" alt="image" src="https://github.com/0xJacky/nginx-ui/assets/13096985/ec6a2c31-8285-4510-8702-ec8f91be6659">
