### ISSUE TITLE
websocket 的 map 指令不应放在站点里配置

### ISSUE THREAD

**Issue by jearton** [0xJacky/nginx-ui#298]
map 指令只能放在 http 指令块下面，并且多个站点可共享。所以最好直接固定到 nginx.conf 文件里，否则在多个站点配置文件里重复配置的话，nginx 测试会报错的

**Comment by 0xJacky** [comment]
nginx 的版本提供一下

**Comment by jearton** [comment]
抱歉，我记错了，在http块里重复的map指令，不会导致报错
