### ISSUE TITLE
体验后的几个小建议

### ISSUE THREAD

**Issue by suiyueou** [0xJacky/nginx-ui#30]
本来没准备新开 issues 的，但是写着写着发现好像又长了，就新开一个了（~

1. 希望 `站点列表` 里的站点名称可修改，然后再加上一个站点描述：

![image](https://user-images.githubusercontent.com/48700331/185193403-dac6b5ba-a242-4648-bae2-5e63e3b4acd2.png)

2. `Server x` 标签页这里我觉得可以为它增加一个标签设置，比如说：快速注释/启用、删除、自定义标签页名等

![image](https://user-images.githubusercontent.com/48700331/185208153-e7ef366b-9750-4e8c-85db-ba3554ed4341.png)

3. `Location` 指令节点的注释可以像其他指令输入框一样触发焦点时弹出吗？这样子如果没有写注释的话，页面留白不会太大，然后删除按钮我觉得可以放在标题区域，这个 `Location` 标题栏我觉得还可以再来个自定义 Location 名称或者跟第二条类似的设置，而且这个注释框好像没有边框线条：

![image](https://user-images.githubusercontent.com/48700331/185198805-1b9469e1-a95f-440a-bbc4-7fb0d895897a.png)

4. `添加站点` 时的默认 `Locations` 指令，我觉得可以改为当开启 `TLS/SSL` 并且 `用 Let's Encrypt 对网站进行加密` 功能启用时，再附加上，反之，关闭时自动注释或删除掉该条 `Locations` 指令：

![image](https://user-images.githubusercontent.com/48700331/185201596-d87dc2d8-8275-4f11-a8a2-94d6684372ea.png)

5. 如果已添加了自定义的 SSL 证书，此时如果启用 `用 Let's Encrypt 对网站进行加密` 功能时，可以加个二次确认或折叠隐藏吗？防止误点击之类，然后这个证书的 `此前无效` 时间可以改成 `签发时间`：

![image](https://user-images.githubusercontent.com/48700331/185208873-eb261d96-eae9-46fa-821f-414252cfecaf.png)

6. 希望可以在 `站点添加/编辑` 页面功能中，添加一个 `强制 HTTPS/HSTS 访问` 的功能
7. 希望可以在 `站点添加/编辑` 页面功能中，添加一个快速反向代理的功能：简单输入路径和端口，自动插入标准的 `Location` 指令节点
8. 希望可以在 `站点添加/编辑` 页面功能中，添加一个快速启用防盗链的功能，这个似乎还得做个区分，因为普通站点和反向代理站点的防盗链写法还不太一样
9. 唔，最后这个应该算 Bug 吧，如果 `Locations` 功能块下已有 `Location` 指令，那么新增的 `Location` 是可以正常添加和保存的，但是，如果 `Locations` 功能块下的 `Location` 指令在新添加前（上一次保存）就已经删除掉了所有的 `Location`，那么将无法正常添加，具体表现为：点击修改站点 => 删除所有 `Location` 并保存 => 再次点击修改站点 => 点击 `添加 Location` => 输入相关信息 => 点击确认，此时页面无任何反应：

无法添加：

![image](https://user-images.githubusercontent.com/48700331/185206799-a5526029-95ae-4b14-8785-8d94bd43cd38.png)

可正常添加保存：

![image](https://user-images.githubusercontent.com/48700331/185206848-a9ec793c-0485-483a-9481-b4bd5a3c22a5.png)

**Comment by 0xJacky** [comment]
第9点已修复，第3点已优化

**Comment by 0xJacky** [comment]
现已支持在可视化界面拖拽以排序指令和 Locations

**Comment by DjSni** [comment]
I think this fits in here quite well, it would be good if there is a way to copy and or use page configurations as a template.

**Comment by suiyueou** [comment]
> I think this fits in here quite well, it would be good if there is a way to copy and or use page configurations as a template.
> And thanks for the great work.

configurations template? Great idea!
