### ISSUE TITLE
日志查阅

### ISSUE THREAD

**Issue by cainb** [0xJacky/nginx-ui#31]
如标题所述，希望可以为各站点日志和 Nginx 错误日志提供日志查看功能

> ps: 有个小疑问，配置管理界面是否应该增加一个 Nginx 重启/配置重载功能，还是说修改完配置后会自动重启/重载（？

**Comment by 0xJacky** [comment]
修改完会自动重载JackyOn Aug 29, 2022, at 8:11 AM, cainb ***@***.***> wrote:﻿
如标题所述，希望可以为各站点日志和 Nginx 错误日志提供日志查看功能

ps: 有个小疑问，配置管理界面是否应该增加一个 Nginx 重启/配置重载功能，还是说修改完配置后会自动重启/重载（？

**Comment by cainb** [comment]
> 修改完会自动重载

好的，明白啦（~

**Comment by 0xJacky** [comment]
日志功能最近会做

**Comment by 0xJacky** [comment]
已添加
