### ISSUE TITLE
ChatGPT 助手无法读取到 include 文件里的指令

### ISSUE THREAD

**Issue by jearton** [0xJacky/nginx-ui#311]
![image](https://github.com/0xJacky/nginx-ui/assets/10370433/117a8d60-9f1a-45fa-891f-36f620ff6d18)

建议将 include 指令对应的文件里的指令，填充进来后，再去生成提示词。或者针对每一个include文件里的指令，再单独生成问答也可以。

**Comment by 0xJacky** [comment]
有道理

**Comment by 0xJacky** [comment]
已在 642e21a 添加
