### ISSUE TITLE
app.example.ini 添加配置项说明

### ISSUE THREAD

**Issue by suiyueou** [0xJacky/nginx-ui#32]
如标题所述，然后 `RunMode` 配置项除了 debug 外还有别的值嘛

**Comment by 0xJacky** [comment]
gin 的 RunMode 只是为了读取不同的配置，本项目目前没有针对 RunMode 进行优化。

https://github.com/gin-gonic/gin/blob/master/mode.go

**Comment by cainb** [comment]
> gin 的 RunMode 只是为了读取不同的配置，本项目目前没有针对 RunMode 进行优化。
> 
> https://github.com/gin-gonic/gin/blob/master/mode.go

好的（~
