### ISSUE TITLE
签发证书时能否增加DNS记录的检测时间？

### ISSUE THREAD

**Issue by jearton** [0xJacky/nginx-ui#321]
签发证书的成功率有点低，50%都不到，全都是因为DNS记录检测超时导致的。我用的阿里云DNS凭证

**Comment by 0xJacky** [comment]
可以试下配置一下环境变量

<img width="632" alt="image" src="https://github.com/0xJacky/nginx-ui/assets/13096985/968909da-be6f-443f-949f-94bcd2e3bacb">

**Comment by 0xJacky** [comment]
对应 UI 里的几个值，我看 lego 的代码是会读取这个 env 的，这个我没法控制，实在不行建议给宿主机换个 DNS。我 CF 还没遇到失败的.

**Comment by jearton** [comment]
可以，有配置能自己控制时间就行

**Comment by jearton** [comment]
@0xJacky 顺便请教一下，这个证书多久会自动续期？

**Comment by 0xJacky** [comment]
目前是每7天重签，不过看起来在证书多的情况下会有问题 #319

**Comment by jearton** [comment]
感觉有点频繁了，毕竟有3个月有效期呢，在过期前几天签就足够了吧。acme.sh 这个项目里是每2个月自动续签，而且续签万一失败，最好能发个机器人消息通知出来，不然感知不到

**Comment by 0xJacky** [comment]
目前，如果还剩半个月没能正常续签 let's encrypted 会给你发邮件的
