### ISSUE TITLE
Let's encypt certifitactes not working in firefox OCSP fail

### ISSUE THREAD

**Issue by zero8d** [0xJacky/nginx-ui#322]
Let's encypt certifitactes not working in firefox OCSP fail

**Comment by 0xJacky** [comment]
Can you provide more details about this issue, like the configuration file of your site and the reproduce steps of this problem.

**Comment by jearton** [comment]
我也遇到了，在firefox里首次访问会有问题，刷新一下又好了。可以用无痕模式稳定复现，OCSP这里出了问题，不知道怎么解决。

![image](https://github.com/0xJacky/nginx-ui/assets/10370433/915b646f-23bf-4ffa-bd21-d01d652fa805)


Secure Connection Failed

An error occurred during a connection to admin.creatly.team. A required TLS feature is missing.

Error code: MOZILLA_PKIX_ERROR_REQUIRED_TLS_FEATURE_MISSING

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

点一下 try again 就好了

**Comment by jearton** [comment]
![image](https://github.com/0xJacky/nginx-ui/assets/10370433/26623048-3986-47a7-b06d-ec7104fa7ea5)

![image](https://github.com/0xJacky/nginx-ui/assets/10370433/5b88d11f-6707-48e9-a9de-783b3245c4d0)

**Comment by 0xJacky** [comment]
This issue may cause by certificate "must staple", introduced in 1c4fb7afcc6ba2dfc46c31c44f36e1c3b74836b7.

I think I should a switcher in frontend for user to chose whether they need "must staple" or not.

https://community.letsencrypt.org/t/ssl-cert-issue-mozilla-pkix-error/194269

<img width="881" alt="image" src="https://github.com/0xJacky/nginx-ui/assets/13096985/58d67490-c30a-48a4-87dc-3ed93dae633a">

**Comment by jearton** [comment]
我已经被这个问题困扰了很久，貌似无解，期待大神找到解决方法

**Comment by jearton** [comment]
我有几个很挫的解决方案，仅供参考：

在 Nginx 中配置 `ssl_stapling on` 并 reload 后，Nginx 并不会马上获取 OCSP Response，它要等第一个请求过来，再发起异步 OCSP 请求，所以刚开始几个响应，很可能不带 OCSP Stapling。另外，有时候由于 OCSP 域名无法解析，或者服务器无法访问造成 OCSP Response 获取失败，也会导致 OCSP Stapling 无法生效。

### 如何在 Nginx 启动时就进行 OCSP 装订？

#### 相关问答

* How to make OCSP stapling on nginx work：[https://matthiasadler.info/blog/ocsp-stapling-on-nginx-with-comodo-ssl/](https://matthiasadler.info/blog/ocsp-stapling-on-nginx-with-comodo-ssl/)
* Priming the OCSP cache in Nginx：[https://unmitigatedrisk.com/?p=241](https://unmitigatedrisk.com/?p=241)
* [[Can I make Nginx automatically OCSP staple certificates at reload/restart?](https://serverfault.com/questions/806329/can-i-make-nginx-automatically-ocsp-staple-certificates-at-reload-restart)](https://serverfault.com/questions/806329/can-i-make-nginx-automatically-ocsp-staple-certificates-at-reload-restart)

#### 解决方案

两种方案：

1. 在 Nginx 启动后，立刻去访问每个域名，从而能触发 Nginx 去异步请求 OCSP 服务器。
2. 手动获取 OCSP 响应以 DER 编码格式写入到文件里，再使用  'ssl_stapling_file' 指令指向该文件，并定期更新 OCSP 响应。

**Comment by ashkov** [comment]
Please, help, what can I do to request certificate right now without staple, by hands? 

I can setup NGINX, but I must copy cert to MailCow, and It does not support staple at all.
So my problem - I can't use IMAPs right now after update.

> This issue may cause by certificate "must staple", introduced in [1c4fb7a](https://github.com/0xJacky/nginx-ui/commit/1c4fb7afcc6ba2dfc46c31c44f36e1c3b74836b7).
> 
> I think I should a switcher in frontend for user to chose whether they need "must staple" or not.

**Comment by ashkov** [comment]
> Hi @ashkov, I just push a new commit which revert [1c4fb7a](https://github.com/0xJacky/nginx-ui/commit/1c4fb7afcc6ba2dfc46c31c44f36e1c3b74836b7), and please wait for this [action](https://github.com/0xJacky/nginx-ui/actions/runs/8277651913) complete then you can try to reinstall nginx-ui.

I use docker image

**Comment by 0xJacky** [comment]
Try to pull this image: uozi/nginx-ui: v2.0.0-beta.18-patch.1 or uozi/nginx-ui:latest

**Comment by l333l** [comment]
这个我今天也遇到过这个问题，我是通过docker compose部署，下面是我解决办法，
部署前要映射 /var/cache/nginx这个目录
然后就是
sudo touch /var/cache/nginx/ocsp.stapling
创建ocsp.stapling

sudo chown -R nginx:nginx /var/cache/nginx
sudo chmod -R 755 /var/cache/nginx
设置权限 

openssl ocsp -issuer /root/中间证书.pem -cert /root/证书.crt -url http://ocsp.responder.com -respout /var/cache/nginx/ocsp.stapling

-issuer 后面换成域名证书的中间证书的路径(服务器的路径，不是docker里面的)

-cert 后面换成域名证书的路径

/var/cache/nginx/ocsp.stapling 换成服务器实际的路径，就是你部署映射的路径

http://ocsp.responder.com 换成实际的OCSP响应者的URL  

要获取OCSP响应者（Online Certificate Status Protocol）的URL，您可以按照以下步骤进行：

1. **查看证书信息**：打开您的证书，进入“详细信息”或“扩展”部分。
2. **找到“授权信息访问”（Authority Information Access）**：在这里，您会看到OCSP响应者的URL。
 (就是点浏览器那个🔒，然后看自己的证书，每个都点开来看，有看到OCSP url 类似字眼，就是URL了)

改好你的信息，然后运行
```
openssl ocsp -issuer /root/中间证书.pem -cert /root/证书.crt -url http://ocsp.responder.com -respout /var/cache/nginx/ocsp.stapling
```

然后ocsp.stapling 这个大小就会有变化，就成功了，然后再通过按页面按nginx重启或者重置 都成功了 ，就没有报错了 

这是我配置的 我是直接配置在nginx.conf文件里的
# 配置 SSL Stapling
    ssl_stapling on;
    ssl_stapling_verify on;
    ssl_trusted_certificate /etc/nginx/中间证书.pem; 
    ssl_stapling_file /var/cache/nginx/ocsp.stapling;
