### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by moskvat2** [0xJacky/nginx-ui#323]
**Describe the bug**
I'm creating a new container with nginx-ui, it doesn't complete the deployment, frozen.

**To Reproduce**
1. Go to 'start ssh in linux server and paste de command
   docker run -dit   --name=nginx-ui   --restart=always   -e TZ=America/Sao_Paulo   -v /mnt/nginx-ui/nginx:/etc/nginx   -v /mnt/nginx-ui/nginx-ui:/etc/nginx-ui   -v /mnt/nginx-ui/www:/var/www   -p 80:80 -p 8443:443 -p 81:9000 uozi/nginx-ui:latest'
3. Click on ' portainer -> container (nginx-ui) -> logs'
4. Scroll down to 'end to line'
5. [GIN-debug] GET    /api/availability_test    --> github.com/0xJacky/Nginx-UI/api/upstream.AvailabilityTest (7 handlers)

**Expected behavior**

**Screenshots**
![image](https://github.com/0xJacky/nginx-ui/assets/88354800/361f5e4a-32e9-4a2e-96f3-97dbd4814b57)

**Info (please complete the following information):**
 - Server OS: [e.g. CentOS 7]
 - Server Arch: [amd64]
 - Nginx UI Version: [latest]
 - Your Browser: [Firefox]

**Additional context**
I open url https://github.com/0xJacky/Nginx-UI/api/upstream.AvailabilityTest
in browser, but return the message (Not Found), nginx-ui frozen here

**Comment by 0xJacky** [comment]
Hi @moskvat2, `github.com/0xJacky/Nginx-UI/api/upstream.AvailabilityTest`  is not a url, it is the final handler path of api `/api/availability_test`.

The nginx ui in your os is working normally, you should visit the `ip:80` of your server in broswer, then you can configurate the basic settings of nginx ui.

**Comment by moskvat2** [comment]
Yes, you were right, the problem was in the docker socket, it worked after the systemctl restart docker.socket command. Thanks!
