### ISSUE TITLE
When Importing certificate it is not possible to use a PKCS8 format private key.

### ISSUE THREAD

**Issue by GunnarHentze2Trace** [0xJacky/nginx-ui#326]
**Private key validation fails when using PKCS8 format**
When importing a certificate it is not possible to use a PKCS8 format private key.

**To Reproduce**
1. Go to 'Certificates' -> Certificates List
2. Click on 'Import'
3. Enter path to PKCS8 format private key.
4. See error 'The path exists, but the file is not a private key'

**Expected behavior**
That it validates PKCS8 private keys

**Info (please complete the following information):**
 - Server OS: Ubuntu 22.04
 - Server Arch: x86_64
 - Nginx UI Version: 2.0.0-beta.18 (120)
 - Your Browser: FireFox
 

**Additional context**
The workaround is to convert the key using this openssl command: 
`openssl rsa -in server.key -out server_new.key -traditional`

**Comment by GunnarHentze2Trace** [comment]
I'm no go programmer, but it seems to me that it can be fixed by adding an extra validation check using `x509.ParsePKCS8PrivateKey()` in `func IsPrivateKey(pemStr string)` in the [helper.go](https://github.com/0xJacky/nginx-ui/blob/dev/internal/cert/helper.go) file

**Comment by 0xJacky** [comment]
Thanks for your report, this issue has been fixed in 979a1d5.

**Comment by 0xJacky** [comment]
Please reinstall nginx ui v2.0.0-beta.18 (https://github.com/0xJacky/nginx-ui/releases/tag/v2.0.0-beta.18-patch.2)
