### ISSUE TITLE
Add support for PHP-FPM

### ISSUE THREAD

**Issue by ivmm** [0xJacky/nginx-ui#33]
With the addition of PHP-FPM support, nginx-ui is basically a simple web control panel.

Users can quickly add a dynamic website.

**Comment by hale177** [comment]
不建议，添加动态后端功能显得太重了，那是否后面还要支持 python ，nodejs   。。。 保持简洁，目前作为一个nginx 负载均衡入口很棒了 。

**Comment by 0xJacky** [comment]
明年年初应该会开发一个模版库的功能，到时候应该能满足这些需求
