### ISSUE TITLE
按照提供的docker部署实例无法部署

### ISSUE THREAD

**Issue by Donleo-feng** [0xJacky/nginx-ui#333]
按照md上的模板直接运行中提示失败，修改之后还是报错。
![image](https://github.com/0xJacky/nginx-ui/assets/31247360/7fb72312-b5d5-4644-a19e-bb5210ab4915)

```
docker run -dit \
  --name=nginx-ui \
  --restart=always \
  -e TZ=Asia/Shanghai \
  -v /opt/docker/nginx:/mnt/user/appdata/nginx \
  -v /opt/docker/nginx-ui:/mnt/user/appdata/nginx-ui \
  -p 8080:80 \
  -p 8443:443 \
  uozi/nginx-ui:latest
```
![image](https://github.com/0xJacky/nginx-ui/assets/31247360/9c9e4747-1d56-46e2-ae8e-ffa0aefc45c7)

**Comment by 0xJacky** [comment]
你写错了

-v /mnt/user/appdata/nginx:/etc/nginx \
  -v /mnt/user/appdata/nginx-ui:/etc/nginx-ui \
  
 前面一个目录是本机的目录，后面的目录是容器内的目录，不可以修改的。
