### ISSUE TITLE
某台机器上的 Nginx-UI 无法被其他机器上的容器访问到

### ISSUE THREAD

**Issue by leic4u** [0xJacky/nginx-ui#334]
现在有三台机器，一台叫 arm，一台叫 nas，一台叫 s4。
arm 和 s4 上我都通过 docker 部署了 Nginx-UI。

现在的问题是：

arm 和 nas 宿主机都可以直接 curl 通 s4 机器上的 Nginx-UI 的服务端口，但进入其他容器后就不行了。

![image](https://github.com/0xJacky/nginx-ui/assets/32786903/9a8fc2bf-8a11-4f11-bf0c-828dd5db2442)

但 arm 上的 Nginx-UI 容器里面，可以 curl 通 s4 机器上的 Nginx-UI 的服务端口，只有这一个容器可以。

![image](https://github.com/0xJacky/nginx-ui/assets/32786903/e0748565-f4c6-405e-8884-3d643e65ede6)

而且很奇怪的是其他机器（比如 arm）上的 Nginx-UI 都是 OK 的，只有 s4 机器上的 Nginx-UI 有问题。

![image](https://github.com/0xJacky/nginx-ui/assets/32786903/b089c624-18a0-49fb-bc28-1870bacdfa56)

**Comment by 0xJacky** [comment]
可以检查一下容器的 dns

**Comment by leic4u** [comment]
但是我在容器里面是可以访问 s4.xxx.org:5010 这个服务的，应该不是 dns 的问题吧？

**Comment by 0xJacky** [comment]
那s4本机内的容器能curl通吗

**Comment by leic4u** [comment]
刚装了个容器试了下，s4 机器上的非 Nginx-UI 容器，跟 arm 和 nas 上的非 Nginx-UI 容器表现是一样的。

能 curl 通非 Nginx-UI 的监听端口，Nginx-UI 监听的端口（80 443 9000）curl 不通。

![image](https://github.com/0xJacky/nginx-ui/assets/32786903/7598099c-de09-4a68-bea6-66bfc9b83058)

**Comment by 0xJacky** [comment]
s4本机直接curl呢，用127.0.0.1JackyOn Mar 24, 2024, at 10:16 AM, leic4u ***@***.***> wrote:﻿
刚装了个容器试了下，s4 机器上的非 Nginx-UI 容器，跟 arm 和 nas 上的非 Nginx-UI 容器表现是一样的。
能 curl 通非 Nginx-UI 的监听端口，Nginx-UI 监听的端口（80 443 9000）curl 不通。
image.png (view on web)

**Comment by leic4u** [comment]
> s4本机直接curl呢，用127.0.0.1JackyOn Mar 24, 2024, at 10:16 AM, leic4u ***@***.***> wrote:﻿ 刚装了个容器试了下，s4 机器上的非 Nginx-UI 容器，跟 arm 和 nas 上的非 Nginx-UI 容器表现是一样的。 能 curl 通非 Nginx-UI 的监听端口，Nginx-UI 监听的端口（80 443 9000）curl 不通。 image.png (view on web) —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

是可以的，80 443 9000 在 arm nas s4 的本机上都能 curl 通。
![image](https://github.com/0xJacky/nginx-ui/assets/32786903/39e487ee-6b73-45e5-ac8a-40cfe27c62d0)

**Comment by 0xJacky** [comment]
可以检查一下本机的防火墙设置

**Comment by leic4u** [comment]
刚试了下，如果容器使用 `network_mode: host` 的情况下，容器也可以访问 Nginx-UI 的监听端口了。

![image](https://github.com/0xJacky/nginx-ui/assets/32786903/98d41df3-4c14-4da6-bc32-b946388b27ed)

**Comment by 0xJacky** [comment]
嗯
