### ISSUE TITLE
Add links to the DNS Credentials page to the associated go-acme docs?

### ISSUE THREAD

**Issue by anonhostpi** [0xJacky/nginx-ui#336]
**Is your feature request related to a problem? Please describe.**
The tips on the DNS credentials page are somewhat vague. A few of them don't tell you where to find/how to validate their values. A simple fix for this would be to add a help link on each of the pages to the associated LeGo (go-acme) doc for those credentials.

**Describe the solution you'd like**
A simple link to the associated go-acme doc would be sufficient:

![image](https://github.com/0xJacky/nginx-ui/assets/130698314/2ff5404c-b57d-430e-9207-1bef40978d56)

**Describe alternatives you've considered**
Adding a link to go-acme docs in the README would also do nicely

**Additional context**
go-acme docs: https://go-acme.github.io/lego/dns/cloudflare/

**Comment by anonhostpi** [comment]
I'm assuming I'll see a release for this once #361 is merged?

**Comment by 0xJacky** [comment]
Yes, it will be one of the features of v2.0.0-beta.19.

**Comment by anonhostpi** [comment]
Thank you!
