### ISSUE TITLE
有考虑过兼容Windows吗？

### ISSUE THREAD

**Issue by 2366567504** [0xJacky/nginx-ui#337]
有考虑过兼容Windows吗？我在发布包里面没看到有Windows的版本

**Comment by lianzuo123** [comment]
同问~~老的服务在Windows上~

**Comment by 0xJacky** [comment]
古早版本是可以在 Windows 上跑的，后来引入了一些包可能是只能在 Linux 或者 macOS 下跑的，具体记不清了。如果有需要需求的话，可以考虑自己开 CGO 在 Windows 上编译，遇到不兼容的问题可以再提 issue。

因为我这边基本没有 Windows 开发环境或者生产环境，所以没有发布 Windows 版本 nginx ui 的计划，感谢您的建议，也欢迎大佬为本项目提 pr~
