### ISSUE TITLE
A Start for Integration with OAuth2-Proxy

### ISSUE THREAD

**Issue by anonhostpi** [0xJacky/nginx-ui#340]
**Is your feature request related to a problem? Please describe.**
Another popular reverse proxy, that is typically used in tandem with Nginx/Traefik is OAuth2-Proxy. OAuth2-Proxy provides OAuth and OIDC authentication for web services that don't come with it. One thing it lacks is a UI for configuration.

**Describe the solution you'd like**
I think this is another place where Nginx-UI could shine over NPM.

Since OAuth2-Proxy can also be configured with a config file, I imagine that the same methods for configuring the nginx configs could be used to configure OAuth2's config file:
- see: https://oauth2-proxy.github.io/oauth2-proxy/configuration/overview/

It is important to note that there isn't a default location for this file, so it may have to be user-specified.

I believe that OAuth2 uses go viper for configuration, but I think it limits the valid formats to mainly toml, but also yaml. Since these are serialization formats, you may be restricted to just providing edit access via the editor, unless you can come up with some GUI method for serialization formats (JSON, TOML, YAML, etc)

**Describe alternatives you've considered**
Editing the config file with nano over ssh

**Additional context**
I say that this is a start, because OAuth2-Proxy is also written in Go, so it might be possible for a more direct integration.

**Comment by 0xJacky** [comment]
Although Nginx UI is not limited to use with Nginx, we are unable to optimize it for other branches of Nginx or reverse proxy due to limited energy, so we cannot guarantee its compatibility.

We welcome anyone to fork this project and adapt it specifically for other reverse proxies.

Thanks for your suggestion.
