### ISSUE TITLE
Authorization failed when link start to a wrong environment

### ISSUE THREAD

**Issue by leic4u** [0xJacky/nginx-ui#342]
**Describe the bug**
There are 3 Nginx-UI on 3 VPS. we could call them S1, S2, S3.

S3 was linked to the others.
A few days ago, the domain of S1 was expired, then I changed the DNS of S1.
Today I logged in Nginx-UI on S3, and found that S1 was disconnected, then I clicked the LINK START button, and I was be forced logout from Nginx-ui on S3.
Just like this: (and I lose the Nginx-UI on S1 after I click the button) 
![image](https://github.com/0xJacky/nginx-ui/assets/32786903/3266600a-062b-4712-b996-1fc7f4908919)

When I want to login, the Nginx-UI tells me _Authorization failed_.
![image](https://github.com/0xJacky/nginx-ui/assets/32786903/bd77d26e-d359-463b-999e-5a4efb5efdc1)

**To Reproduce**
1. Add a wrong url item in Environment.
2. Click on 'Link Start'.
3. You will be forced logout.
4. Login.
5. See error.

**Expected behavior**
Login correctly.

**Info (please complete the following information):**
 - Server OS:  Ubuntu 22.04
 - Server Arch:  x86(S1) and aach64(S3)
 - Nginx UI Version: 2.0.0-beta.18 (122)
 - Your Browser: Chrome

**Comment by nianzecong** [comment]
same issue

**Comment by 0xJacky** [comment]
I am sorry that I can't reproduce this issue. First I login in into S1 and click link start to S2, then I stop the nginx-ui on S2. I can logout and login again.

By the way, we did not proxy the login request to the target server you linked to.

**Comment by leic4u** [comment]
> I am sorry that I can't reproduce this issue. First I login in into S1 and click link start to S2, then I stop the nginx-ui on S2. I can logout and login again.
> 
> By the way, we did not proxy the login request to the target server you linked to.

Try to fill in a wrong url to click the Link Start?

**Comment by 0xJacky** [comment]
Still can not reproduce.

**Comment by leic4u** [comment]
I could reporduce this issue everytime...

The simplest way is to delete one letter from Node Secret of S2, making the enviroment wrong.

![image](https://github.com/0xJacky/nginx-ui/assets/32786903/1eb36d1b-6dbf-4a7f-a6c2-bbda7753f6c6)

I test it in the latest version of Chrome. And I can solve this issue by using the method @nianzecong  provided in https://github.com/0xJacky/nginx-ui/issues/342#issuecomment-2051097567 .
