### ISSUE TITLE
Add a setting for renewal interval

### ISSUE THREAD

**Issue by mattiapv** [0xJacky/nginx-ui#343]
Hello, is there a specific reason for setting the default renew interval to 7 days? 

https://github.com/0xJacky/nginx-ui/blob/4289d555629524b62d9da3d1b3b638727e19ab13/internal/cert/auto_cert.go#L63

Since a certificate is valid for 90 days, I would prefer to have a setting to increase the renew interval. For example:

```ini
[server]
RenewalInterval = 60
```

```go
if time.Now().Sub(cert.NotBefore).Hours()/24 < settings.ServerSettings.RenewalInterval {
```

Thank you

**Comment by Condorello** [comment]
Hi, seems that the GUI is limited to 21 days max, could be elevated at 60 days as suggest by lets encrypt?
