### ISSUE TITLE
双重验证 2FAS

### ISSUE THREAD

**Issue by zuilintan** [0xJacky/nginx-ui#344]
RT，
最近经常能发现陌生IP的登录请求，建议添加2FAS增强安全性

**Comment by jearton** [comment]
把公网上的nginx-ui实例，通过agent key的方式加入到内网nginx-ui实例里，就安全了

**Comment by zuilintan** [comment]
> 把公网上的nginx-ui实例，通过agent key的方式加入到内网nginx-ui实例里，就安全了

如果它为你工作，可以提供具体步骤？
