### ISSUE TITLE
open : no such file or directory

### ISSUE THREAD

**Issue by zqq-nuli** [0xJacky/nginx-ui#346]
我通過 root權限 在我的 ubuntu 20.24 的服務器上通過一鍵安裝命令安裝后 
使用過程中遇到了大量的 open : no such file or directory

**Comment by solywsh** [comment]
我也遇到了,不过排查原因是因为80端口被其他服务占用，导致nginx没有正常启动。还有就是app.ini配置里边的nginx相关配置都为空，手动填入配置并关闭占用端口的服务就好了。

**Comment by liujmpo** [comment]
> 我也遇到了，不过排查原因是因为80端口被其他服务占用，导致nginx无法正常启动。还有就是app.ini配置里边的nginx相关配置都为空，手动填入配置并关闭占用端口的服务就好的。

请问需要添加那些配置文件

**Comment by 0xJacky** [comment]
可以把日志post上来吗 感谢

**Comment by liujmpo** [comment]
抱歉，我找不到日志，但是app.pin里配置文件是这个样子
![Uploading 截图 - 2024-4-6 7.58.3.png…]()

**Comment by liujmpo** [comment]
![截图 - 2024-4-6 7 58 3](https://github.com/0xJacky/nginx-ui/assets/48621868/7576c725-511f-40dd-b632-10933782f75a)
抱歉，我是个新手，找不到日志，我的app.ini配置是这个样子

**Comment by liujmpo** [comment]
> 可以把日志贴上来吗 谢谢

我是通过一键脚本安装的

**Comment by liujmpo** [comment]
> 可以把日志post上来吗 感谢

![截图 - 2024-4-6 8 1 58](https://github.com/0xJacky/nginx-ui/assets/48621868/b221cf45-4e5d-441e-9078-9d635a93aa17)

**Comment by liujmpo** [comment]
> 可以把日志post上来吗 感谢

![截图 - 2024-4-6 8 49 44](https://github.com/0xJacky/nginx-ui/assets/48621868/d63674dd-1d84-41e0-bef5-9c34d0745d96)
事实上他并没有自动识别，需要手动添加，手动添加后就可以了

**Comment by 0xJacky** [comment]
这个问题，我在文档里有提到 需要手动创建 sites-available 和 sites-enabled，并且需要在 nginx.conf 中 include

具体请参考

https://nginxui.com/zh_CN/guide/getting-started.html#%E4%BD%BF%E7%94%A8%E5%89%8D%E6%B3%A8%E6%84%8F

**Comment by 0xJacky** [comment]
@liujmpo 我删掉了你的评论，因为你的评论中含有敏感密钥，别人可以通过这个 NodeSecret 直接登录

**Comment by liujmpo** [comment]
> @liujmpo 我删掉了你的评论，因为你的评论中含有敏感密钥，别人可以通过这个 NodeSecret 直接登录

好的，非常感谢

**Comment by sonicno1** [comment]
include vhost/*.conf;

**Comment by 0xJacky** [comment]
> include vhost/*.conf;

Please refer to this documentation for more detail: https://nginxui.com/guide/getting-started.html#before-use
