### ISSUE TITLE
improve ssl management

### ISSUE THREAD

**Issue by ethaniel86** [0xJacky/nginx-ui#351]
Currently SSL management is a hassle feel like this feature is incomplete and confusing. 

Desired solution
1. A way to generate wildcard SSL from SSL page
2. Manual trigger SSL renewal when certificate expired on SSL page or Domain Configuration page

**Comment by 0xJacky** [comment]
Hi, have you try the latest version? Generate wildcard ssl feature and manual trigger ssl renewal are already implemented.

**Comment by ethaniel86** [comment]
you mean 2.0 beta?

**Comment by 0xJacky** [comment]
yes

**Comment by ethaniel86** [comment]
Yes wildcard works in 2.0 beta. How do I know the cert will auto-renew? From the ui i don't see this. 
Found a few bugs will submit through Bug Report.

**Comment by 4NE3Q** [comment]
I'm using cloudflare api token and it adds the dns records I can see but is just unable to complete the challenge. Any help will be appreciated, I can use it manually though not sure what am I doing wrong.
