### ISSUE TITLE
希望新增多日志查看

### ISSUE THREAD

**Issue by oneisall8955** [0xJacky/nginx-ui#356]
习惯每个site（每个域名）的日志独立，例如，foo.example.com与bar.example.com的日志分别为
/var/log/nginx/foo.access.log
/var/log/nginx/foo.error.log

/var/log/nginx/bar.access.log
/var/log/nginx/bar.access.log

但是当前只能查看/var/log/nginx/access.log和/var/log/nginx/error.log

**Comment by 0xJacky** [comment]
是这样的，当你在 server 块中配置了 access_log 或者 error_log 的时候，前端会出现日志按钮

**Comment by 0xJacky** [comment]
<img width="348" alt="image" src="https://github.com/0xJacky/nginx-ui/assets/13096985/15f7f0ea-273a-4649-84d2-571fad61fc51">

**Comment by oneisall8955** [comment]
谢谢解答，很抱歉，我之前只一直用高级模式，没注意到这里。
另外，如果在访问日志，错误日志中选取是否会更好点？

如下图中这里红色框的位置，添加上选取access_log,error_log指令的server
![image](https://github.com/0xJacky/nginx-ui/assets/44989283/d92617be-0f61-436c-be99-3a4c4116e042)

**Comment by 0xJacky** [comment]
这个可能要以后看看了，因为现在没有存储解析后的配置文件，所以目前这个版本是加不了的
