### ISSUE TITLE
主节点上的证书能否支持同步到多个实例上复用?

### ISSUE THREAD

**Issue by jearton** [0xJacky/nginx-ui#363]
我通过agent key集中管理了多个 nginx-ui 实例，有一些证书在多个实例中都要用到，这些证书能否支持只在主节点上生成一次，然后通过agent的api同步到其他实例中去呢？

**Comment by 0xJacky** [comment]
这个不错

**Comment by jearton** [comment]
期待实现，这样就省得我同一个域名在多个节点里去重复签发证书了

**Comment by jearton** [comment]
非常需要这个，希望提高优先级

**Comment by 0xJacky** [comment]
这个功能已发布，如果使用 docker 请用 v2.0.0-beta.25-patch.1 这个 tag 的镜像
