### ISSUE TITLE
Problem While running in docker all other domains redirect to same nginx ui 

### ISSUE THREAD

**Issue by Jagatpratap** [0xJacky/nginx-ui#367]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
 - Server OS: [e.g. Ubuntu 22.04]
 - Server Arch: [e.g. x86, aach64]
 - Nginx UI Version: [e.g. 1.8.0]
 - Your Browser: [e.g. Chrome, Safari, Firefox]

**Additional context**

**Comment by 0xJacky** [comment]
Have you pass the $Host header to the nginx in nginx-ui docker?

**Comment by Jagatpratap** [comment]
Solved.
