### ISSUE TITLE
Impossible to get Let's Encrypt certificate http/dns : error error read certificate: open : no such file or directory

### ISSUE THREAD

**Issue by PastaGringo** [0xJacky/nginx-ui#368]
**Describe the bug**
I just installed nginx-ui with docker.
I want to create my first reverse proxy for nginx-ui (nui.domain.tld -> IP:80) but I can't get a valid ssl Let's Encrypt certificate.
domain.tld is my domain where I set DNS A records (domain + *.domain) pointing to my external VPS IP address.

**To Reproduce**

- Manages Sites > Add Site:
Configuration name: basic
Listen: 80
server_name: nui.domain.tld

- Next
Enable TLS ✅
Do you want to enable TLS popup: OK
Encrypt website with Let's Encrypt ✅
Challenge method: HTT01
Key Tape: RSA2048
ACME user: System Initial User (already setup my Let's Encrypt account)

- Next

The popup opens and nothing happen after `Getting the certificate, please wait...`

**Expected behavior**
The TLS certificate is generated from Let's Encrypt and set to server nui.domain.tld.

**Screenshots**
<img width="628" alt="Capture d’écran 2024-05-02 à 14 23 23" src="https://github.com/0xJacky/nginx-ui/assets/16828964/87c40827-df2a-4cfb-a6f8-0a65969d6381">

**Info (please complete the following information):**
 - Server OS: Ubuntu 22.04.3 LTS
 - Server Arch: x64
 - Nginx UI Version: 2.0.0-beta.20 (129)
 - Your Browser: Chrome
 - Docker: 26.1.1
 - Docker compose: 2.27.0

**Additional context**
Logs from `docker logs -f nginx-ui`:

```
2024/05/02 14:23:18 /home/runner/work/nginx-ui/nginx-ui/model/cert.go:57
[5.409ms] [rows:1] INSERT INTO `certs` (`created_at`,`updated_at`,`deleted_at`,`name`,`domains`,`filename`,`ssl_certificate_path`,`ssl_certificate_key_path`,`auto_cert`,`challenge_method`,`dns_credential_id`,`acme_user_id`,`key_type`,`log`,`resource`) VALUES ("2024-05-02 14:23:18.298","2024-05-02 14:23:18.298",NULL,"basic",NULL,"basic","","",0,"",0,0,"2048","",NULL) RETURNING `id`
2024-05-02 14:23:18     ERROR   certificate/issue.go:88 get certificate info error error read certificate: open : no such file or directory
[GIN] 2024/05/02 - 14:23:18 | 200 |   58.009098ms |   92.184.107.24 | GET      "/api/domain/basic/cert?token=MyToken==/"
```

docker-compose.yml:

```
  nginx-ui:
    stdin_open: true
    tty: true
    container_name: nginx-ui
    restart: always
    environment:
      - TZ=Europe/Paris
    volumes:
      - './nginx-ui/nginx:/etc/nginx'
      - './nginx-ui/nginx-ui:/etc/nginx-ui'
      - '/var/www:/var/www'
    ports:
      - 80:80
      - 443:443
    image: 'uozi/nginx-ui:latest'
```

**Comment by 0xJacky** [comment]
Sorry, I'll fix it later.

**Comment by 0xJacky** [comment]
Please try v2.0.0-beta.21, it should be fixed now.
