### ISSUE TITLE
Missing /etc/nginx/ssl

### ISSUE THREAD

**Issue by Tom60chat** [0xJacky/nginx-ui#37]
Simple issue:
On my ubuntu, the ssl folder in /etc/nginx/ does not exist, when I was using the let's encrypt auto certificate.

The easy way to fix it is just to make sure the ssl folder in /etc/nginx/ is created.

` sudo mkdir /etc/nginx/ssl`

**Comment by 0xJacky** [comment]
Fixed in https://github.com/0xJacky/nginx-ui/commit/c4f87fb4cc49344aec657ff6b3c1ab49a940d170
