### ISSUE TITLE
[error] /var/log/nginx/access.log

### ISSUE THREAD

**Issue by manustars** [0xJacky/nginx-ui#371]
I have a new installation via docker-compose and I get that error, the suggested link gives me 404. in the paths set on compose there is no log folder.

**Comment by 0xJacky** [comment]
https://nginxui.com/guide/config-nginx.html

**Comment by manustars** [comment]
> Can you provide the content of docker-compose.yaml, thanks.

version: '3.3'
services:
    nginx-ui:
        stdin_open: true
        tty: true
        container_name: nginx-ui
        restart: always
        environment:
            - TZ=Europe/Rome
        volumes:
            - '/home/manuel/NGINX/NGINX:/etc/nginx'
            - '/home/manuel/NGINX/NGINX-UI:/etc/nginx-ui'
            - '/var/www:/var/www'
        ports:
            - 8080:80
            - 8443:443
        image: 'uozi/nginx-ui:latest'

**Comment by 0xJacky** [comment]
Hi @manustars, please manually fill the Nginx settings with the values below, and then you can use the log viewer.
<img width="957" alt="image" src="https://github.com/0xJacky/nginx-ui/assets/13096985/248a256b-712d-43ac-b26d-3c39fe2023d5">

I will fix this problem later, thanks you for your report.

**Comment by 0xJacky** [comment]
AccessLogPath = /var/log/nginx/access.local.log
ErrorLogPath = /var/log/nginx/error.local.log
