### ISSUE TITLE
开启ShellCrash代理后，证书->证书列表->签发通配符证书 失败

### ISSUE THREAD

**Issue by gfgjs** [0xJacky/nginx-ui#372]
### 环境：
1. windows虚拟机->pve->lxc
2. 物理机->pve->lxc
### 操作：
**路由器** **开启** **ShellCrash** **代理**后，
通过：nginxui 证书->证书列表->签发通配符证书 **失败**
不进行任何其他修改，**仅关闭**ShellCrash代理，
再次签发通配符证书 **成功**
（以上步骤尝试过多次）

附上失败和成功的日志
[签发通配符证书 日志.txt](https://github.com/0xJacky/nginx-ui/files/15199491/default.txt)

**我注意到日志中，acme使用了nameserver的53端口，不知是否有关**

**Comment by 0xJacky** [comment]
是本地 DNS 服务器的问题，ShellCrash的dns有缓存吧

**Comment by 0xJacky** [comment]
我看了日志，

Checking DNS record propagation. [nameservers=192.168.128.2:53]，用的这个 DNS 服务器，lego 会等待 1 分钟，间隔 2s 检查 DNS 的改动是否传播到你的 DNS 服务器，如果是 ShellCrash 这一类会缓存 DNS 结果的，可能就会出问题，这个可以看看能否关闭 ShellCrash 的 DNS 缓存。

<img width="551" alt="image" src="https://github.com/0xJacky/nginx-ui/assets/13096985/066477e6-27ea-471f-9405-0338bd6b162a">

**Comment by 0xJacky** [comment]
不过这个问题应该有办法，我看 lego 可以设置 recursiveNameservers，回头我加个设置，你设置成1.1.1.1/8.8.8.8应该就可以

**Comment by 0xJacky** [comment]
更新到 v2.0.0-beta.22，在 偏好设置 > 基本 中，找到递归域名服务器
<img width="626" alt="image" src="https://github.com/0xJacky/nginx-ui/assets/13096985/ea6fc0ec-7b05-4bda-be4d-eab45f7bf484">

你可以添加多个 DNS 服务器，拖拽排序或删除。

关于 app.ini 的配置说明请参考：https://nginxui.com/zh_CN/guide/config-server.html#recursivenameservers

**Comment by gfgjs** [comment]
> 更新到 v2.0.0-beta.22，在 偏好设置 > 基本 中，找到递归域名服务器 <img alt="image" width="626" src="https://private-user-images.githubusercontent.com/13096985/327918677-ea6fc0ec-7b05-4bda-be4d-eab45f7bf484.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MDE0NjYsIm5iZiI6MTcxNDgwMTE2NiwicGF0aCI6Ii8xMzA5Njk4NS8zMjc5MTg2NzctZWE2ZmMwZWMtN2IwNS00YmRhLWJlNGQtZWFiNDVmN2JmNDg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDA1MzkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhODAxMGVkZDFlZjI0ZTA1YzMzMjc4YTE1MTc0MzIzNGYyNzgxNDNjNmQ1MDk0Mzg0ZWYxNDhkZjNlYjk1ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RwlmIa1C1vJyP5IKvH0ITzG2Ca2eF-erINXrdECkwQQ">
> 
> 你可以添加多个 DNS 服务器，拖拽排序或删除。
> 
> 关于 app.ini 的配置说明请参考：https://nginxui.com/zh_CN/guide/config-server.html#recursivenameservers

好好好！太强了！修改太及时，使我的服务器旋转！

**Comment by jearton** [comment]
我的网络环境里也有软路由，流量会经过OpenClash，这里对DNS有什么影响吗
