### ISSUE TITLE
签发证书卡主了

### ISSUE THREAD

**Issue by jearton** [0xJacky/nginx-ui#378]
![image](https://github.com/0xJacky/nginx-ui/assets/10370433/e33ba7a9-633c-41e4-a806-e14d46e91a3d)

版本：最新版

但是我等了一会儿，刷新页面后，其实已经成功了

**Comment by 0xJacky** [comment]
每次签都这样么，开始就这一次，然后就是有无使用反向代理？

**Comment by jearton** [comment]
试了好几次都是这样，卡在48%，阿里云dns，beta.22版本，新初始化的一个节点，我直接用ip访问的nginx-ui，没有反向代理

**Comment by 0xJacky** [comment]
试试 beta.23 ？

**Comment by jearton** [comment]
好，空了试试，可能是dns的问题，我的软路由里用了fake-ip模式，dns解析出来的ip都是假的

**Comment by 0xJacky** [comment]
对，排除一下 DNS 的问题，因为这个步骤已经是 lego 在执行了

**Comment by jearton** [comment]
重试了一下，现在可以了，我的网络问题

**Comment by 0xJacky** [comment]
好的，关掉吧
