### ISSUE TITLE
升级到beta.23版本后，主控节点仪表盘里看不到被控节点了

### ISSUE THREAD

**Issue by jearton** [0xJacky/nginx-ui#385]

**Comment by 0xJacky** [comment]
你是换的 docker 镜像吗，docker 镜像要用 latest 或者 
v2.0.0-beta.23-patch.2 这个 tag

**Comment by 0xJacky** [comment]
或者可以尝试直接在线升级-重新安装

**Comment by jearton** [comment]
我用的v2.0.0-beta.23，我试试加上patch

**Comment by 0xJacky** [comment]
对，我在 patch 上修了这个问题，你看看 ok 就关掉这个 issue

**Comment by jearton** [comment]
可以了，升级后修复了
