### ISSUE TITLE
修改Server的证书，点击确定后，回显没有变化

### ISSUE THREAD

**Issue by jearton** [0xJacky/nginx-ui#386]
![image](https://github.com/0xJacky/nginx-ui/assets/10370433/586be637-947a-45e0-9e30-c2d4068df3b5)

最新版

不过指令里是改过来了，保存后再回显也是OK的

**Comment by 0xJacky** [comment]
这个其实是保存生效前的证书

**Comment by jearton** [comment]
没保存之前，页面显示会出现不一致，会不会影响用户判断

![image](https://github.com/0xJacky/nginx-ui/assets/10370433/c7a8736b-038b-41fe-8090-4dc1b077cee2)
