### ISSUE TITLE
一键轻松部署并自动续签 Let's Encrypt 证书。有具体说明文档吧，没明白如何做

### ISSUE THREAD

**Issue by ftyszyx** [0xJacky/nginx-ui#388]
一键轻松部署并自动续签 Let's Encrypt 证书。有具体说明文档吧，没明白如何做

**Comment by 0xJacky** [comment]
1. 创建网站-第二部选择启动TLS，就可以看到 用 Let's Encrypt 对网站进行加密 的开关

2. 在已存在的网站中，确保server里有 listen 443 ssl 指令，就可以看到 用 Let's Encrypt 对网站进行加密 的开关

**Comment by ftyszyx** [comment]
一直卡在：正在获取证书，请稍等...

**Comment by ftyszyx** [comment]
> 1. 创建网站-第二部选择启动TLS，就可以看到 用 Let's Encrypt 对网站进行加密 的开关
> 2. 在已存在的网站中，确保server里有 listen 443 ssl 指令，就可以看到 用 Let's Encrypt 对网站进行加密 的开关

一直卡在：正在获取证书，请稍等...

**Comment by 0xJacky** [comment]
> > 1. 创建网站-第二部选择启动TLS，就可以看到 用 Let's Encrypt 对网站进行加密 的开关
> > 2. 在已存在的网站中，确保server里有 listen 443 ssl 指令，就可以看到 用 Let's Encrypt 对网站进行加密 的开关
> 
> 一直卡在：正在获取证书，请稍等...

有用反向代理吗，反向代理了 nginxui

**Comment by ftyszyx** [comment]
> > > 1. 创建网站-第二部选择启动TLS，就可以看到 用 Let's Encrypt 对网站进行加密 的开关
> > > 2. 在已存在的网站中，确保server里有 listen 443 ssl 指令，就可以看到 用 Let's Encrypt 对网站进行加密 的开关
> > 
> > 
> > 一直卡在：正在获取证书，请稍等...
> 
> 有用反向代理吗，反向代理了 nginxui

关掉了nginx_ui的反向代理：
现在新的报错：
正在获取证书，请稍等...
issue cert get acme user error: get default user error: record not found

**Comment by ftyszyx** [comment]
![image](https://github.com/0xJacky/nginx-ui/assets/3063779/ac975064-e42a-48da-98f3-365deca2f6ac)

**Comment by 0xJacky** [comment]
看一下 证书 > ACME 用户中有 System Inital User 吗，如果没有的话可以用你在设置中填的邮件，CA Dir 为空注册一下

**Comment by ftyszyx** [comment]
> 看一下 证书 > ACME 用户中有 System Initial User 吗，如果没有的话可以用你在设置中填的邮件，CA Dir 为空注册一下
> 
> 一般情况下会在首次启动阶段自动注册，如果因为网络问题没法注册的话要手动注册一下

成功了，不过第一次都会失败：
正在获取证书，请稍等...

2024/05/13 11:07:40 [INFO] [Nginx UI] 正在准备 Lego 的配置

2024/05/13 11:07:40 [INFO] [Nginx UI] ACME User: sss, Email: ftyszyx@gmail.com, CA Dir: https://acme-v02.api.letsencrypt.org/directory

2024/05/13 11:07:40 [INFO] [Nginx UI] 正在创建客户端用于与 CA 服务器通信

2024/05/13 11:07:41 [INFO] [Nginx UI] 使用 HTTP01 challenge provider

2024/05/13 11:07:41 [INFO] [Nginx UI] 正在获取证书

2024/05/13 11:07:41 [INFO] [blog.bytefuse.cn] acme: Obtaining bundled SAN certificate

2024/05/13 11:07:42 [INFO] [blog.bytefuse.cn] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/350075139637

2024/05/13 11:07:42 [INFO] [blog.bytefuse.cn] acme: Could not find solver for: tls-alpn-01

2024/05/13 11:07:42 [INFO] [blog.bytefuse.cn] acme: use http-01 solver

2024/05/13 11:07:42 [INFO] [blog.bytefuse.cn] acme: Trying to solve HTTP-01

2024/05/13 11:07:43 [INFO] [blog.bytefuse.cn] Served key authentication

2024/05/13 11:07:46 [INFO] [blog.bytefuse.cn] Served key authentication

2024/05/13 11:07:59 [INFO] [blog.bytefuse.cn] Served key authentication

2024/05/13 11:08:31 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/350075139637

2024/05/13 11:08:32 [INFO] [Nginx UI] 正在重载 Nginx

obtain certificate error: error: one or more domains had a problem: [blog.bytefuse.cn] acme: error: 400 :: urn:ietf:params:acme:error:dns :: During secondary validation: DNS problem: query timed out looking up A for blog.bytefuse.cn; no valid AAAA records found for blog.bytefuse.cn

第二次才成功

**Comment by ftyszyx** [comment]
非常感谢，很帮的系统

**Comment by 0xJacky** [comment]
这个看起来是 DNS 的解析的延迟，一般修改完解析之后可以等待几分钟再签
