### ISSUE TITLE
二级域名的反向代理可随意访问

### ISSUE THREAD

**Issue by thansury** [0xJacky/nginx-ui#389]
二级域名aa.bb.com经过反代后，可以随意更改前缀aa为任意字符，均可访问服务器。如果在高级设置里，添加上       
 if ($host != $server_name) {
            return 204; 
}
则可以避免这个问题。
![EN9UIPAXTC0R(66@`BQD$ 7](https://github.com/0xJacky/nginx-ui/assets/63008892/5bde8c98-bb6e-42fc-9c80-6cde75fd3236)
![QQ截图20240512174257](https://github.com/0xJacky/nginx-ui/assets/63008892/f11d941d-9c72-4b0a-8cf4-74bf554bc19f)

实际上**反向代理模板**是没有这个代码的，请求开发者下一更新添加此代码！感谢开发者带来的优秀产品，使我省了很多时间。

**Comment by 0xJacky** [comment]
返回 404 好像也可以？

**Comment by 0xJacky** [comment]
我加在 server block 里应该也是可以的吧
