### ISSUE TITLE
证书无法获取

### ISSUE THREAD

**Issue by ifwwww** [0xJacky/nginx-ui#390]
在debian lxc容器下运行的，腾讯云dns验证，验证成功了，获取证书的时候提示no such file or directory

**Comment by 0xJacky** [comment]
可以进入 /etc/nginx/ssl 看看文件夹存在吗

**Comment by ifwwww** [comment]
大佬，刚刚我看了一下，不存在

**Comment by 0xJacky** [comment]
ssl 文件夹不存在，还是文件夹里没有内容呢

**Comment by ifwwww** [comment]
是整个nginx目录都不存在
![image](https://github.com/0xJacky/nginx-ui/assets/65443757/5d9f66f5-236e-4c85-9cde-96c4b83aff51)
![image](https://github.com/0xJacky/nginx-ui/assets/65443757/d5c981c1-244c-45cf-a1bb-84771c606eeb)
![image](https://github.com/0xJacky/nginx-ui/assets/65443757/dbfe91b4-1212-434d-91db-bd53f98ae95a)

**Comment by 0xJacky** [comment]
嗯？你有安装 nginx 吗

**Comment by 0xJacky** [comment]
如果没安装，先 apt install nginx 一下

如果安装，执行 nginx -V 发一下输出，或者在 app.ini 中手动指定 nginx 的配置目录

**Comment by ifwwww** [comment]
呃，是直接脚本安装的nginx-ui，我以为直接连nginx一起安装了

**Comment by 0xJacky** [comment]
好吧，没有的

**Comment by 0xJacky** [comment]
你安装完 nginx 之后，重启一下 nginx ui，然后看看能不能用

**Comment by ifwwww** [comment]
那我就懂了，谢谢大佬，麻烦了

**Comment by 0xJacky** [comment]
可以，你安装完确认一下，如果没有问题就 Close 掉这个 issue 哈

**Comment by ifwwww** [comment]
已经正常，属于本人操作问题，谢谢大佬
