### ISSUE TITLE
到期SSL证书重复申请 | SSL certificate repeat application in beta.23

### ISSUE THREAD

**Issue by kekylin** [0xJacky/nginx-ui#391]
我通过Nginx-UI申请了一张泛域名证书，在站点管理添加了两个站点反向代理，使用的是Nginx-UI申请的泛域名证书。在泛域名证书到达七天期限时，出现了三次证书更新通知。
在站点配置均有下面配置：
`    location /.well-known/acme-challenge {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr:$remote_port;
        proxy_pass http://127.0.0.1:9180;`
在偏好设置——证书续期间隔设置为7天。
疑是两个站点配置和系统设置共触发了三次证书更新申请，是否应该为系统申请一次即可，站点配置套用泛域名证书的。
![QQ截图20240512212911](https://github.com/0xJacky/nginx-ui/assets/65521882/6e3a7d65-3fe5-4821-82fc-67ebbf83e948)
![QQ截图20240512212945](https://github.com/0xJacky/nginx-ui/assets/65521882/ae031af8-9f35-4959-8143-4103edc111d3)
![QQ截图20240512212958](https://github.com/0xJacky/nginx-ui/assets/65521882/f5a990de-0b34-4a10-ad73-7b3d41022b30)
![QQ截图20240512214115](https://github.com/0xJacky/nginx-ui/assets/65521882/20ca7597-d9e1-4a87-944d-5bf78c482dfe)

**Comment by 0xJacky** [comment]
这个问题应该是最新 beta.23 的破坏性更新引入的，可以试试将这个证书删除，重新签发，再在配置文件中使用新证书的路径。

The problem appears to have been introduced by the latest breaking update in beta.23, so try deleting the certificate, issuing it again, and using the new certificate path in your configuration file.

**Comment by 0xJacky** [comment]
是的，是这个问题，必须要重新签发

**Comment by 0xJacky** [comment]
或者手动更新证书路径，也是 ok 的

**Comment by 0xJacky** [comment]
最好是尽快更新或者重新签发，不然等会又触发限流了😂

**Comment by 0xJacky** [comment]
好的，后面看看是否还会重新签发，如果没有问题就关闭 issue 哈

**Comment by leic4u** [comment]
我的从 5 月 8 号开始就每半小时签发一次，刷了 2700 条的通知，但是因为通知仅限面板查看（顺便请求一下将通知发送到 Telegram bot 的功能），没登录就没发现，刚刚登面板瞅两眼才发现。

现在已经被限流了，没法删了立即重新签发，想停一下续签，结果没找到暂停续签的功能。

我现在是不是只能删掉证书裸奔一周，或者删掉证书再把所有证书文件手动上传配一遍？😂

**Comment by 0xJacky** [comment]
> 我的从 5 月 8 号开始就每半小时签发一次，刷了 2700 条的通知，但是因为通知仅限面板查看（顺便请求一下将通知发送到 Telegram bot 的功能），没登录就没发现，刚刚登面板瞅两眼才发现。
> 
> 现在已经被限流了，没法删了立即重新签发，想停一下续签，结果没找到暂停续签的功能。
> 
> 我现在是不是只能删掉证书裸奔一周，或者删掉证书再把所有证书文件手动上传配一遍？😂

不用，签证书等十分钟就能签，用的接口不一样不会被限流。续期的话要等168h。

**Comment by leic4u** [comment]
> 不用，签证书等十分钟就能签，用的接口不一样不会被限流。续期的话要等168h。

试了下删掉证书重新签发，报错让我 `retry after 2024-05-20T20:25:08Z` 😂

我是不是可以用换成用 ZeroSSL 来重新签发来规避这个问题？

在 ACME 用户里面配置一个新的邮箱，把 CA Dir 填为 `https://acme.zerossl.com/v2/DV90` 就行吧？

我去试试。

**Comment by 0xJacky** [comment]
> > 不用，签证书等十分钟就能签，用的接口不一样不会被限流。续期的话要等168h。
> 
> 试了下删掉证书重新签发，报错让我 `retry after 2024-05-20T20:25:08Z` 😂
> 
> 我是不是可以用换成用 ZeroSSL 来重新签发来规避这个问题？
> 
> 在 ACME 用户里面配置一个新的邮箱，把 CA Dir 填为 `https://acme.zerossl.com/v2/DV90` 就行吧？
> 
> 我去试试。

zerossl 应该是不能用的，我之前有测试过，它跟 let's encrypted 的注册方式不太一样。不过理论上符合 [RFC8555](https://www.rfc-editor.org/rfc/rfc8555.html) 的都能用。

**Comment by leic4u** [comment]
> zerossl 应该是不能用的，我之前有测试过，它跟 let's encrypted 的注册方式不太一样。不过理论上符合 [RFC8555](https://www.rfc-editor.org/rfc/rfc8555.html) 的都能用。

试了，确实不行，那我现在除了裸奔一天或者手动导入证书以外，还有其他办法可以治疗我这种情况么🤣

**Comment by 0xJacky** [comment]
> > zerossl 应该是不能用的，我之前有测试过，它跟 let's encrypted 的注册方式不太一样。不过理论上符合 [RFC8555](https://www.rfc-editor.org/rfc/rfc8555.html) 的都能用。
> 
> 试了，确实不行，那我现在除了裸奔一天或者手动导入证书以外，还有其他办法可以治疗我这种情况么🤣

裸奔一天也不是不能接受吧？这个证书理论上到8月才过期

**Comment by leic4u** [comment]
> 裸奔一天也不是不能接受吧？这个证书理论上到8月才过期

哎，我发现我删除了证书，但是好像并没有真的删除掉，访问的还是带 https 的。那这样看来我只需要删除所有证书，明天重新签发就行了？

**Comment by 0xJacky** [comment]
> > 裸奔一天也不是不能接受吧？这个证书理论上到8月才过期
> 
> 
> 
> 哎，我发现我删除了证书，但是好像并没有真的删除掉，访问的还是带 https 的。那这样看来我只需要删除所有证书，明天重新签发就行了？

是啊，删除只是删的数据库里的记录，不会动文件的

**Comment by 0xJacky** [comment]
Resolved in v2.0.0-beta.24.
