### ISSUE TITLE
网站管理建议增加自定义分类并以多个TAB显示

### ISSUE THREAD

**Issue by jearton** [0xJacky/nginx-ui#392]
![image](https://github.com/0xJacky/nginx-ui/assets/10370433/75b5f6c2-89a3-4a80-8a62-bbc2ce1bf143)

或者其它UI形式也可以，总之痛点就是我站点太多了，一眼看不过来，需要人为分类一下

**Comment by 0xJacky** [comment]
未来可期

**Comment by jearton** [comment]
求加速。我现在站点太多了，管理开始吃力了，眼镜都看花了，每次都得用ctrl+f，全局搜索关键词
