### ISSUE TITLE
终端鉴权优化

### ISSUE THREAD

**Issue by Naochen2799** [0xJacky/nginx-ui#394]
https://yourdomain.com/#/terminal
没有终端相关的鉴权，存在被滥用的风险。
注：包括demo站点！

**Comment by 0xJacky** [comment]
我不清楚您是如何认为我们没有做终端鉴权的
https://github.com/0xJacky/nginx-ui/blob/189f6239940b5893a3cc639951680e1f880c74f2/router/routers.go#L66-L70

后端需要通过 token 验证才可以进入 web 终端，其次，我在文档中有注明使用 login 作为启动命令，这样相当于可以多套一层 linux 的用户认证
https://nginxui.com/zh_CN/guide/config-server.html#startcmd
<img width="795" alt="image" src="https://github.com/0xJacky/nginx-ui/assets/13096985/6877a605-651c-4529-aa7f-5096006bbc43">

**Comment by Naochen2799** [comment]
我没有完整的阅读文档，忽略了Linux默认的用户名和密码进行验证。
但是目前的demo网站似乎也没有添加额外的授权，可能存在风险

**Comment by 0xJacky** [comment]
因为 demo 为了展示，所以直接用的 bash 作为启动命令

**Comment by 0xJacky** [comment]
后续会增加设置，禁用 WebTerminal，以及二步验证等
