### ISSUE TITLE
请求 DNS 服务商增加华为云 | Support for DNS provider: huawei cloud

### ISSUE THREAD

**Issue by lyj5812** [0xJacky/nginx-ui#395]
请求增加华为云dns的支持，华为dns免费
![image](https://github.com/0xJacky/nginx-ui/assets/37658093/6638c931-159b-4584-af3e-2c0606da17cd)

**Comment by 0xJacky** [comment]
这个要看 lego 什么时候支持

**Comment by freshgeek** [comment]
接入了dns 操作，能否进一步支持在页面上配置dns 解析？这样就不需要登录对应的云平台去设置解析ip了

**Comment by 0xJacky** [comment]
> 接入了dns 操作，能否进一步支持在页面上配置dns 解析？这样就不需要登录对应的云平台去设置解析ip了

很抱歉，这个不是我们开发的重心，目前已有的 DNS 操作是因为刚好有 lego 这么伟大的项目节省了我手动对接几十家 DNS 提供商。当然，我也很期待有贡献者或者项目能够支持这个需求。

**Comment by 0xJacky** [comment]
已经有贡献者为 lego 贡献了华为云的 DNS，我这边下个 beta 版会发布
