### ISSUE TITLE
深色模式如何启用

### ISSUE THREAD

**Issue by hale177** [0xJacky/nginx-ui#40]
没有找到相关选项启用 webui 的 深色模式

**Comment by 0xJacky** [comment]
深色模式跟随系统和浏览器设置的JackyOn Nov 1, 2022, at 5:00 PM, hale177 ***@***.***> wrote:﻿
没有找到相关选项启用 webui 的 深色模式

**Comment by hale177** [comment]
> 深色模式跟随系统和浏览器设置的JackyOn Nov 1, 2022, at 5:00 PM, hale177 ***@***.***> wrote:﻿ 没有找到相关选项启用 webui 的 深色模式 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

好吧，我以为页面上有开关 ，是否做成页面开关按钮更合适一些呢
