### ISSUE TITLE
docker 挂载 window目录，无法申请证书

### ISSUE THREAD

**Issue by Ador-able** [0xJacky/nginx-ui#403]
证书文件夹命名为 `*.test.top_test.top_2048` 样式，windows 文件夹禁止包含 `*`

**Comment by 0xJacky** [comment]
感谢反馈，由于手头上没有 Windows 的机器，所以 Nginx UI 并不保证在 Windows 系统下功能的可用性，不过这个问题应该好说，我之后会修复。

**Comment by Ador-able** [comment]
我这边是 window + wsl2 + docker engine 。没有使用 docker desktop

**Comment by 0xJacky** [comment]
之前修错了，今天 review 代码的时候发现这个问题没解决，现在已经解决了，等 beta.30 的时候会发布。
