### ISSUE TITLE
证书自动续期失败

### ISSUE THREAD

**Issue by jearton** [0xJacky/nginx-ui#406]
2024/05/23 16:34:09 [Error] obtain certificate error: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many certificates (5) already issued for this exact set of domains in the last 168 hours: *.creatly.team,creatly.team, retry after 2024-05-23T15:40:15Z: see https://letsencrypt.org/docs/duplicate-certificate-limit/

是不是重试得太频繁了啊

**Comment by 0xJacky** [comment]
已在 beta.24 中修复，等下一次可以正常续期之后，就会回复正常
