### ISSUE TITLE
控制nginx 的重启和重载无效果

### ISSUE THREAD

**Issue by en-o** [0xJacky/nginx-ui#408]
**Describe the bug**
控制nginx 的重启和重载无效果

**To Reproduce**
1. nginx ConfigDir 关联原有的conf目录
2. 在ui配置管理里编辑原有的配置
3. 编辑之后重载nginx
4. 重载/重启都不生效

**Expected behavior**
1. 编辑配置后会生效
2.  location /demo -> demo2  
3. http://xx/demo2

**Screenshots**
## 功能点
![image](https://github.com/0xJacky/nginx-ui/assets/45027672/ef043450-b7e0-4aab-8b25-4b53991ef9b6)
## nginx配置
![image](https://github.com/0xJacky/nginx-ui/assets/45027672/228cfb8b-587b-4f31-8a0f-6a929dda6691)
![image](https://github.com/0xJacky/nginx-ui/assets/45027672/743c1ccd-163d-4dbe-bc98-da79fd6f889c)
![image](https://github.com/0xJacky/nginx-ui/assets/45027672/770f01d7-d15c-4477-b7cc-29f4d81906aa)
## nignx ui 是我代理出去的
![image](https://github.com/0xJacky/nginx-ui/assets/45027672/f4f95067-e2f7-4bc5-b9af-6cde7a6935d1)

**Info (please complete the following information):**
 - Server OS: centos7
 - Server Arch:  amd64
 - Nginx UI Version: v2.0.0-beta.24
 - Your Browser: Chrome

**Additional context**

**Comment by 0xJacky** [comment]
发一下 nginx -V 的输出，也可以自己配置重载命令，还要看一下是不是因为权限的问题引起

**Comment by en-o** [comment]
> 发一下 nginx -V 的输出，也可以自己配置重载命令，还要看一下是不是因为权限的问题引起
```shell
[root@swdetabes bin]# nginx -V
nginx version: openresty/1.21.4.1
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) 
built with OpenSSL 1.1.1n  15 Mar 2022 (running with OpenSSL 1.1.1s  1 Nov 2022)
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt='-O2 -DNGX_LUA_ABORT_AT_PANIC -I/usr/local/openresty/zlib/include -I/usr/local/openresty/pcre/include -I/usr/local/openresty/openssl111/include' --add-module=../ngx_devel_kit-0.3.1 --add-module=../echo-nginx-module-0.62 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.33 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.09 --add-module=../srcache-nginx-module-0.32 --add-module=../ngx_lua-0.10.21 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.9 --add-module=../ngx_stream_lua-0.0.11 --with-ld-opt='-Wl,-rpath,/usr/local/openresty/luajit/lib -L/usr/local/openresty/zlib/lib -L/usr/local/openresty/pcre/lib -L/usr/local/openresty/openssl111/lib -Wl,-rpath,/usr/local/openresty/zlib/lib:/usr/local/openresty/pcre/lib:/usr/local/openresty/openssl111/lib' --with-cc='ccache gcc -fdiagnostics-color=always' --with-pcre-jit --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_v2_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --with-http_stub_status_module --with-http_realip_module --with-http_addition_module --with-http_auth_request_module --with-http_secure_link_module --with-http_random_index_module --with-http_gzip_static_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-threads --with-compat --with-stream --with-http_ssl_module


```
ReloadCmd  命令我配置了的没啥效果

**Comment by 0xJacky** [comment]
手动执行 restart / reload 命令的时候有什么输出吗

**Comment by en-o** [comment]
> 手动执行 restart / reload 命令的时候有什么输出吗

ui 上面的那个主动点击么。那个我看了日志和接口，就一个成功信息， 我自己手动在ssh控制台执行nginx -s reload 是正常的工作的

**Comment by 0xJacky** [comment]
你不是用 docker 安装的吧？

**Comment by en-o** [comment]
> 你不是用 docker 安装的吧？
脚本安装的   nginx也是

**Comment by 0xJacky** [comment]
这个问题我暂时没办法在现有环境复现，也许您可以补充关于这个问题的更多细节，比如 nginx 的安装方式和步骤，我有空时再虚拟机里试试，不过这个功能是直接调用的 exec.Command 函数，最多就是权限不够没法执行，但是如果你运行在 root 下呢还是这样，我可能得看看能不能复现才能给你答复

**Comment by 0xJacky** [comment]
我今天在 centos7 的虚拟机里，通过 nginx.org 的源安装最新版本 1.27 的 nginx，然后 nginx-ui 的 app.ini 配置重载命令为 systemctl restart nginx，是可以正常工作的，reload 也是可以正常工作的

<img width="570" alt="image" src="https://github.com/0xJacky/nginx-ui/assets/13096985/db36ab4c-d96f-4cbb-8eb0-12fcdd3d76c5">

**Comment by 0xJacky** [comment]
但是我似乎注意到另一个细节，你在入口的 nginx.conf 中没有配置 include /etc/nginx/sites-available; 大概这就是真正的问题吧

**Comment by 0xJacky** [comment]
附重启前后的 nginx.pid 变化

<img width="312" alt="image" src="https://github.com/0xJacky/nginx-ui/assets/13096985/f72ce106-cbd1-4ea0-8adb-f27d6c93ff59">

**Comment by FatMii** [comment]
docker启动目前我也遇到这个问题，重启和重载都没效果：
docker 启动命令：
```bash
docker run -dit --name=nginx-ui --restart=always -e TZ=Asia/Shanghai -e NGINX_UI_IGNORE_DOCKER_SOCKET=true -v /etc/nginx:/etc/nginx -v /var/log/nginx:/var/log/nginx -v /etc/nginx-ui:/etc/nginx-ui -v /var/backups/nginx-ui:/var/backups/nginx-ui -p 9000:9000 uozi/nginx-ui:latest
```
在宿主机的 /etc/nginx-ui/app.ini也修改了命令：

<img width="390" height="227" alt="Image" src="https://github.com/user-attachments/assets/1e2c6480-4961-4a4c-9525-10386c7a0c51" />

然后docker restart，使用`systemctl status nginx`, 依然没有变化，重启前后的 nginx.pid 也没有变化

**Comment by 0xJacky** [comment]
> docker启动目前我也遇到这个问题，重启和重载都没效果： docker 启动命令：
> 
> docker run -dit --name=nginx-ui --restart=always -e TZ=Asia/Shanghai -e NGINX_UI_IGNORE_DOCKER_SOCKET=true -v /etc/nginx:/etc/nginx -v /var/log/nginx:/var/log/nginx -v /etc/nginx-ui:/etc/nginx-ui -v /var/backups/nginx-ui:/var/backups/nginx-ui -p 9000:9000 uozi/nginx-ui:latest
> 在宿主机的 /etc/nginx-ui/app.ini也修改了命令：
> 
> <img alt="Image" width="390" height="227" src="https://private-user-images.githubusercontent.com/39074672/592839922-1e2c6480-4961-4a4c-9525-10386c7a0c51.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Nzg4MTA2NzEsIm5iZiI6MTc3ODgxMDM3MSwicGF0aCI6Ii8zOTA3NDY3Mi81OTI4Mzk5MjItMWUyYzY0ODAtNDk2MS00YTRjLTk1MjUtMTAzODZjN2EwYzUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNTE1VDAxNTkzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0ZWQ1Nzg5ZGU3MWUyZTA3Mjc4ZWY0MzhiMTczNzdhMWVjODkyODFkOGI2MTFmNDg0MWUwMWQxYjYxY2QxY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.BE8BhXvu3OCHlB-pB97Li0ZBXbXMoSZ4n1tl98mSIFA">
> 然后docker restart，使用`systemctl status nginx`, 依然没有变化，重启前后的 nginx.pid 也没有变化

docker 版本只能控制容器内的 nginx

**Comment by FatMii** [comment]
更换其他安装方式后似乎还是无法重载和重启：
1.安装命令：
```bash
bash -c "$(curl -L https://cloud.nginxui.com/install.sh)" @ install
```
2. nginx 版本

```bash
nginx version: nginx/1.20.1
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)
built with OpenSSL 1.1.1k  FIPS 25 Mar 2021
TLS SNI support enabled
configure arguments: --prefix=/usr/share/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib64/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --http-client-body-temp-path=/var/lib/nginx/tmp/client_body --http-proxy-temp-path=/var/lib/nginx/tmp/proxy --http-fastcgi-temp-path=/var/lib/nginx/tmp/fastcgi --http-uwsgi-temp-path=/var/lib/nginx/tmp/uwsgi --http-scgi-temp-path=/var/lib/nginx/tmp/scgi --pid-path=/run/nginx.pid --lock-path=/run/lock/subsys/nginx --user=nginx --group=nginx --with-compat --with-debug --with-file-aio --with-google_perftools_module --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_degradation_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module=dynamic --with-http_mp4_module --with-http_perl_module=dynamic --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-http_xslt_module=dynamic --with-mail=dynamic --with-mail_ssl_module --with-pcre --with-pcre-jit --with-stream=dynamic --with-stream_ssl_module --with-stream_ssl_preread_module --with-threads --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic' --with-ld-opt='-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -Wl,-E'

```

3. /etc/nginx-ui/app.ini
```

[nginx]
AccessLogPath   = 
ErrorLogPath    = 
LogDirWhiteList = 
ConfigDir       = /etc/nginx
ConfigPath      = /etc/nginx/nginx.conf
PIDPath         = /var/run/nginx.pid
SbinPath        = /usr/sbin/nginx
TestConfigCmd   = nginx -t
ReloadCmd       = systemctl reload nginx
RestartCmd      = systemctl restart nginx
StubStatusPort  = 0
ContainerName   = 

[nginx_log]
IndexingEnabled          = false
IndexPath                = 
IncrementalIndexInterval = 0

```

4. 在服务器直接执行： `systemctl restart nginx` 是可以成功重启的

**Comment by 0xJacky** [comment]
> 更换其他安装方式后似乎还是无法重载和重启： 1.安装命令：
> 
> bash -c "$(curl -L https://cloud.nginxui.com/install.sh)" @ install
> 2. nginx 版本
> 
> nginx version: nginx/1.20.1
> built by gcc 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)
> built with OpenSSL 1.1.1k  FIPS 25 Mar 2021
> TLS SNI support enabled
> configure arguments: --prefix=/usr/share/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib64/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --http-client-body-temp-path=/var/lib/nginx/tmp/client_body --http-proxy-temp-path=/var/lib/nginx/tmp/proxy --http-fastcgi-temp-path=/var/lib/nginx/tmp/fastcgi --http-uwsgi-temp-path=/var/lib/nginx/tmp/uwsgi --http-scgi-temp-path=/var/lib/nginx/tmp/scgi --pid-path=/run/nginx.pid --lock-path=/run/lock/subsys/nginx --user=nginx --group=nginx --with-compat --with-debug --with-file-aio --with-google_perftools_module --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_degradation_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module=dynamic --with-http_mp4_module --with-http_perl_module=dynamic --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-http_xslt_module=dynamic --with-mail=dynamic --with-mail_ssl_module --with-pcre --with-pcre-jit --with-stream=dynamic --with-stream_ssl_module --with-stream_ssl_preread_module --with-threads --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic' --with-ld-opt='-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -Wl,-E'
> 3. /etc/nginx-ui/app.ini
> 
> ```
> 
> [nginx]
> AccessLogPath   = 
> ErrorLogPath    = 
> LogDirWhiteList = 
> ConfigDir       = /etc/nginx
> ConfigPath      = /etc/nginx/nginx.conf
> PIDPath         = /var/run/nginx.pid
> SbinPath        = /usr/sbin/nginx
> TestConfigCmd   = nginx -t
> ReloadCmd       = systemctl reload nginx
> RestartCmd      = systemctl restart nginx
> StubStatusPort  = 0
> ContainerName   = 
> 
> [nginx_log]
> IndexingEnabled          = false
> IndexPath                = 
> IncrementalIndexInterval = 0
> ```
> 
> 4. 在服务器直接执行： `systemctl restart nginx` 是可以成功重启的

请看文档
https://nginxui.com/zh_CN/guide/config-nginx.html#restartcmd

**Comment by FatMii** [comment]
> > 更换其他安装方式后似乎还是无法重载和重启： 1.安装命令：
> > bash -c "$(curl -L https://cloud.nginxui.com/install.sh)" @ install
> > 2. nginx 版本
> > nginx version: nginx/1.20.1
> > built by gcc 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)
> > built with OpenSSL 1.1.1k  FIPS 25 Mar 2021
> > TLS SNI support enabled
> > configure arguments: --prefix=/usr/share/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib64/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --http-client-body-temp-path=/var/lib/nginx/tmp/client_body --http-proxy-temp-path=/var/lib/nginx/tmp/proxy --http-fastcgi-temp-path=/var/lib/nginx/tmp/fastcgi --http-uwsgi-temp-path=/var/lib/nginx/tmp/uwsgi --http-scgi-temp-path=/var/lib/nginx/tmp/scgi --pid-path=/run/nginx.pid --lock-path=/run/lock/subsys/nginx --user=nginx --group=nginx --with-compat --with-debug --with-file-aio --with-google_perftools_module --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_degradation_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module=dynamic --with-http_mp4_module --with-http_perl_module=dynamic --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-http_xslt_module=dynamic --with-mail=dynamic --with-mail_ssl_module --with-pcre --with-pcre-jit --with-stream=dynamic --with-stream_ssl_module --with-stream_ssl_preread_module --with-threads --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic' --with-ld-opt='-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -Wl,-E'
> > 3. /etc/nginx-ui/app.ini
> > ```
> > 
> > [nginx]
> > AccessLogPath   = 
> > ErrorLogPath    = 
> > LogDirWhiteList = 
> > ConfigDir       = /etc/nginx
> > ConfigPath      = /etc/nginx/nginx.conf
> > PIDPath         = /var/run/nginx.pid
> > SbinPath        = /usr/sbin/nginx
> > TestConfigCmd   = nginx -t
> > ReloadCmd       = systemctl reload nginx
> > RestartCmd      = systemctl restart nginx
> > StubStatusPort  = 0
> > ContainerName   = 
> > 
> > [nginx_log]
> > IndexingEnabled          = false
> > IndexPath                = 
> > IncrementalIndexInterval = 0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 4. 在服务器直接执行： `systemctl restart nginx` 是可以成功重启的
> 
> 请看文档 https://nginxui.com/zh_CN/guide/config-nginx.html#restartcmd

经检查后发现：在更换启动方式后，没有在正确的配置文件路径上进行修改配置文件：`/usr/local/etc/nginx-ui/app.ini` ,按照文档中修改后，重启功能正常。感谢作者耐心指导与回复！ @0xJacky
