### ISSUE TITLE
网站管理/站点列表 搜索功能

### ISSUE THREAD

**Issue by hale177** [0xJacky/nginx-ui#41]
- [x] 是否考虑站点列表  右边增加一个搜索框，对于对外公网映射站点很多（>= 几十个），增加一个搜索功能很实用
找起来方便 ：）

- [x] 搜索条件可以是 名称描述 ，配置里面的 ip地址
- [x] 突然发现【名称】在第一次创建后，不支持修改

**Comment by 0xJacky** [comment]
可以的，这阵子比较忙会，更新比较随缘。

**Comment by hale177** [comment]
已更新验证 ok ，perfect ~

**Comment by 0xJacky** [comment]
先不关吧 还有两个问题没修
