### ISSUE TITLE
Browser Search not working properly

### ISSUE THREAD

**Issue by bitsky6** [0xJacky/nginx-ui#412]
**Describe the bug**

**To Reproduce**
1. Go to 'Manage Sites -> Sites Lists'
2. Click on 'any of the configs'
3. When you have it open in advanced mode and try to search the content of a larger config that needs scrolling as it can't fit in one page you press CTRL + F as usually to search for a word.
4. It will only match what is on the current page, as soon as I try to scroll down the match disappears and wont see all of them.
5. Would be preferable maybe the search to be inside the editor on the top so can actually search inside the config for specific words.

**Expected behavior**
I expect when I open in advanced mode the config and I want to search for the word for example "socket" it will match all words inside the config with simply pressing CTRL + F so can find and replace in case need multiple matches.

**Screenshots**
On this page I search for the word socket and gives me 6 matches.
But if I actually scroll down inside the config are 2 more socket words which are not matched unless scrolled down.
This can be dangerous in case you think have found all the changes you need but actually you missed some.
![image](https://github.com/0xJacky/nginx-ui/assets/57507315/31294731-be69-42bd-9fde-16a9610d038c)

![image](https://github.com/0xJacky/nginx-ui/assets/57507315/5d192853-7945-4073-b3b7-8d6246fc72e1)

**Info (please complete the following information):**
 - Server OS: Docker
 - Server Arch: [e.g. x86, ]
 - Nginx UI Version: 2.0.0-beta.24 (135)
 - Your Browser: [e.g. Chrome, Firefox]

**Comment by 0xJacky** [comment]
Hi @bitsky6, I just load the search box module of ace editor for it, and you will be able to use the search feature by pressing Ctrl+F (Command+F for macOS) in next beta version of Nginx UI.

<img width="853" alt="image" src="https://github.com/0xJacky/nginx-ui/assets/13096985/c85ed329-8497-47fc-9a83-1432347dd89f">

**Comment by bitsky6** [comment]
Thanks for the feedback will wait on the new one having this.
