### ISSUE TITLE
get directory at '': Get "": unsupported protocol scheme ""

### ISSUE THREAD

**Issue by ethaniel86** [0xJacky/nginx-ui#417]
**Describe the bug**
ACME 添加用户报错

**问题复现**
1. 证书
2. 点 'ACME用户'
3. 点 '提交'
4. 报错 “get directory at '': Get "": unsupported protocol scheme ""

**截图**
<img width="872" alt="Screenshot 2024-06-13 at 6 21 57 PM" src="https://github.com/0xJacky/nginx-ui/assets/11464581/24cfbf64-402c-444a-8ddc-d5fcfb8ca8d0">

**Info (please complete the following information):**
 - Server OS: Ubuntu 22.04
 - Server Arch: x86_64
 - Nginx UI Version: 2.0.0-beta.24 (从2.0.0-beta.8升级上来的)
 - Your Browser: Chrome

**Additional context**
发通配符证书报错，就尝试加“ACME用户”看能不能解决

<img width="585" alt="Screenshot 2024-06-13 at 6 28 49 PM" src="https://github.com/0xJacky/nginx-ui/assets/11464581/2a50be8c-acc3-4daf-b4ce-699f923e2532">

**Comment by 0xJacky** [comment]
应该是两个问题，默认用户会自动创建的，可以等几分钟看一下

**Comment by 0xJacky** [comment]
Hi, 现在可以看到 System Initial User 了吗

**Comment by ethaniel86** [comment]
《ACME 用户》 页面还是空的，没数据。

**Comment by 0xJacky** [comment]
重启一下，看看日志
```
journalctl -u nginx-ui
```

**Comment by 0xJacky** [comment]
正常情况下，网络正常，邮件没有被封，ip 没有触发限流，首次启动会注册默认用户

<img width="330" alt="image" src="https://github.com/0xJacky/nginx-ui/assets/13096985/7f7ed191-1c63-4e7e-9d51-47c69a67e15f">

**Comment by ethaniel86** [comment]
Jun 14 12:25:59 LS-108582-37600 nginx-ui[3140634]: 2024-06-14 12:25:59        ERROR        cert/logger.go:30        AutoCert issue cert get acme user error: get default user error: record not found
Jun 14 12:25:59 LS-108582-37600 nginx-ui[3140634]: 2024-06-14 12:25:59        INFO        cert/auto_cert.go:27        AutoCert Worker End
Jun 14 12:26:00 LS-108582-37600 nginx-ui[3140634]: 2024-06-14 12:26:00        INFO        cert/register.go:50        ACME Default User registered

![WhatsApp Image 2024-06-14 at 12 29 33_027393f9](https://github.com/0xJacky/nginx-ui/assets/11464581/8171e1de-0f12-4d6a-a282-f4bfa539f58f)

重启后就有了。
这台机器有51个域名。有没有办法有效解决限流的问题？

**Comment by 0xJacky** [comment]
这个和域名的数量关系不是很大，beta19 的时候，针对注册、签发、续期的续期做了优化，现在启动之后只会注册一个用户，之后的限流政策请参考：https://letsencrypt.org/zh-cn/docs/rate-limits/
