### ISSUE TITLE
casdoor settings are not available in Preference and redirect is not available either

### ISSUE THREAD

**Issue by SamLangTen** [0xJacky/nginx-ui#423]
**Describe the bug**
I try to enable casdoor sso for nginxui with the lastest docker image, but there is nothing about casdoor in Preference pages.
And I found that app.ini can be fill with casdoor settings and I do so. After that a fresh-new "SSO Login" button appeared on the login page. Clicking this button can redirect me to casdoor authentication page and login is ok, but when casdoor redirects me back to nginxui nothing happend, I still need to login.

**To Reproduce**
1. Go to 'Login Page'
2. Click on 'SSO Login'
3. Redirect to casdoor and login
4. Redirect to nginxui

**Expected behavior**
After casdoor redirects me back to nginxui, I should be logged into nginxui instead of stuck in login page

**Screenshots**

**Info (please complete the following information):**
 - Server OS: Debian
 - Server Arch: x86
 - Nginx UI Version: 2.0.0-beta.24 (135)
 - Your Browser: Chrome

**Additional context**
None

**Comment by SamLangTen** [comment]
I'm confused about the code
https://github.com/0xJacky/nginx-ui/blob/6f349aa12a46d93d299913eee92066f1b75ed012/api/user/router.go#L10
The router restricts the callback URL to be called only by the POST method. However, when a user is redirected back to the callback URL, it's impossible to use the POST method.

Additionally, even when I use Postman to trigger the callback URL, it's still helpless. It seems that nginx-ui can't read the certificate properly from the app.ini file.

**Comment by 0xJacky** [comment]
Thank you for your report. This feature was contributed by a community member, but unfortunately, the full configuration documentation is missing.

Over the past month, our focus has been elsewhere, which is why I didn’t reply to you sooner. We have now reviewed the code and confirmed that it is functional. We will update the documentation shortly so you can configure it accordingly.

For now, you can refer to the following configuration: 
```ini
[casdoor]
Endpoint     = http://192.168.215.1:8001 # the endpoint is the casdoor baseurl
ClientId     = 637cb*****a2b3f
ClientSecret = 1b503e2f77bd*****e2f05ecb6bc0846eda
Certificate  = """
-----BEGIN CERTIFICATE-----
****
-----END CERTIFICATE-----
"""
Organization = built-in
Application  = nginx-ui
RedirectUri  = `http://localhost:9001/#/login` # the login url of your nginx-ui
```
