### ISSUE TITLE
password not recognized, unable to change it after installation

### ISSUE THREAD

**Issue by ntalamdotcom** [0xJacky/nginx-ui#426]
After installing and running, I can not login.
There is no option to reset the password

**Comment by 0xJacky** [comment]
If you install nginx-ui via [installation script for Linux](https://github.com/0xJacky/nginx-ui#script-for-linux), you can maually remove the app.ini and database.db in /usr/local/etc/nginx-ui, and then restart nginx ui by using `systemctl restart nginx-ui`. Finally, visit ip:port/install in your browser to reinstall nginx-ui, this can reset password.
