### ISSUE TITLE
建议在一个WEB控制台管理多个环境

### ISSUE THREAD

**Issue by linux-L** [0xJacky/nginx-ui#427]
建议在同一个UI控制台管理配置多个环境的NGINX，可以切换环境管理对应NGINX服务器。多个环境可以只启动一个WEB管理后台，其他环境则关掉WEB访问

**Comment by 0xJacky** [comment]
你好，现在这个功能已经有了，在环境中添加另一节点既可。如需关闭 WEB 访问，请使用 ufw 或者云服务器中的安全组，限制可访问的 ip 地址。
