### ISSUE TITLE
Unable to generate TLS certificates, app just hangs

### ISSUE THREAD

**Issue by saheljalal** [0xJacky/nginx-ui#434]
**Describe the bug**
Trying to add TLS certificates after enabling and toggling "Encrypt website with Let's Encrypt" causes the web app to hang. I built this from the source and saw this error repeatedly in the logs regarding web sockets:
```
2024-07-05 14:35:27	ERROR	certificate/issue.go:60	websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
```

**To Reproduce**
1. Go to Sites List
2. Click on modify on a site
3. Toggle Enable TLS (click OK)
4. Toggle Encrypt website with Let's Encrypt (choose either HTTP or DNS)
5. Click Next
6. Observe issue

**Expected behavior**
This should handle getting certs automatically without any issues.

**Screenshots**
<img width="600" alt="Screenshot 2024-07-05 at 2 46 55 PM" src="https://github.com/0xJacky/nginx-ui/assets/1617586/cafcd122-eac3-4755-8413-cd8532002086">
<img width="600" alt="Screenshot 2024-07-05 at 2 46 46 PM" src="https://github.com/0xJacky/nginx-ui/assets/1617586/87df84c3-0909-43af-811c-79d1967e6738">

**Info (please complete the following information):**
 - Server OS: MacOS Sonoma
 - Server Arch: x86
 - Nginx UI Version: latest from source
 - Your Browser: Arc

**Additional context**

**Comment by 0xJacky** [comment]
Hi @saheljalal, did you run nginx-ui behind a reverse proxy?

**Comment by saheljalal** [comment]
Yes @0xJacky , my setup is as follows:
- Unifi Gateway with port forwarding for 80,443 to IP w/Nginx
- Nginx running using brew services
- Nginx-UI running separately on same machine built from source

**Comment by 0xJacky** [comment]
To enable Nginx to proxy WebSocket connections, refer to the detailed guide available at [Nginx Proxy Example](https://nginxui.com/guide/nginx-proxy-example.html).
