### ISSUE TITLE
[Feature] 建议更换nginx为openresty

### ISSUE THREAD

**Issue by hsy-design** [0xJacky/nginx-ui#435]
https://github.com/0xJacky/nginx-ui/blob/dev/Dockerfile引用
而https://github.com/0xJacky/uozi-docker/blob/master/nginx-ui-base/Dockerfile
引用的是nginx:latest
从功能性角度出发 更换nginx为openresty（相当于nginx+lua模块）会更好些 并不会影响原有功能
如果觉得更换不好 引入新的cicd步骤也不错
如果接受此建议 我可以进行相关修改然后发送合并请求

**Comment by 0xJacky** [comment]
@hsy-design 感谢你的建议。
关于你提出的更换 Nginx 为 Openresty 的建议，我有几点需要说明。

首先，Nginx UI 之所以叫 Nginx UI，是因为它主要是为了适配 Nginx，而非其他 Nginx 的分支项目如 Tengine、OpenResty 等，而且现在项目使用 Docker 部署的用户已经很多，强迫其他人更换到其中的一个分支项目是不公平的。

虽然 Nginx UI 并不是只能在 Nginx 上使用，一些其他的开源分支也可以正常使用，但由于精力有限，我们没有办法去针对 Nginx 的其他分支项目进行优化，因此无法保证其兼容性。

实际上，Nginx UI 目前的代码解析器对 Lua 的支持并不好，这可能会影响到OpenResty的使用效果。

不过，如果你有这方面的需求，您可以创建自己的 DockerFile 并构建定制版的镜像，当然我们不会对此提供过多的技术支持。

**Comment by hsy-design** [comment]
非常感谢您的回复 与 开源此项目的公益性
这是我打包的基于openresty的nginx-ui 留给有需要的人使用
https://hub.docker.com/r/yiniot/nginx-ui

**Comment by freshgeek** [comment]
> 非常感谢您的回复 与 开源此项目的公益性 这是我打包的基于openresty的nginx-ui 留给有需要的人使用 https://hub.docker.com/r/yiniot/nginx-ui

可以请教一下打包的详细流程吗？
