### ISSUE TITLE
修改证书续期间隔数值报错

### ISSUE THREAD

**Issue by kekylin** [0xJacky/nginx-ui#446]
操作步骤：点击偏好设置——证书续期间隔，将默认数值7改为其他任意数值后，点击保存，弹窗提示错误信息“Cannot read properties of undefined (reading 'getBannedIPs')”。

部署方式：docker compose
部署参数：
services:
    nginx-ui:
        stdin_open: true
        tty: true
        container_name: nginx-ui
        restart: always
        network_mode: host
        environment:
            - TZ=Asia/Shanghai
        volumes:
            - '/opt/docker/nginx-ui/nginx:/etc/nginx'
            - '/opt/docker/nginx-ui/ui:/etc/nginx-ui'
            - '/opt/docker/nginx-ui/logs:/var/log/nginx'
            - '/opt/docker/nginx-ui/www:/var/www'
        image: 'uozi/nginx-ui:latest'

![QQ截图20240722212348](https://github.com/user-attachments/assets/6e324c3c-4ffd-4fb5-9256-6b8e2e23e5b0)

**Comment by 0xJacky** [comment]
已修复，会在 beta.27 发布
