### ISSUE TITLE
Support Azure OpenAI

### ISSUE THREAD

**Issue by aldinokemal** [0xJacky/nginx-ui#475]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I can only use OpenAI's services and there is no support for Azure OpenAI. This limitation restricts my ability to leverage Azure's infrastructure and offerings alongside OpenAI's capabilities.

**Describe the solution you'd like**
I would like the development team to add support for Azure OpenAI. This would enable users to seamlessly integrate and utilize Azure's OpenAI services within the project, providing more flexibility and options for deployment and management.

**Describe alternatives you've considered**
An alternative solution would be to manually integrate Azure OpenAI using custom scripts or middleware. However, this approach is more complex and less efficient compared to having native support within the project.

**Additional context**
Supporting Azure OpenAI would allow users who are already invested in Azure's ecosystem to better integrate their services. It would also expand the project's versatility and appeal to a broader user base.

**Comment by 0xJacky** [comment]
Added in [bd395e3](https://github.com/0xJacky/nginx-ui/commit/bd395e3c3233170fe02aad24a0c23201f07abfa3), will be released with v2.0.0-beta.42.
