### ISSUE TITLE
手动更新证书报错

### ISSUE THREAD

**Issue by jearton** [0xJacky/nginx-ui#487]
2.0.0-beta.30

![image](https://github.com/user-attachments/assets/0e666da9-9a96-4d04-9382-74922d14a8ef)

点击更新证书按钮，日志里显示没有找到 dns01。我这是在内网里用的nginx，公网肯定访问不到这个域名的

**Comment by 0xJacky** [comment]
是的，使用DNS挑战需要域名能被公网访问，这不是 bug

**Comment by 0xJacky** [comment]
不幸的是，Let's Encrypt 需要一个公共 DNS 记录来验证域和颁发证书，如果您需要在内部网络中签名证书，您可能需要考虑https://github.com/letsencrypt/boulder 并使用您自己部署的 Boulder 作为 CA 在 Nginx UI 中创建一个 ACME 用户。

**Comment by jearton** [comment]
不是，我的DNS是走公网的。你仔细看右边的日志，我左边设置的是 DNS 挑战，然后右边的日志里表明出来实际使用的是 HTTP 挑战。也就是说，点击更新证书按钮后，使用的挑战方法不是我选的 DNS01，而是HTTP01，这个算不算bug

**Comment by 0xJacky** [comment]
重新申请一下试试，我这没法复现
