### ISSUE TITLE
能否增加证书下载功能？

### ISSUE THREAD

**Issue by jearton** [0xJacky/nginx-ui#488]
我每过一段时间，就需要把证书下载下来，手动上传到阿里云的证书管理后台上，用于CDN域名开启HTTPS。

如果能直接集成阿里云的这个API，每次续签后自动往阿里云同步，那就更好了。

![image](https://github.com/user-attachments/assets/82f186f4-6d8e-4fd4-a4c7-f66d0d9d4163)

**Comment by 0xJacky** [comment]
可以用这个项目 https://github.com/0xJacky/cdn_cert

**Comment by jearton** [comment]
@0xJacky 这一步跑不通，镜像找不到

![image](https://github.com/user-attachments/assets/2029d778-25e2-4ee9-bbf1-7e34b93de835)

![image](https://github.com/user-attachments/assets/faaec718-c381-4776-8324-26e7612fa435)

**Comment by 0xJacky** [comment]
已更新 Readme.md 镜像是 uozi/cdn_cert
