### ISSUE TITLE
建议必填项添加*标识与选填项区分开来

### ISSUE THREAD

**Issue by kekylin** [0xJacky/nginx-ui#505]
如题所示，希望能在所有必须填写内容或者选择内容的地方，必填项添加*标识，谢谢！
![QQ截图20240814214845](https://github.com/user-attachments/assets/67594228-85de-4639-ba5e-5a566bb88735)

**Comment by 0xJacky** [comment]
抱歉，这些配置都是直接从 lego 里下载来的，lego 本身不提供必选项和非必选的区分，因此我无法实现这个需求，感谢你的建议。

Sorry, these configurations are directly downloaded from lego. lego itself does not provide the distinction between required options and optional options, so I cannot realize this requirement. Thank you for your advice.
