### ISSUE TITLE
证书获取失败

### ISSUE THREAD

**Issue by ftyszyx** [0xJacky/nginx-ui#506]
![image](https://github.com/user-attachments/assets/fe938395-b80a-43a2-ba66-ba6aadb5f67e)

**Comment by 0xJacky** [comment]
这个站点有 /.well-known 的反代规则吗，如果没有的话手动添加一下
<img width="1187" alt="截屏2024-08-15 上午10 29 14" src="https://github.com/user-attachments/assets/6ec171a3-a501-4ba0-b8a5-8f88525359ed">

**Comment by ftyszyx** [comment]
@0xJacky 感谢，可以了！
