### ISSUE TITLE
集群第一次同步配置文件可以，第二次修改配置覆盖出现406

### ISSUE THREAD

**Issue by seven54** [0xJacky/nginx-ui#508]
错误如下：同步配置错误
同步配置 config_name 到 test30 失败，响应：{"message":"File exists"}

![image](https://github.com/user-attachments/assets/b1f9fa8c-0e0c-4a71-927a-cacc13029cec)

![image](https://github.com/user-attachments/assets/949e991d-b99f-4f5d-bdbd-f636a7791555)

![image](https://github.com/user-attachments/assets/4acb9003-7a89-4e36-85c1-29afd1ab76b7)

**Comment by 0xJacky** [comment]
感谢反馈，我确认一下，您是已经勾选了覆盖操作吗

<img width="257" alt="image" src="https://github.com/user-attachments/assets/f6a96dad-2c8f-4eb1-ae11-432b111bd93c">

**Comment by seven54** [comment]
![image](https://github.com/user-attachments/assets/8584d73e-19bc-4a4d-8ae5-35116bb0fe82)
  有选择。

**Comment by 0xJacky** [comment]
好的，修复好会通知

**Comment by 0xJacky** [comment]
已在 v2.0.0-beta.31 中修复，请更新主节点和其他节点上的 Nginx UI。

**Comment by seven54** [comment]
同步问题是修复了，但是现在又出现了另一个问题。每次同步操作，要强制ctrl + F5强制刷新才有用。否则一直默认第一次的勾选操作。
