### ISSUE TITLE
关于证书管理的建议

### ISSUE THREAD

**Issue by AC-0308** [0xJacky/nginx-ui#52]
# 关于证书管理的建议

建议借鉴宝塔面板的证书夹功能，单独列一个模块来管理已经申领的证书(同一个域名常使用泛域名证书)，以便在不同的站点快速应用既有的证书，避免反复申请导致的资源浪费

联动issue[关于非80端口下，Let's Encrypt功能的补充建议 #51](https://github.com/0xJacky/nginx-ui/issues/51)

**Comment by 0xJacky** [comment]
过几天看看，这几天羊了😓

**Comment by AC-0308** [comment]
> 过几天看看，这几天羊了😓

嗯嗯，保重身体
