### ISSUE TITLE
为项目后端配置反向代理时，静态文件和 API 请求无法正确转发

### ISSUE THREAD

**Issue by Yi-Xio** [0xJacky/nginx-ui#520]
**Is your feature request related to a problem? Please describe.**
我希望配置通过域名（如 https://example.com/nginxui ）访问服务,我为此配置了反向代理
```
location /nginxui {
        proxy_pass http://127.0.0.1:9000/;
    }
```
但这样做的话，许多静态文件和 API 请求无法正确转发到后端服务器。这导致呈现空白页，功能无法正常使用。
我也尝试将静态文件的 `/assets/` 路径 和 `/api/` 路径配置转发至 `http://127.0.0.1:9000` 的对应路径，但我觉得这样可能存在某些潜在的问题，且似乎有些“不优雅”。
我查阅了项目文档，并没有找到相关说明。如果该功能已实现，烦请告知如何操作。

**Describe the solution you'd like**
我希望项目能够支持通过自定义子路径进行反向代理访问。例如，在 Nginx 中配置 /nginxui 作为子路径，能让所有相关请求（包括静态文件和 API 请求）正确转发到后端。

**Describe alternatives you've considered**
目前我尝试过使用不同的 Nginx 反向代理配置，然而问题依然存在。我认为项目需要内置对自定义子路径的支持，或者提供一个更清晰的指导来帮助用户解决这一问题。

**Additional context**
`Nginx-UI` 是非常优秀的项目，感谢作者大大的付出！

**Comment by 0xJacky** [comment]
Hi, 您的部署方式是脚本部署，还是 docker？

**Comment by 0xJacky** [comment]
我们之前针对这种情况做过调整了 https://github.com/0xJacky/nginx-ui/issues/68

只需要改成 location /nginxui/ （后面加个 / ）就可以正常使用，对了，记得配置 WebSocket 相关。

Example:
```
map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}
server {
    listen 80;
    listen [::]:80;
    server_name <ip>;
    location /nginx-ui/ {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_pass http://127.0.0.1:9000/;
    }
}
```

**Comment by steveepreston** [comment]
@0xJacky Thank you. Worked for me!
Can you please write a sample without `map $http_upgrade $connection_upgrade {}` block?

**Comment by 0xJacky** [comment]
> @0xJacky Thank you. Worked for me!
> 
> Can you please write a sample without `map $http_upgrade $connection_upgrade {}` block?

Sorry I can't, we need this block to set up a condition where a normal HTTP request will not upgrade to a WebSocket connection.

**Comment by steveepreston** [comment]
@0xJacky I tested this and seems everything works:

```nginx
    location /nginx-ui/ {
        proxy_pass http://127.0.0.1:9000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
```

The line `proxy_set_header Connection "upgrade";` sets the Connection header to "upgrade" for all requests. However, normal HTTP requests typically do not include the Upgrade header, so they will not trigger a WebSocket handshake. This means that the `Connection: upgrade` header will not affect normal HTTP requests, as they won't initiate a WebSocket connection without the corresponding Upgrade header.
