### ISSUE TITLE
The new configuration file was created with an incorrect path

### ISSUE THREAD

**Issue by ttrinh24** [0xJacky/nginx-ui#521]
**Describe the bug**
The config file was created correctly inside the folder (`/etc/nginx/<folder>/<new-file>`), but the subfolder path is incorrect (`/etc/nginx/<folder>/<subfolder>/<new-file>`).

**To Reproduce**

1. Click on 'Manage Configs' menu
2. Click on 'Modify' at folder conf.d 
3. Click on 'Modify' at folder includes
5. Click on 'Create File'
6. See error

**Expected behavior**
The file was created with the correct path

**Screenshots**
![image](https://github.com/user-attachments/assets/88f94052-494f-4c77-baaa-0f7894b23372)
![image](https://github.com/user-attachments/assets/fa5c72b0-81b9-4dd0-a86f-c76b0e3b2599)

**Info (please complete the following information):**
 - Server OS: Debian 12.6
 - Server Arch: linux 5.15.0-117-generic x86_64
 - Nginx UI Version: [v2.0.0-beta.31](https://github.com/0xJacky/nginx-ui/releases/tag/v2.0.0-beta.31)
 - Browser: Chrome

**Comment by 0xJacky** [comment]
Thanks for your report, I will fix it soon.
