### ISSUE TITLE
opentelemetry support

### ISSUE THREAD

**Issue by holmofy** [0xJacky/nginx-ui#529]
**Is your feature request related to a problem? Please describe.**
Opentelemetry supports link tracking for troubleshooting.

**Describe the solution you'd like**

Currently, both opentelemetry and nginx have officially released related plug-ins.
* [opentelemetry-nginx](https://github.com/open-telemetry/opentelemetry-cpp-contrib/tree/main/instrumentation/nginx)
* [nginx-otel](https://github.com/nginxinc/nginx-otel)

[I tried it myself](https://github.com/holmofy/otel-full). Although the nginx-otel provided by nginx has high performance, its functions are still relatively simple. The plug-in provided by opentelemetry has relatively complete functions. I hope this plug-in can be integrated into nginx-ui.

**Comment by 0xJacky** [comment]
Sorry, we have no plan to implement this.
