### ISSUE TITLE
Is the session broken now?

### ISSUE THREAD

**Issue by tamr** [0xJacky/nginx-ui#530]
Some versions ago I noticed being welcomed by "Authorization failed" message on the login screen. I see the secure_session_id cookie has the value of "undefined". Previously the session worked just fine even after upgrades.

**Comment by 0xJacky** [comment]
Hi @tamr，did you enable 2FA?

**Comment by tamr** [comment]
> Hi @tamr，did you enable 2FA?

Nope, I have restricted it by ip with deny all. I think it started to ask for the login 2 updates ago.

**Comment by 0xJacky** [comment]
Do you mean you have configured IP access restrictions for the Nginx UI in your Nginx configurations?

**Comment by 0xJacky** [comment]
The "Authorization failed" message displayed on the login screen is not a bug. When the JWT expires (currently after 24 hours), you will be prompted with "Authorization failed" and asked to log in again.
