### ISSUE TITLE
[Bug] 终端页面, 提示"连接中断，请刷新页面。"

### ISSUE THREAD

**Issue by zuilintan** [0xJacky/nginx-ui#537]
**Describe the bug**
进入终端页面, 提示"连接中断，请刷新页面。", 但刷新也是无效的, 
此时systemctl status nginx-ui -l报错信息如下截图(很抱歉, 我没有找到咱们nginx-ui自身的日志文件)

**To Reproduce**
以在线升级的方式, 升级到v2.0.0-beta.32后, 
进去终端页面, 
问题必现

**Expected behavior**
正常显示终端

**Screenshots**
![QQ_1725327506645](https://github.com/user-attachments/assets/e0c84ba7-03d1-4566-9a4f-c51f252b0901)
![image](https://github.com/user-attachments/assets/bd2708c8-bd0f-4097-80ad-fea9bb8b0466)

**Info (please complete the following information):**
 - Server OS: CentOS 7
 - Server Arch: X86_64
 - Nginx UI Version: 2.0.0-beta.32
 - Your Browser: Chrome

**Additional context**
None

**Comment by 0xJacky** [comment]
之前是从哪个版本升级上来的？因为最近一次更新 pty 依赖是 3 星期前

**Comment by 0xJacky** [comment]
去年的时候也有用户反馈过这个问题，但是在我这边无法复现：https://github.com/0xJacky/nginx-ui/issues/54

**Comment by 0xJacky** [comment]
至少 beta.24 开始这个功能好像就不可用了

**Comment by zuilintan** [comment]
> 之前是从哪个版本升级上来的？因为最近一次更新 pty 依赖是 3 周前

很遗憾, 具体版本号我没有印象了, 
不过应该是在2.0.0-beta.26或更早之前

**Comment by 0xJacky** [comment]
是的这个应该是老问题了，目前我在 debian 和 Ubuntu （内核 5.x）都是正常使用的
https://github.com/creack/pty/issues/21

**Comment by 0xJacky** [comment]
所以很抱歉这个问题大概率我没法解决

**Comment by zuilintan** [comment]
通过数据库查询, 我可确认版本是从2.0.0-beta.25-patch.1升级上来: 
![QQ_1725332632673](https://github.com/user-attachments/assets/1041c3cc-7dde-4b1c-8ae2-491bbe5c1b9f)
![QQ_1725332764855](https://github.com/user-attachments/assets/413b321b-da05-433b-a902-2811caaceafd)

**Comment by zuilintan** [comment]
> 所以很抱歉这个问题大概率我没法解决

好的, 这的确是个很复杂且无头绪的问题, 
后面我会尝试重新安装

**Comment by zuilintan** [comment]
对了, 补充一下: 
我这台主机, 手动更新过python版本, 
从2.x->3.12

**Comment by 0xJacky** [comment]
如果可以的话建议更新一下操作系统 centos7 上个月已经 EOL 了

**Comment by zuilintan** [comment]
问题已定位：
我的ngiuxUI web端使用了nginx反代，不需要端口9000访问，
故将端口移出了防火墙白名单，

而**终端似乎依赖9000**

对策：
9000加入防火墙白名单

**Comment by 0xJacky** [comment]
错误的，9000 端口如果在 nginx 反向代理后面，是不需要暴露到防火墙外的

**Comment by SuJack** [comment]
修改下配置文件：

/usr/local/etc/nginx-ui/app.ini


![Image](https://github.com/user-attachments/assets/0add7096-2fbc-4d0f-96ca-fceb4ca5f3e6)

然后重新启动一下， 看看是否可以解决

ps:
[terminal]
StartCmd = bash    我把login改成bash 就好了
