### ISSUE TITLE
update docker examples

### ISSUE THREAD

**Issue by Karlostavitch1** [0xJacky/nginx-ui#538]
docker examples on readme and in nginx documentation reference ports 8080 and 8443 but current docker image is using 80 and 443.

small issue but harder for newbies like me to get started.

**Comment by 0xJacky** [comment]
Hi @Karlostavitch1,

Below is the command of staring nginx-ui docker copy from our documentation:
```
docker run -dit \
  --name=nginx-ui \
  --restart=always \
  -e TZ=Asia/Shanghai \
  -v /mnt/user/appdata/nginx:/etc/nginx \
  -v /mnt/user/appdata/nginx-ui:/etc/nginx-ui \
  -p 8080:80 -p 8443:443 \
  uozi/nginx-ui:latest
```

In this example, we map the host ports (8080,8443) to the ports (80,443) of the container.  Howerver, you can use another host ports you want.

You can check the documentation of Docker about how to publish ports:
<img width="784" alt="image" src="https://github.com/user-attachments/assets/e174258b-5679-46d0-ab00-a9da2e25c2c0">

https://docs.docker.com/engine/network/#published-ports

Thus, I don't think there is a problem in our documentation.

Regards,
Jacky

**Comment by Karlostavitch1** [comment]
my bad, I was writing a docker compose and must have had a dislexic moment and was putting them in the wrong order and couldn't fix it until I changed it to 80:80 and 443:443 not realising that I just had the order of operation reversed.
