### ISSUE TITLE
 nginx-ui: Error ReadPtyAndWriteWs read pty: read /dev/ptmx: input/output error

### ISSUE THREAD

**Issue by alokispandey** [0xJacky/nginx-ui#54]
Hi,
I am running ngix-ui  on redhat 8 and can access all of the feature offer over GUI, except "terminal". when i click to access terminal, i am getting below Error
 

> nginx-ui: Error ReadPtyAndWriteWs read pty: read /dev/ptmx: input/output error

I tried basic troubleshooting including disabling selinux, but no luck. Please suggest how to proceed next..!

**Comment by 0xJacky** [comment]
Today, I installed the RedHat 8.5 on a virtual machine, and then installed nginx-ui v1.8.4 on it. In my environment, I can use terminal in WebUI.

It seems like a kernal issue, please check this topic for more informations. https://github.com/creack/pty/issues/21#issuecomment-39067752
