### ISSUE TITLE
API endpoint to add site

### ISSUE THREAD

**Issue by opeoniye** [0xJacky/nginx-ui#540]
**Is your feature request related to a problem? Please describe.**
I love the nginx-ui dashboard but I need to also be able to create/add/delete new sites via api calls.

**Describe the solution you'd like**
Provide a rest api endpoint to call to add site, delete site with the ability to pass nginx config template.

**Describe alternatives you've considered**

**Additional context**

**Comment by 0xJacky** [comment]
https://github.com/0xJacky/nginx-ui/blob/dev/api/sites/router.go

Currently, the Nginx UI API follows a RESTful design but lacks formal documentation. As the project is still in its beta phase, the API endpoints and their parameters are subject to change, so we don't have immediate plans to publish detailed documentation at this time.

However, you can explore the API request parameters by inspecting the network requests in your browser's developer tools.

Thank you for your suggestion!

**Comment by opeoniye** [comment]
Thank you very much @0xJacky
