### ISSUE TITLE
Multi Node Environment, sites not getting enabled on deploy.

### ISSUE THREAD

**Issue by xXleowXx** [0xJacky/nginx-ui#541]
**Describe the bug**
In multi node Environment when creating/updating site and deploying to nodes with function Enable selected. The configuration is not getting enabled in the nodes. You have to manually connect to nodes and enable the site configuration.

**To Reproduce**
1. Install 2 or more Nginx UI nodes
2. Add nodes to Master Nginx UI panel
3. Add new site, any configuration.
4. Go to modify in site list
5. Select Nodes you want to deploy to and select Enabled checkbox

**Expected behavior**
Site is getting deployed to nodes and being Enabled

**Info (please complete the following information):**
 - Server OS: Ubuntu 24.04
 - Nginx UI Version: 2.0.0-beta.32
 - Your Browser: Chrome, Edge

**Comment by 0xJacky** [comment]
Thanks for your report, I will fix later this week.
