### ISSUE TITLE
添加 TOTP 时，二维码变化太快以至于添加比较困难

### ISSUE THREAD

**Issue by oneisall8955** [0xJacky/nginx-ui#551]
版本：2.0.0-beta.32
![image](https://github.com/user-attachments/assets/c6961412-6b3d-4035-aa60-8e8126e065e5)

开启 TOTP 时候，30s 内没添加，二维码会重新刷新。对于习惯使用 bitwarden 来管理 TOTP 考验手速。
操作流程如下：
1. 先将二维码 使用截图软件OCR提取出链接如：otpauth://totp/Nginx%20UI:xxx?algorithm=SHA1&digits=6&issuer=Nginx%20UI&period=30&secret=SQWVRMIOHARYH237CMCUFFG6F4FXXXX。
2. 将secret复制到验证器密钥中
![image](https://github.com/user-attachments/assets/71a75afb-e4a2-4a7f-bcc0-ec4b69c7a880)
3. 复制生成的TOTP
![image](https://github.com/user-attachments/assets/ff7e4cb6-0ae6-43e9-a03d-ae5e7c657b33)
4. 粘贴到验证码框
![image](https://github.com/user-attachments/assets/fdcf1783-95ce-4133-9244-5d9444585542)

往往粘贴校验的时候，整个操作都已经超过 30s，导致重新加载了二维码，所以验证码校验失败，最终开启两步登录失败。

当然，使用手机  Microsoft Authenticator 当然可以添加成功，但是这类 app 无法导出密钥，无法添加到 bitwarden 插件中。

建议延长时间或者新增通用的解决办法：新增一个选项，直接显示为密钥，用户复制密钥到 bitwarden，省去 OCR 过程，这样 30s 内还是够手速的

**Comment by oneisall8955** [comment]
建议新增这种逻辑：
![image](https://github.com/user-attachments/assets/c0af3a2c-c055-4d07-a965-952155f08305)

![image](https://github.com/user-attachments/assets/6c6af78a-0e45-4c9e-a690-45f1bb0d314b)

![image](https://github.com/user-attachments/assets/8a61a730-2c22-441a-8c0e-2a90e080479f)

**Comment by 0xJacky** [comment]
是的，我也是这样想的，等有空了看看

**Comment by 0xJacky** [comment]
因为这是 TOTP 的性质决定的，每个验证码有效期只有 30s
