### ISSUE TITLE
是否支持自己手动添加dns域名解析

### ISSUE THREAD

**Issue by stylesmile** [0xJacky/nginx-ui#563]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 0xJacky** [comment]
不支持

**Comment by stylesmile** [comment]
后续考虑加嘛，这样支持所有运营商，刚刚我加了godaddy的密钥，加了好几次，申请证书都不成功

**Comment by 0xJacky** [comment]
具体是 DNS 验证超时还是其他原因？请提供一下日志，这个手动添加是做不到的，抱歉。

**Comment by stylesmile** [comment]
2024/09/17 10:22:09 [INFO] [Nginx UI] 正在重载 Nginx

obtain certificate error: error: one or more domains had a problem: [*.fcbalancer.com] [*.fcbalancer.com] acme: error presenting token: godaddy: failed to get TXT records: unexpected status code: [status code: 401] body: {"code":"UNABLE_TO_AUTHENTICATE","message":"Unauthorized : Could not authenticate API key/secret"} [fcbalancer.com] [fcbalancer.com] acme: error presenting token: godaddy: failed to get TXT records: unexpected status code: [status code: 401] body: {"code":"UNABLE_TO_AUTHENTICATE","message":"Unauthorized : Could not authenticate API key/secret"}

**Comment by stylesmile** [comment]
2024/09/17 10:22:09 [INFO] [Nginx UI] 正在重载 Nginx

obtain certificate error: error: one or more domains had a problem: [*.xxx.com] [*.xxx.com] acme: error presenting token: godaddy: failed to get TXT records: unexpected status code: [status code: 401] body: {"code":"UNABLE_TO_AUTHENTICATE","message":"Unauthorized : Could not authenticate API key/secret"} [xxx.com] [xxx.com] acme: error presenting token: godaddy: failed to get TXT records: unexpected status code: [status code: 401] body: {"code":"UNABLE_TO_AUTHENTICATE","message":"Unauthorized : Could not authenticate API key/secret"}

**Comment by 0xJacky** [comment]
GODADDY_API_KEY

GODADDY_API_SECRET

这两个正确配置了吗，看错误日志是 godaddy 提示认证失败
