### ISSUE TITLE
[Bug] 通过 snippets  方式配置的证书，无法在 导入 时，被Nginx-UI识别

### ISSUE THREAD

**Issue by zuilintan** [0xJacky/nginx-ui#564]
**Describe the bug**
通过 `snippets ` 方式配置的证书，无法在 导入 时，被Nginx-UI识别

**Screenshots**
![QQ_1726620864088](https://github.com/user-attachments/assets/95c10dfb-7746-49df-8a98-eb0e442c5c67)
![QQ_1726620846273](https://github.com/user-attachments/assets/8916fb0f-bb93-41b3-a4df-fca2a1e70437)
![QQ_1726620786637](https://github.com/user-attachments/assets/b222df16-ba2b-4ad6-bed9-eeb6e9e2d49e)
![QQ_1726620827324](https://github.com/user-attachments/assets/fcaeb0d0-b366-4222-b66f-d821d3a40a44)

**Info (please complete the following information):**
 - Nginx UI Version: v2.0.0-beta.32

**Comment by 0xJacky** [comment]
你好，这个不是 bug，为了避免在 Nginx UI 内出现越权行为，我们的程序禁止访问 nginx 配置目录以外的目录，所以对于这种情况，您可以考虑使用软连接或者修改证书目录，谢谢。

**Comment by zuilintan** [comment]
> 你好，这个不是 bug，为了避免在 Nginx UI 内出现越权行为，我们的程序禁止访问 nginx 配置目录以外的目录，所以对于这种情况，您可以考虑使用软连接或者修改证书目录，谢谢。

Good Idea, It works for me

![image](https://github.com/user-attachments/assets/1feec47b-6b9a-4f74-9905-f4f2dc952eba)
