### ISSUE TITLE
请问有权限管理功能吗？

### ISSUE THREAD

**Issue by GuoFlight** [0xJacky/nginx-ui#565]
我发现新增的用户，也能继续新增用户，看起来权限很大，好像没有权限管理的功能？

**Comment by 0xJacky** [comment]
您好，暂时没有这个功能

**Comment by GuoFlight** [comment]
好的，谢谢~

**Comment by Hintay** [comment]
如果对权限管理有任何想法，欢迎在 https://github.com/0xJacky/nginx-ui/discussions/397 中进行讨论。
