### ISSUE TITLE
腾讯云账号无法申请SSL证书

### ISSUE THREAD

**Issue by dingdian** [0xJacky/nginx-ui#566]
我使用docker不部署的nginx-ui, 申请证书的时候总是报错：
![image](https://github.com/user-attachments/assets/9b50d097-e20a-46e6-9b29-1365627e57a6)

同样的id和key放到nginx proxy manager中是可以正常的申请到对应证书

**Comment by 0xJacky** [comment]
你好，我也是用的 腾讯云 dnspod，你的提供商选择的是 Tencent Cloud DNS 吗

**Comment by 0xJacky** [comment]
不能选 DNSPod，要选 Tencent Cloud DNS

**Comment by dingdian** [comment]
我选的是Tencent Cloud DNS，相关的id和key也确认是可以使用的，很奇怪

**Comment by 0xJacky** [comment]
试下勾选 「Lego 禁用 CNAME 支持」

**Comment by dingdian** [comment]
一样的报错：


正在获取证书，请稍等...

2024/09/23 11:37:07 [INFO] [Nginx UI] 正在准备 Lego 的配置

2024/09/23 11:37:07 [INFO] [Nginx UI] ACME User: ssl, Email: xxxxxx@foxmail.com, CA Dir: https://acme-v02.api.letsencrypt.org/directory

2024/09/23 11:37:07 [INFO] [Nginx UI] 正在创建客户端用于与 CA 服务器通信

2024/09/23 11:37:07 [INFO] [Nginx UI] 使用 DNS01 Challenge 提供商

2024/09/23 11:37:07 [INFO] [Nginx UI] 正在设置环境变量

2024/09/23 11:37:07 [INFO] [Nginx UI] 正在获取证书

2024/09/23 11:37:07 [INFO] [*.xxxxxxxx.net, xxxxxxxx.net] acme: Obtaining bundled SAN certificate

2024/09/23 11:37:09 [INFO] [*.xxxxxxxx.net] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/407217170206

2024/09/23 11:37:09 [INFO] [xxxxxxxx.net] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/407217170216

2024/09/23 11:37:09 [INFO] [*.xxxxxxxx.net] acme: use dns-01 solver

2024/09/23 11:37:09 [INFO] [xxxxxxxx.net] acme: Could not find solver for: tls-alpn-01

2024/09/23 11:37:09 [INFO] [xxxxxxxx.net] acme: Could not find solver for: http-01

2024/09/23 11:37:09 [INFO] [xxxxxxxx.net] acme: use dns-01 solver

2024/09/23 11:37:09 [INFO] [*.xxxxxxxx.net] acme: Preparing to solve DNS-01

2024/09/23 11:37:10 [INFO] [xxxxxxxx.net] acme: Preparing to solve DNS-01

2024/09/23 11:37:10 [INFO] [*.xxxxxxxx.net] acme: Cleaning DNS-01 challenge

2024/09/23 11:37:11 [WARN] [*.xxxxxxxx.net] acme: cleaning up failed: tencentcloud: failed to get hosted zone: zone net. not found in dnspod for domain _acme-challenge.xxxxxxxx.net.

2024/09/23 11:37:11 [INFO] [xxxxxxxx.net] acme: Cleaning DNS-01 challenge

2024/09/23 11:37:11 [WARN] [xxxxxxxx.net] acme: cleaning up failed: tencentcloud: failed to get hosted zone: zone net. not found in dnspod for domain _acme-challenge.xxxxxxxx.net.

2024/09/23 11:37:12 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/407217170206

2024/09/23 11:37:12 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/407217170216

2024/09/23 11:37:13 [INFO] [Nginx UI] 正在重载 Nginx

2024/09/23 11:37:13 [INFO] [Nginx UI] 完成

obtain certificate error: error: one or more domains had a problem: [*.xxxxxxxx.net] [*.xxxxxxxx.net] acme: error presenting token: tencentcloud: failed to get hosted zone: zone net. not found in dnspod for domain _acme-challenge.xxxxxxxx.net. [xxxxxxxx.net] [xxxxxxxx.net] acme: error presenting token: tencentcloud: failed to get hosted zone: zone net. not found in dnspod for domain _acme-challenge.xxxxxxxx.net.

**Comment by 0xJacky** [comment]
可以等晚点或者明天试试，有可能是腾讯的问题，之前我也遇到过

**Comment by dingdian** [comment]
好吧

**Comment by Howardnm** [comment]
我单独用acme.sh是可以申请到的（用的是dns验证方法申请下来Let’s Encrypt的证书），他需要填ID和token。nginx-ui的dnspod只看到可以填写DNSPOD_API_KEY，而填不了ID。

**Comment by 0xJacky** [comment]
选用 Tencent Cloud DNS
