### ISSUE TITLE
如何配置IP地址+端口号的反向代理？

### ISSUE THREAD

**Issue by chung1912** [0xJacky/nginx-ui#575]
内网地址的ip:port形式如何在ui里面配置？
比如：
https://192.168.1.11:1443
https://192.168.1.11:2443
https://192.168.1.11:3443
这些端口对应不同的服务，并且不是域名，是同一个IP地址
用原生nginx是分别映射多个端口，然后nginx配置文件的直接分别配置
UI里面怎么配置这种？并且和域名的反代分开独立管理

**Comment by 0xJacky** [comment]
新建多个 server 也可以

**Comment by chung1912** [comment]
> 新建多个 server 也可以

没太明白什么意思，需要部署多个nginx-ui？ 是否可以一个nginx-ui，映射多个端口来设置？

**Comment by 0xJacky** [comment]
<img width="851" alt="image" src="https://github.com/user-attachments/assets/c1793431-12e1-4b5a-950b-a1d9695cf4e1">
添加多个 Server，每个 server 监听不同的端口比如 1443,2443,3443， 然后每个 server 分别配置反向代理的后端就可以了吧
