### ISSUE TITLE
增加mysql数据库的支持

### ISSUE THREAD

**Issue by chung1912** [0xJacky/nginx-ui#576]
希望增加mysql数据库的支持

**Comment by 0xJacky** [comment]
现在 sqlite 有遇到什么瓶颈吗

**Comment by chung1912** [comment]
> 现在 sqlite 有遇到什么瓶颈吗

没有什么瓶颈，但是sqlite管理不太方便，而且无密

**Comment by 0xJacky** [comment]
当前我们的工作重心在维护基于 Sqlite 的版本，我们欢迎 PR，让 Nginx UI 变得更强。
