### ISSUE TITLE
请问自己签发的通配符域名和添加站点勾选证书有什么区别？

### ISSUE THREAD

**Issue by chung1912** [0xJacky/nginx-ui#580]
Let's Encrypt有两种方式添加：
1、在证书列表预先添加通配符证书（会显示托管证书），然后添加站点的时候选择这个证书
2、在添加站点的时候直接选中Let's Encrypt证书加密，此时会创建一个普通证书，并且提示会自动更新
![image](https://github.com/user-attachments/assets/f0d90736-4bdf-4a9d-87e3-2b6c28dd333b)
那么，对于第一种方式创建的托管证书，也可以自动续期更新吗？还是必须第二种方式才支持自动更新？

**Comment by 0xJacky** [comment]
区别在于：通配符证书还是单域名的证书

其他续期的逻辑都是一样的
