### ISSUE TITLE
是否会有一个windows平台的版本？

### ISSUE THREAD

**Issue by Nu1i** [0xJacky/nginx-ui#581]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 0xJacky** [comment]
https://github.com/0xJacky/nginx-ui/issues/337
抱歉，暂时没有这个计划，不过您可以使用 docker 来启动，这样就可以在 Windows 上运行。

**Comment by Hintay** [comment]
如果想要在Windows上本地管理Web环境，推荐使用 [Largon](https://laragon.org/)。
