### ISSUE TITLE
SSL证书支持Zerossl和google或能自定义ACME地址和EAB密钥信息

### ISSUE THREAD

**Issue by fcwys** [0xJacky/nginx-ui#582]
**Is your feature request related to a problem? Please describe.**
SSL证书支持Zerossl和google或能自定义ACME地址和EAB密钥信息，这样会更灵活

**Describe the solution you'd like**
SSL证书支持Zerossl和google或能自定义ACME地址和EAB密钥信息

**Describe alternatives you've considered**

**Additional context**

**Comment by 0xJacky** [comment]
现在已经实现了，只要符合 acme 标准的都可通过创建 ACME User 设置 ca dir，zerossl 那边因为不是标准的 acme 协议，所以不支持

**Comment by fcwys** [comment]
我记得legos支持zerossl的，不知道能不能通过lego支持呢
