### ISSUE TITLE
no such file or directory

### ISSUE THREAD

**Issue by WanaTea** [0xJacky/nginx-ui#583]
脚本安装，正常访问 9000 之后准备配置 NG 提示这个
<img width="969" alt="image" src="https://github.com/user-attachments/assets/7ad2a7f1-9201-4370-b31c-8fa24c1a73ed">
<img width="1579" alt="image" src="https://github.com/user-attachments/assets/62fdad6f-7495-4588-a898-d18b39636b51">

**Comment by 0xJacky** [comment]
您好，请查看文档说明
https://nginxui.com/zh_CN/guide/getting-started.html#%E4%BD%BF%E7%94%A8%E5%89%8D%E6%B3%A8%E6%84%8F
