### ISSUE TITLE
casdoor登录报错

### ISSUE THREAD

**Issue by chung1912** [0xJacky/nginx-ui#584]
2024-09-27 18:32:45	ERROR	user/casdoor.go:52	json: cannot unmarshal object into Go struct field Claims.address of type []string
日志出现这个错误，怎么解决？
另外，环境变量NGINX_UI_CASDOOR_CERTIFICATE的值直接输入证书字符串也太长了，能不能支持读pem文件？直接映射这个文件来读取更方便些

**Comment by 0xJacky** [comment]
参考一下这个配置：https://github.com/0xJacky/nginx-ui/issues/423#issuecomment-2254904566

**Comment by chung1912** [comment]
> 参考一下这个配置：[#423 (comment)](https://github.com/0xJacky/nginx-ui/issues/423#issuecomment-2254904566)
我就是参考你这个配置的，帮忙看下是否有问题呢？dockercompose部署
![image](https://github.com/user-attachments/assets/58b5fad8-4fd4-4eaf-8f63-cd174c261b1a)

**Comment by 0xJacky** [comment]
换行符不能删的吧...，你可以映射配置文件进入容器，不一定用环境变量

**Comment by chung1912** [comment]
> 换行符不能删的吧...，你可以映射配置文件进入容器，不一定用环境变量

保留换行符，问题依旧

**Comment by 0xJacky** [comment]
临时的解决方案就是映射 app.ini 进容器，不使用 env

**Comment by chung1912** [comment]
> 花了点时间复现了一下，env 解析之后会把换行符替换为空格，所以证书就提示损坏了，这个问题是环境变量的锅，我计划在下个版本移除 app.ini 中直接配置证书内容的功能，改为在配置文件中设置证书的路径，到时候，可以直接把证书文件映射到容器内。

是的，直接改为映射下载下来的pem证书文件，这样肯定就好多了

**Comment by 0xJacky** [comment]
已修复，将会在 beta.36 中发布。

**Comment by echoface** [comment]
我这里报错 User not exist； 
```
nginx_lan    | [0.146ms] [rows:0] SELECT * FROM `auths` WHERE `name` = "admin" AND `auths`.`deleted_at` IS NULL ORDER BY `auths`.`id` LIMIT 1
```
sso登录必须要求对应应用要注册一个admin的用户？

配置内容
```
[casdoor]
Endpoint        = https://casdoor.xxxxx.cn
ExternalUrl     = https://casdoor.xxxxx.cn
ClientId        = 2b686xxxxxx6d0
ClientSecret    = e4836e2e666fb86xxxxxxxx5b1209bf6e58914d
CertificatePath = /xxxxxx/xxxxxxx/xxxxx.pem
Organization    = xxorg
Application     = nginxlan
RedirectUri     = `https://nginx.echoface.cn/#/login`
```

@0xJacky @chung1912

**Comment by 0xJacky** [comment]
> 我这里报错 User not exist；
> 
> ```
> nginx_lan    | [0.146ms] [rows:0] SELECT * FROM `auths` WHERE `name` = "admin" AND `auths`.`deleted_at` IS NULL ORDER BY `auths`.`id` LIMIT 1
> ```
> 
> sso登录必须要求对应应用要注册一个admin的用户？
> 
> 配置内容
> 
> ```
> [casdoor]
> Endpoint        = https://casdoor.xxxxx.cn
> ExternalUrl     = https://casdoor.xxxxx.cn
> ClientId        = 2b686xxxxxx6d0
> ClientSecret    = e4836e2e666fb86xxxxxxxx5b1209bf6e58914d
> CertificatePath = /xxxxxx/xxxxxxx/xxxxx.pem
> Organization    = xxorg
> Application     = nginxlan
> RedirectUri     = `https://nginx.echoface.cn/#/login`
> ```
> 
> [@0xJacky](https://github.com/0xJacky) [@chung1912](https://github.com/chung1912)

是的

**Comment by echoface** [comment]
> > 我这里报错 User not exist；
> > ```
> > nginx_lan    | [0.146ms] [rows:0] SELECT * FROM `auths` WHERE `name` = "admin" AND `auths`.`deleted_at` IS NULL ORDER BY `auths`.`id` LIMIT 1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > sso登录必须要求对应应用要注册一个admin的用户？
> > 配置内容
> > ```
> > [casdoor]
> > Endpoint        = https://casdoor.xxxxx.cn
> > ExternalUrl     = https://casdoor.xxxxx.cn
> > ClientId        = 2b686xxxxxx6d0
> > ClientSecret    = e4836e2e666fb86xxxxxxxx5b1209bf6e58914d
> > CertificatePath = /xxxxxx/xxxxxxx/xxxxx.pem
> > Organization    = xxorg
> > Application     = nginxlan
> > RedirectUri     = `https://nginx.echoface.cn/#/login`
> > ```
> > 
> > 
> >     
> >   
> > [@0xJacky](https://github.com/0xJacky) [@chung1912](https://github.com/chung1912)
> 
> 是的

能否支持user 自动注册或者，配置中添加对应的配置项，比如allow_user_list 或者与casdoor交互的时候制定用户也行； 不然这个功能实现的比较奇怪； 和sso的实践规范相差很多
