### ISSUE TITLE
Clone button on locations

### ISSUE THREAD

**Issue by kcholoren** [0xJacky/nginx-ui#586]
It would be very useful to have a button to _clone_ settings from a Location inside a Site, without being forced to go to the advanced mode to copy them. Maybe next to the delete button.

Thank you.

**Comment by 0xJacky** [comment]
Thanks for your suggestion, I have added this feature in 6e17ddf, and it will be released with the next beta version of Nginx UI.

**Comment by kcholoren** [comment]
Thanks for the quick implementation!
