### ISSUE TITLE
Problem building the project for arm64

### ISSUE THREAD

**Issue by kordonskim** [0xJacky/nginx-ui#59]
I was hoping to get little help from you.
I am trying to build your project for arm64 architecture.
When I compile with this command 
CGO_ENABLED=1 GOOS=linux GOARCH=arm64 go build -ldflags "-X 'github.com/0xJacky/Nginx-UI/server/settings.buildTime=$(date +%s)'" -o nginx-ui -v main.go
and run it in docker I get this error below...

- nginx-ui  | /app/nginx-ui: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /app/nginx-ui)
- nginx-ui  | /app/nginx-ui: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /app/nginx-ui)
- nginx-ui  | /app/nginx-ui: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /app/nginx-ui)

Compiling with CGO_ENABLED=0 works but looks like sqlite requires cgo and I get error on creating the initial database.
Any chance you could point me to the right direction how to fix this?

**Comment by 0xJacky** [comment]
You should install gcc and g++ tool chain before cross compile nginx-ui with CGO.

Here is an example for Ubuntu users

tool | armhf | arm64 | eabi
-- | -- | -- | --
gcc | gcc-arm-linux-gnueabihf | gcc-aarch64-linux-gnu | gcc-arm-linux-gnueabi
g++ | g++-arm-linux-gnueabihf | g++-aarch64-linux-gnu | g++-arm-linux-gnueabi

1. Use apt-get to install gcc and g++ tool chain.
```
apt install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu -y
```
2. Build nginx-ui with `CC` and `CXX` flag
```
CGO_ENABLED=1 \
GOOS=linux \
CC=gcc-aarch64-linux-gnu \
CXX=g++-aarch64-linux-gnu \
GOARCH=amd64 go build -ldflags \
    "-X 'github.com/0xJacky/Nginx-UI/server/settings.buildTime=$(date +%s)'" -o nginx-ui -v main.go
```

**Comment by Hintay** [comment]
The reason for this issue is that the docker image you built does not have the corresponding compiled version of the `glib` library. Most importantly, according to our tests, our statically compiled `nginx-ui` with `glibc` does not work in embedded linux.

Therefore, if you want to use it cross-platform without glib, you should build it with [musl libc](https://musl.libc.org/). As refer, you can check our [GitHub Workflow file](https://github.com/0xJacky/nginx-ui/blob/master/.github/workflows/build.yml#L139-L152).

**Comment by kordonskim** [comment]
Thank you for all the responses. 
Go and Node are not my field of expertise. 
I ended up spinning off docker image of Debian Bullseye (to match version from your base image) and compiling your project within and then building the docker image on my main system which is Ubuntu.
I am up and running. 
Thanks again.
