### ISSUE TITLE
[Bug] 证书更新后, 路径发生变化

### ISSUE THREAD

**Issue by zuilintan** [0xJacky/nginx-ui#591]
**Describe the bug**
证书更新后, 原本
`*`.b.a.com_xxx_P256
变为
`#`.b.a.com_xxx_P256

**Screenshots**
![QQ_1727917929196](https://github.com/user-attachments/assets/6aa8cb66-72a7-484c-b5d4-4d027da47e61)
![image](https://github.com/user-attachments/assets/af74024f-9330-44c7-8069-37afc61272aa)

**Info (please complete the following information):**
 - Server OS: Debian-12
 - Nginx UI Version: 2.0.0-beta.35

**Comment by 0xJacky** [comment]
确实，修复了，下个版本发，更新后，建议重新签发证书
