### ISSUE TITLE
环境变量和app.ini的关系不正确

### ISSUE THREAD

**Issue by chung1912** [0xJacky/nginx-ui#594]
正常情况下，通常是环境变量优先级高于app.ini，两者配置应该相互独立。
但是，发现环境变量配置后，会自动写入app.ini，**这种情况下，如果删除环境变量，app.ini的配置并不会删除，而会保留，如果需要清除配置，则还需要去app.ini里面再操作一次**。

建议环境变量和app.ini相互独立，不把环境变量的配置写入app.ini

**Comment by 0xJacky** [comment]
已在 4d1adac 中解决，将会在 beta.36 发布。
