### ISSUE TITLE
please add a arm64 based docker image

### ISSUE THREAD

**Issue by DjSni** [0xJacky/nginx-ui#60]
As the title says, please add an arm64 based docker image. It would be nice.

**Comment by Hintay** [comment]
Hi, we have added docker images for multiple platforms starting with the [latest release of v1.7.1](https://hub.docker.com/r/uozi/nginx-ui/tags). Please feel free to let us know if you encounter any problems with the new image.

**Comment by DjSni** [comment]
Wow, that was fast. Thanks a lot, i will try it.
