### ISSUE TITLE
希望证书签发可以多域名单证书

### ISSUE THREAD

**Issue by ERSTT** [0xJacky/nginx-ui#601]
最近遇到了abc.com abc.cn需要指向同一个服务
目前在UI里签发只能签 *.abc.tld abc.tld
不能签 *.a.abc.tld *.abc.tld abc.tld的单证书
也不能签 *.abc.tld abc.tld *.123.tld 123.tld的单证书
现在在UI下只能多域名签发多个证书 然后写不同的server来达到多域名指向单一服务的需求

另外希望在"站点列表"里添加一个跟"管理 Stream"界面 一样的“添加”按钮
如果想用"高级模式"新增站点 每次添加站点都要先填必填项目 然后才能去修改里填写
或者添加站点里添加"高级模式"

**Comment by 0xJacky** [comment]
abc.com abc.cn 这个情况，现在是支持的

只要 server_name 是这样设置的，打开 let's encrypted 自动证书，就会获取到这样的证书

**Comment by ERSTT** [comment]
> abc.com abc.cn 这种情况，现在是支持的
> 
> 只要 server_name 是这样设置的，打开let's crypto自动证书，就能获取到这样的证书

试了下 在站点列表那里开证书的话如果 server_name 有*.abc.com *.abc.cn abc.com abc.cn 确实可以都签发 但是停用这个站点就会停用续签 但是其他站点也在用这个证书 
除非让其他站点也重复去签发 但是感觉这样的话 站点一多在快过期的时候很大概率撞到letsencrypt的速率限制
如果用证书里的签发泛域名 就又得写两份server

**Comment by 0xJacky** [comment]
1. 停用站点没法续签很合理，因为站点关闭后不能续签了
2. 速率限制这个问题，首次安装，我们会注册一个 ACME 用户并保存，之后的限流规则由 Let's encrypted 的策略决定：https://letsencrypt.org/zh-cn/docs/rate-limits/ 


> 我们最主要的限制是每个注册域名可签发的证书数量（每周 50 份）。
> 
> 每个账户三小时内最多可创建 300 份订单。 每次向 Boulder CA 申请证书都会创建一份新订单，也就是说每次证书请求都会生成一份新订单。 如果超出订单数量限制，就会得到 too many new orders recently 的报错信息。
>
> [每个 IP 地址](https://letsencrypt.org/zh-cn/docs/too-many-registrations-for-this-ip/)每 3 个小时最多可创建 10 个账户。 每个 IPv6 /48 地址段每 3 小时最多可以创建 500 个账户。 达到这两个账户限制是十分罕见的，我们建议我们建议大型集成商[使用一个帐户为多个客户提供服务](https://letsencrypt.org/zh-cn/docs/integration-guide/)。 超过这些限制的请求，将会得到 too many registrations for this IP 或者 too many registrations for this IP range的报错信息。

如果你有超出 300 个域名，也可以创建多个账户来进行申请，理论上每三小时可以申请 3000 个整数，这个配额足够了吧？

关于这项功能的 pr: https://github.com/0xJacky/nginx-ui/pull/361

**Comment by 0xJacky** [comment]
你可以创建多张 Wildcard 证书，然后对于 *.abc.tld abc.tld *.123.tld 123.tld 这种需求，可以在同一个 Server 里绑定多张证书，就可以实现你的需求。
