### ISSUE TITLE
使用 dns 申请 ssl 证书时，最后保存阶段报错：make certificate dir error: mkdir : no such file or directory 

### ISSUE THREAD

**Issue by zsio** [0xJacky/nginx-ui#602]
**Describe the bug**
使用阿里云的 dns 申请 ssl 证书，申请成功后会在保存证书文件时报错。

**To Reproduce**
1. 添加 dns 凭证
2. 申请泛域名证书
3. 观察日志发现申请成功，但是保存时出错

**Expected behavior**
我希望能正常保存证书

**Screenshots**
<img width="2318" alt="image" src="https://github.com/user-attachments/assets/263ad0fb-8a85-426a-afdd-cda1c3816b50">

**Info (please complete the following information):**
 - Server OS: debian 12
 - Server Arch: x86
 - Nginx UI Version: 2.0.0-beta.36 (2)
 - Your Browser: arc / chrome

**Comment by 0xJacky** [comment]
麻烦检查 nginx 配置目录下是否有 ssl 文件夹

如 /etc/nginx/ssl

**Comment by 0xJacky** [comment]
不存在的话手动创建一下就可以，下个版本会改用 mkdirAll 函数创建文件夹

**Comment by 0xJacky** [comment]
我重新检查了代码，确实是用的 mkdirAll 函数，无法复现您的问题，在我的测试环境中，/etc/nginx/ssl 也是不存在的

如果有更多细节补充请回复此 issue，我会重新打开。

**Comment by zhouzongyan** [comment]
用的版本也是 2.0.0-beta.36

**Comment by zhouzongyan** [comment]
也是没有/etc/nginx/ssl文件夹
![image](https://github.com/user-attachments/assets/b6b08591-2627-41c1-a7d9-5438eee6d1af)

**Comment by 0xJacky** [comment]
> 也是没有/etc/nginx/ssl文件夹
> 
> ![image](https://github.com/user-attachments/assets/b6b08591-2627-41c1-a7d9-5438eee6d1af)
> 
> 

如果手动创建呢？

**Comment by zhouzongyan** [comment]
测试太多次被限制了，到时候我试试
![image](https://github.com/user-attachments/assets/b75f29f1-b57d-4086-a0a5-8e300234eac1)

**Comment by 0xJacky** [comment]
@zhouzongyan 可以使用这个 CA Dir：
https://acme-staging-v02.api.letsencrypt.org/directory，这个是 Let's Encrypt 的演示环境，可以提供更多次的错误重试。

**Comment by zhouzongyan** [comment]
手动创建ssl文件夹也不行，还是一样的错误，配置的是et's Encrypt 演示环境地址
![image](https://github.com/user-attachments/assets/9365c042-729e-4b83-ba89-1b5656806f95)

![image](https://github.com/user-attachments/assets/ff6c091e-4608-4a3f-b5c8-0210ba7581a6)

**Comment by 0xJacky** [comment]
nginxui 有权限读写吗

**Comment by 0xJacky** [comment]
> 有的，我特意把ssl改成了777权限

**Comment by 0xJacky** [comment]
> 有的，我特意把ssl改成了777权限

安装方式是？

**Comment by zhouzongyan** [comment]
需要我弄啥不，我也做啥操作，就正常的用脚本安装，然后签发证书

**Comment by zhouzongyan** [comment]
用这个命令安装的
![image](https://github.com/user-attachments/assets/0ef0ab76-a241-44fb-8e3b-f6dc4f3da2ea)

**Comment by 0xJacky** [comment]
> 用这个命令安装的 ![image](https://private-user-images.githubusercontent.com/18110319/378073138-0ef0ab76-a241-44fb-8e3b-f6dc4f3da2ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMzU3NDgsIm5iZiI6MTcyOTMzNTQ0OCwicGF0aCI6Ii8xODExMDMxOS8zNzgwNzMxMzgtMGVmMGFiNzYtYTI0MS00NGZiLThlM2ItZjZkYzRmM2RhMmVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDEwNTcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0MzM1NGExMjNhOWU4YmNjNTI0YmNiZTk2NjMzZWY1ZDNlYWNmYzFiNTg3ODBmOTUzZmRkNmI3M2ZhZmEwMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pKS_Jwgwrdfr_4Rgbexj35wlgtKQmtO8o6LUxio3wB4)

操作系统是？

**Comment by zhouzongyan** [comment]
Debian 11
![image](https://github.com/user-attachments/assets/1c4e559f-a7d6-4ea9-9483-658e11ad03ce)

**Comment by 0xJacky** [comment]
好的收到，如果我能复现的话会研究一下

**Comment by zhouzongyan** [comment]
请问程序的日志路径配置是在哪个路径，没看到有对应的配置

**Comment by 0xJacky** [comment]
> 请问程序的日志路径配置是在哪个路径，没看到有对应的配置

journalctl -uf nginx-hi

**Comment by zhouzongyan** [comment]
看日志是nginx出错了
![image](https://github.com/user-attachments/assets/d50a5d7d-63c6-4a54-8d5c-7226498a3c80)

**Comment by 0xJacky** [comment]
噢这样，你的nginx是怎么安装的？ 自己编译的吗，可以手动配置一下这个：https://nginxui.com/zh_CN/guide/config-nginx.html

**Comment by zhouzongyan** [comment]
嗯，用官方的nginx包正常了，感谢
