### ISSUE TITLE
一件安装脚本报错

### ISSUE THREAD

**Issue by vergil-lai** [0xJacky/nginx-ui#604]
~ sudo bash <(curl -L -s https://mirror.ghproxy.com/https://raw.githubusercontent.com/0xJacky/nginx-ui/master/install.sh) install -r https://mirror.ghproxy.com/

bash: /proc/self/fd/11: No such file or directory

**Comment by Hintay** [comment]
请使用以下命令重试∶

```bash
bash -c "$(curl -L https://mirror.ghproxy.com/https://raw.githubusercontent.com/0xJacky/nginx-ui/master/install.sh)" @ install -r https://mirror.ghproxy.com/
```

**Comment by vergil-lai** [comment]
> 请使用以下命令重试∶
> 
> ```shell
> bash -c "$(curl -L https://mirror.ghproxy.com/https://raw.githubusercontent.com/0xJacky/nginx-ui/master/install.sh)" @ install -r https://mirror.ghproxy.com/
> ```

可以了，谢谢
