### ISSUE TITLE
请问日志总是显示不出来？

### ISSUE THREAD

**Issue by joylijoy** [0xJacky/nginx-ui#606]
在LogDirWhiteList =处填的是nginx的日志路径，但登陆nignx-ui后，显示The log path is not under the paths in LogDirWhiteList. 是为什么，谢谢

**Comment by 0xJacky** [comment]
填写的是日志的文件夹路径

**Comment by joylijoy** [comment]
> 填写的是日志的文件夹路径

我填的是这个呀，就是存放nginx的access.log和error.log的日志的路径对吧？

**Comment by 0xJacky** [comment]
不是，填的是文件夹的路径，然后改完记得 restart nginx-ui

**Comment by joylijoy** [comment]
> 不是，填的是文件夹的路径，然后改完记得 restart nginx-ui

填完了日志文件夹的路径后，报这个问题：log file is not regular file

**Comment by 0xJacky** [comment]
/apps/openresty/nginx/logs 这个文件是软连接吗？

**Comment by joylijoy** [comment]
> /apps/openresty/nginx/logs 这个文件是软连接吗？

不是，是真实的文件夹
![image](https://github.com/user-attachments/assets/da855929-e9f5-483c-912a-a68028085098)

**Comment by 0xJacky** [comment]
只支持单个文件
![Uploading image.png…]()

**Comment by joylijoy** [comment]
> 只支持单个文件
> 
> 比如
> 
> AccessLogPath = /var/logs/nginx/access.log LogDirWhiteList = /var/logs/nginx

可以了，谢谢！

**Comment by xlcaptain** [comment]
![微信截图_20241107230219](https://github.com/user-attachments/assets/58b8c94a-9378-4d6a-9a1c-28e2167e3e6d)
如果是docker-compose来启动服务的话，这个LogDirWhiteList设置以环境变量不太行，这怎么办呢？是需要在容器中修改app.ini的配置吗？在容器中我没有找到go的app.ini这个配置文件，请问能够解答吗？

**Comment by xlcaptain** [comment]
@0xJacky

**Comment by 0xJacky** [comment]
@xlcaptain 文档要看全，
https://nginxui.com/zh_CN/guide/env.html#nginx

<img width="654" alt="image" src="https://github.com/user-attachments/assets/8f3efad7-456f-4ccd-a91b-06520c48ce52">

`NGINX_UI_NGINX_LOG_DIR_WHITE_LIST`

**Comment by xlcaptain** [comment]
@0xJacky 明白了，谢谢。配置似乎成功：
![微信截图_20241107235554](https://github.com/user-attachments/assets/14a98d7e-2a74-4e9e-afdd-e4127711103c)
但是，日志中没有产生日志，我已经成功在nginx-ui中配置了我的个人网站的转发，并且能够成功获取，但是没有日志：
![微信截图_20241107235607](https://github.com/user-attachments/assets/dfacb904-e739-4503-b8fc-c753f663738f)
以下是我的终端docker-compose日志以及容器中就日志文件的权限截图：
![微信截图_20241107235751](https://github.com/user-attachments/assets/aaae0cb5-c5b1-4026-9600-a896742c6f95)
![微信截图_20241107235924](https://github.com/user-attachments/assets/cf9cdc0c-37ac-4712-8c31-6fc9c43f202e)

望能够查看，十分感谢您的回答！
