### ISSUE TITLE
能否提供支持HTTP/3 (QUIC)版本的nginx

### ISSUE THREAD

**Issue by BugChang** [0xJacky/nginx-ui#607]

**Comment by BugChang** [comment]
> 您是说 docker 容器内的 Nginx？

对的，能编译一个支持的NGINX作为另一个版本么

**Comment by 0xJacky** [comment]
抱歉，暂时没有这个计划，这种情况下更推荐将 nginx-ui 安装在宿主机上。

**Comment by freshgeek** [comment]
请问docker 方式运行 是否可以支持外部nginx？或者提供编译选项？有没有具体操作教程文档可以？目前使用涉及到流控 、安全、性能缓存等方面的 需要加模块进去 不知道从哪里下手

**Comment by 0xJacky** [comment]
> 请问docker 方式运行 是否可以支持外部nginx？或者提供编译选项？有没有具体操作教程文档可以？目前使用涉及到流控 、安全、性能缓存等方面的 需要加模块进去 不知道从哪里下手 @0xJacky 

目前暂时建议自由构建镜像，然后在 Dockerfile 里执行 nginx-ui 安装脚本

**Comment by freshgeek** [comment]
> > 请问docker 方式运行 是否可以支持外部nginx？或者提供编译选项？有没有具体操作教程文档可以？目前使用涉及到流控 、安全、性能缓存等方面的 需要加模块进去 不知道从哪里下手 [@0xJacky](https://github.com/0xJacky)
> 
> 目前暂时建议自由构建镜像，然后在 Dockerfile 里执行 nginx-ui 安装脚本

好的 谢谢  晚点我看看能否成功

**Comment by chung1912** [comment]
> > > 请问docker 方式运行 是否可以支持外部nginx？或者提供编译选项？有没有具体操作教程文档可以？目前使用涉及到流控 、安全、性能缓存等方面的 需要加模块进去 不知道从哪里下手 [@0xJacky](https://github.com/0xJacky)
> > 
> > 
> > 目前暂时建议自由构建镜像，然后在 Dockerfile 里执行 nginx-ui 安装脚本
> 
> 好的 谢谢 晚点我看看能否成功 ，请问 https://github.com/0xJacky/nginx-ui/blob/dev/Dockerfile 这个基础镜像有公开吗？我看是nginx-ui的基础镜像，只能以容器再构建的方式创建自己的镜像吗？ 安装脚本中也是nginx-ui的安装 好像没有暴露nginx 的安装 方式 https://github.com/0xJacky/nginx-ui/blob/dev/install.sh

我也想知道，如果手上已经有自己添加了自定义nginx模块的镜像，现在这个镜像怎么作为基础镜像构建到nginx-ui中？

**Comment by freshgeek** [comment]
> > > > 请问docker 方式运行 是否可以支持外部nginx？或者提供编译选项？有没有具体操作教程文档可以？目前使用涉及到流控 、安全、性能缓存等方面的 需要加模块进去 不知道从哪里下手 [@0xJacky](https://github.com/0xJacky)
> > > 
> > > 
> > > 目前暂时建议自由构建镜像，然后在 Dockerfile 里执行 nginx-ui 安装脚本
> > 
> > 
> > 好的 谢谢 晚点我看看能否成功 ，请问 https://github.com/0xJacky/nginx-ui/blob/dev/Dockerfile 这个基础镜像有公开吗？我看是nginx-ui的基础镜像，只能以容器再构建的方式创建自己的镜像吗？ 安装脚本中也是nginx-ui的安装 好像没有暴露nginx 的安装 方式 https://github.com/0xJacky/nginx-ui/blob/dev/install.sh
> 
> 我也想知道，如果手上已经有自己添加了自定义nginx模块的镜像，现在这个镜像怎么作为基础镜像构建到nginx-ui中？

https://github.com/0xJacky/uozi-docker/blob/main/nginx-ui-base/Dockerfile 这边是他的基础镜像，但是没看懂应该如何串起来

**Comment by 0xJacky** [comment]
> > > > > 请问docker 方式运行 是否可以支持外部nginx？或者提供编译选项？有没有具体操作教程文档可以？目前使用涉及到流控 、安全、性能缓存等方面的 需要加模块进去 不知道从哪里下手 [@0xJacky](https://github.com/0xJacky)
> > > > 
> > > > 
> > > > 目前暂时建议自由构建镜像，然后在 Dockerfile 里执行 nginx-ui 安装脚本
> > > 
> > > 
> > > 好的 谢谢 晚点我看看能否成功 ，请问 https://github.com/0xJacky/nginx-ui/blob/dev/Dockerfile 这个基础镜像有公开吗？我看是nginx-ui的基础镜像，只能以容器再构建的方式创建自己的镜像吗？ 安装脚本中也是nginx-ui的安装 好像没有暴露nginx 的安装 方式 https://github.com/0xJacky/nginx-ui/blob/dev/install.sh
> > 
> > 
> > 我也想知道，如果手上已经有自己添加了自定义nginx模块的镜像，现在这个镜像怎么作为基础镜像构建到nginx-ui中？
> 
> https://github.com/0xJacky/uozi-docker/blob/main/nginx-ui-base/Dockerfile 这边是他的基础镜像，但是没看懂应该如何串起来

我计划在下个月的正式版前，增加只包含 Nginx UI 镜像，然后通过 docker client API 去控制其他的 Nginx 容器。

**Comment by freshgeek** [comment]
> > > > > > 请问docker 方式运行 是否可以支持外部nginx？或者提供编译选项？有没有具体操作教程文档可以？目前使用涉及到流控 、安全、性能缓存等方面的 需要加模块进去 不知道从哪里下手 [@0xJacky](https://github.com/0xJacky)
> > > > > 
> > > > > 
> > > > > 目前暂时建议自由构建镜像，然后在 Dockerfile 里执行 nginx-ui 安装脚本
> > > > 
> > > > 
> > > > 好的 谢谢 晚点我看看能否成功 ，请问 https://github.com/0xJacky/nginx-ui/blob/dev/Dockerfile 这个基础镜像有公开吗？我看是nginx-ui的基础镜像，只能以容器再构建的方式创建自己的镜像吗？ 安装脚本中也是nginx-ui的安装 好像没有暴露nginx 的安装 方式 https://github.com/0xJacky/nginx-ui/blob/dev/install.sh
> > > 
> > > 
> > > 我也想知道，如果手上已经有自己添加了自定义nginx模块的镜像，现在这个镜像怎么作为基础镜像构建到nginx-ui中？
> > 
> > 
> > https://github.com/0xJacky/uozi-docker/blob/main/nginx-ui-base/Dockerfile 这边是他的基础镜像，但是没看懂应该如何串起来
> 
> 我计划在下个月的正式版前，增加只包含 Nginx UI 镜像，然后通过 docker client API 去控制其他的 Nginx 容器。

感谢您的回复，但是目前等不了那么久，我只能先研究下如何打一个支持外部模块的包出来

**Comment by freshgeek** [comment]
自定义 nginx 打包dockerfile https://github.com/kejilion/docker/blob/main/nginx/Dockerfile
