### ISSUE TITLE
Nginx 反向代理模板配置

### ISSUE THREAD

**Issue by YiHui-Liu** [0xJacky/nginx-ui#608]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
![image](https://github.com/user-attachments/assets/8d981ccd-16bb-4d6d-9d21-ed5dc14706d6)

add `scheme`, `server` and `port` items, change `proxy_pass` to:
```
proxy_pass       $scheme://$server:$port$request_uri;
```

**Comment by 0xJacky** [comment]
It there any problem about the current template?

**Comment by YiHui-Liu** [comment]
> It there any problem about the current template?

No, but if you deploy `nginx-ui` with docker, other services host will not be `127.0.0.1`, so i recommend to add a configuration item with `host`

**Comment by 0xJacky** [comment]
Ok, I will add a field to set the host of backend server.

**Comment by YiHui-Liu** [comment]
> Ok, I will add a field to set the host of backend server.

thanks for your work.
