### ISSUE TITLE
脚本自动安装后，打开[站点列表]会出现open /etc/nginx/sites-available: no such file or directory

### ISSUE THREAD

**Issue by YMingPro** [0xJacky/nginx-ui#611]
**Describe the bug**
在按文档一键脚本安装后，
打开【站点列表】和【管理Stream】会出现类似open /etc/nginx/sites-available: no such file or directory 这样的提示，
我手动增加所提示的dir后才不会报错。

问题：
1. 或许可以修复这个问题？没有的话可以自动mkdir
2. 我在【配置管理】里是能看到我之前nginx下的配置问题的，但是在【站点列表】并不会同步，想知道是否可以提供一个同步机制？还是说设计之初，此处的【站点列表】均是由【添加站点】才会产生？而不能从已有的配置中提取或者同步之类的?

**Comment by 0xJacky** [comment]
有关此 issue 的回答在这里：
https://nginxui.com/zh_CN/guide/getting-started.html#%E4%BD%BF%E7%94%A8%E5%89%8D%E6%B3%A8%E6%84%8F

**Comment by YMingPro** [comment]
> 有关此 issue 的回答在这里： https://nginxui.com/zh_CN/guide/getting-started.html#%E4%BD%BF%E7%94%A8%E5%89%8D%E6%B3%A8%E6%84%8F

感谢回复，已解决。

**Comment by huchao-hu** [comment]
![image](https://github.com/user-attachments/assets/ee164470-b1cc-4615-940b-1aabb559ad66)
![image](https://github.com/user-attachments/assets/b5eaa43e-51a3-4b78-8862-22b7a83117c3)

**Comment by huchao-hu** [comment]
我已经按照上述文档配置了 但是报错没有目录 @YMingPro

**Comment by huchao-hu** [comment]
我已经按照上述文档配置了 但是报错没有目录 @0xJacky

**Comment by huchao-hu** [comment]
想问一下您是怎么解决的呢 @YMingPro

**Comment by YMingPro** [comment]
> 想问一下您是怎么解决的呢 @YMingPro

创建sites-avaliable目录了吗？ 我新的服务器全新重装nginx-ui的脚本已经没有这个bug了。如果你还有这个问题，手动创建enable和avaliable目录就好
