### ISSUE TITLE
运行app.int的时候 runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by excaliburKongbai** [0xJacky/nginx-ui#612]
**Describe the bug**
使用docker部署
docker run -dit \
  --name=nginx-ui \
  --restart=always \
  -e TZ=Asia/Shanghai \
  -v /mnt/user/appdata/nginx:/etc/nginx \
  -v /mnt/user/appdata/nginx-ui:/etc/nginx-ui \
  -v /home/www/web:/web \
  -p 8080:80 -p 8443:443 \
  uozi/nginx-ui:latest
  
  在根目/etc/nginx-ui 运行 nginx-ui -config app.ini发生异常空指针
  
  **Run Logs**
root@6ee3e50328f2:/etc/nginx-ui# nginx-ui -config app.ini
2024/10/12 10:49:34 [overseer] disabled. run failed: listen tcp 0.0.0.0:9000: bind: address already in use
2024-10-12 10:49:34     INFO    nginx-ui/main.go:20     Nginx configuration directory: /etc/nginx
2024-10-12 10:49:34     ERROR   kernal/boot.go:67       runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
github.com/0xJacky/Nginx-UI/internal/kernal.recovery()
        /home/runner/work/nginx-ui/nginx-ui/internal/kernal/boot.go:66 +0x65
panic({0x36ce840?, 0x7594300?})
        /opt/hostedtoolcache/go/1.23.2/x64/src/runtime/panic.go:785 +0x132
github.com/0xJacky/Nginx-UI/internal/kernal.RegisterAcmeUser()
        /home/runner/work/nginx-ui/nginx-ui/internal/kernal/register_acme_user.go:10 +0x2c
github.com/0xJacky/Nginx-UI/internal/kernal.Boot()
        /home/runner/work/nginx-ui/nginx-ui/internal/kernal/boot.go:40 +0xa2
main.Program({0x0, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0, ...}, ...})
        /home/runner/work/nginx-ui/nginx-ui/main.go:22 +0xac
github.com/jpillora/overseer.Run({0x0, 0x477f8d0, {0xc0013c2fe0, 0xc}, {0x0, 0x0, 0x0}, {0x0, 0x0}, 0x12a05f200, ...})
        /home/runner/go/pkg/mod/github.com/jpillora/overseer@v1.1.6/overseer.go:106 +0x215
main.main()
        /home/runner/work/nginx-ui/nginx-ui/main.go:43 +0x2fd

2024-10-12 10:49:34     INFO    nginx-ui/main.go:31     Server exited

**Comment by 0xJacky** [comment]
您好，docker 启动后会自动运行的，无需进入容器执行启动命令，如果 docker 启动失败，可以贴一下 docker logs -f nginx-ui 的日志，谢谢。

**Comment by excaliburKongbai** [comment]
> 您好，docker 启动后会自动运行的，无需进入容器执行启动命令，如果 docker 启动失败，可以贴一下 docker logs -f nginx-ui 的日志，谢谢。

好的,请问启动docker 后的访问地址是什么吗?直接返回80端口吗

**Comment by 0xJacky** [comment]
看你的端口映射情况，我看配置文件是 8080

**Comment by excaliburKongbai** [comment]
> 看你的端口映射情况，我看配置文件是 8080

我这边打开防火墙,访问8080端口nginx 502了

我修改了app.in的HttpPort的端口防止端口冲突,并且重启了容器还是不行

**Comment by excaliburKongbai** [comment]
> 看你的端口映射情况，我看配置文件是 8080

*16 connect() failed (111: Connection refused) while connecting to upstream, client: 183.30.222.244, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:9000/favicon.ico", host: "47.***.**.**:8080", referrer: "http://47.***.**.**:8080/admin"

我这边查看了一下nginx 的错误日志,我修改了app.in的配置,重启了容器,但是服务没有刷新

**Comment by 0xJacky** [comment]
修改了nginx-ui的端口要改 nginx 的配置文件，因为 nginx 反向代理了 nginx-ui，如果不需要，可以直接暴露 nginx-ui 的端口出来。

**Comment by YMingPro** [comment]
> 修改了nginx-ui的端口要改 nginx 的配置文件，因为 nginx 反向代理了 nginx-ui，如果不需要，可以直接暴露 nginx-ui 的端口出来。

在docker desktop的运行方式中，直接用命令运行起容器但缺少-p 9000:9000 的映射似乎访问不了nginx-ui的界面？

**Comment by 0xJacky** [comment]
并不是，直接访问80端口就可以访问 nginx-ui 做了反向代理了，如果不能访问，麻烦提供日志 谢谢

**Comment by YMingPro** [comment]
> 并不是，直接访问80端口就可以访问 nginx-ui 做了反向代理了，如果不能访问，麻烦提供日志 谢谢

且访问后会初始化时会出现没有app.ini的报错，补充了一个app.ini后，又会提示invalid memory address or nil pointer dereference

所以似乎不支持windows的docker
![image](https://github.com/user-attachments/assets/1b27653d-aed5-4b86-be07-509f33934470)
![image](https://github.com/user-attachments/assets/86b66770-9fed-4a01-84c8-94d6221498ae)
![image](https://github.com/user-attachments/assets/8425c8bd-0c5d-4d84-943b-86485feb8099)

**Comment by excaliburKongbai** [comment]
> 修改了nginx-ui的端口要改 nginx 的配置文件，因为 nginx 反向代理了 nginx-ui，如果不需要，可以直接暴露 nginx-ui 的端口出来。

好的我这边已经解决问题了

**Comment by excaliburKongbai** [comment]
> > 并不是，直接访问80端口就可以访问 nginx-ui 做了反向代理了，如果不能访问，麻烦提供日志 谢谢
> 
> 且访问后会初始化时会出现没有app.ini的报错，补充了一个app.ini后，又会提示invalid memory address or nil pointer dereference
> 
> 所以似乎不支持windows的docker ![image](https://private-user-images.githubusercontent.com/36704983/375930149-1b27653d-aed5-4b86-be07-509f33934470.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTQwMzIsIm5iZiI6MTcyODcxMzczMiwicGF0aCI6Ii8zNjcwNDk4My8zNzU5MzAxNDktMWIyNzY1M2QtYWVkNS00Yjg2LWJlMDctNTA5ZjMzOTM0NDcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA2MTUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzMzc4NzI2M2Y1NzI5MDgyMzJiMjI4ZDdkM2MxODEzYWI5ODUwM2RhZGEwNDYyNGY5NWNiMjM1NTU2MWRhODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8WkqVuAIT8UPEMpWbMlfi-z4SSfQzgem-AZ6H1jAt1Y) ![image](https://private-user-images.githubusercontent.com/36704983/375930167-86b66770-9fed-4a01-84c8-94d6221498ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTQwMzIsIm5iZiI6MTcyODcxMzczMiwicGF0aCI6Ii8zNjcwNDk4My8zNzU5MzAxNjctODZiNjY3NzAtOWZlZC00YTAxLTg0YzgtOTRkNjIyMTQ5OGFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA2MTUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4MTEzM2JmMzgxZjRiNThlZGIwZDNlZTQ3NDU5NTE2NjNjMDJjOTQwN2QwNDZmYTVlNzkyYzc3OWViYzdhMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fRsFwQSPF2c022zIkupczw55pNJnFMbyQ-xU9i0cJEU) ![image](https://private-user-images.githubusercontent.com/36704983/375930247-8425c8bd-0c5d-4d84-943b-86485feb8099.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTQwMzIsIm5iZiI6MTcyODcxMzczMiwicGF0aCI6Ii8zNjcwNDk4My8zNzU5MzAyNDctODQyNWM4YmQtMGM1ZC00ZDg0LTk0M2ItODY0ODVmZWI4MDk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA2MTUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViNDk5YjdmZWI5ODEzNTQ3OGViYjVmOWE3ZTZmMzEwZDJiYTFlZDdhYjY1ODUxNzk4YmQ0YzUzMWU2NjQ4NzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UrEiNRFd06h5z5jvo7h66A5XcFTwHJed7i-Js-Z9JgA) ![image](https://private-user-images.githubusercontent.com/36704983/375930363-5f139af4-4324-4f20-8a84-75002c519f2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTQwMzIsIm5iZiI6MTcyODcxMzczMiwicGF0aCI6Ii8zNjcwNDk4My8zNzU5MzAzNjMtNWYxMzlhZjQtNDMyNC00ZjIwLThhODQtNzUwMDJjNTE5ZjJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA2MTUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjNjM5NGVkNDMxNzhjMWFkMzFlYWExNWE4ZThjMDY2OTM5OGZlOWM3ZWQyOWVhOGE1YjQzNDBjMjRkOTg4N2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bLzkhwqPQnsM7QlO5b7ayM8u9_KXt1etyHL3js8-ZvM)
> 
> 尝试了下把映射的两个目录去掉后，启动报告依然会出现Error save settings open /etc/nginx-ui/app.ini: no such file or directory的错误
> 
> 最后：在手动进入容器内的目录新增 touch /etc/nginx-ui/app.ini 空白文件后，重启容器，一切恢复正常。但依旧80端口映射不了，默认还是9000

这个9000端口不需要对外暴露,1你直接访问映射:80端口的就可以了,如果你修改了nginx-ui的端口,需要修改nginx-ui.conf
![image](https://github.com/user-attachments/assets/f56a2a46-ba2d-456e-bb8f-8ae1fa395850)

**Comment by YMingPro** [comment]
> > > 并不是，直接访问80端口就可以访问 nginx-ui 做了反向代理了，如果不能访问，麻烦提供日志 谢谢
> > 
> > 
> > 且访问后会初始化时会出现没有app.ini的报错，补充了一个app.ini后，又会提示invalid memory address or nil pointer dereference
> > 所以似乎不支持windows的docker ![image](https://private-user-images.githubusercontent.com/36704983/375930149-1b27653d-aed5-4b86-be07-509f33934470.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTQwMzIsIm5iZiI6MTcyODcxMzczMiwicGF0aCI6Ii8zNjcwNDk4My8zNzU5MzAxNDktMWIyNzY1M2QtYWVkNS00Yjg2LWJlMDctNTA5ZjMzOTM0NDcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA2MTUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzMzc4NzI2M2Y1NzI5MDgyMzJiMjI4ZDdkM2MxODEzYWI5ODUwM2RhZGEwNDYyNGY5NWNiMjM1NTU2MWRhODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8WkqVuAIT8UPEMpWbMlfi-z4SSfQzgem-AZ6H1jAt1Y) ![image](https://private-user-images.githubusercontent.com/36704983/375930167-86b66770-9fed-4a01-84c8-94d6221498ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTQwMzIsIm5iZiI6MTcyODcxMzczMiwicGF0aCI6Ii8zNjcwNDk4My8zNzU5MzAxNjctODZiNjY3NzAtOWZlZC00YTAxLTg0YzgtOTRkNjIyMTQ5OGFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA2MTUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4MTEzM2JmMzgxZjRiNThlZGIwZDNlZTQ3NDU5NTE2NjNjMDJjOTQwN2QwNDZmYTVlNzkyYzc3OWViYzdhMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fRsFwQSPF2c022zIkupczw55pNJnFMbyQ-xU9i0cJEU) ![image](https://private-user-images.githubusercontent.com/36704983/375930247-8425c8bd-0c5d-4d84-943b-86485feb8099.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTQwMzIsIm5iZiI6MTcyODcxMzczMiwicGF0aCI6Ii8zNjcwNDk4My8zNzU5MzAyNDctODQyNWM4YmQtMGM1ZC00ZDg0LTk0M2ItODY0ODVmZWI4MDk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA2MTUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViNDk5YjdmZWI5ODEzNTQ3OGViYjVmOWE3ZTZmMzEwZDJiYTFlZDdhYjY1ODUxNzk4YmQ0YzUzMWU2NjQ4NzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UrEiNRFd06h5z5jvo7h66A5XcFTwHJed7i-Js-Z9JgA) ![image](https://private-user-images.githubusercontent.com/36704983/375930363-5f139af4-4324-4f20-8a84-75002c519f2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTQwMzIsIm5iZiI6MTcyODcxMzczMiwicGF0aCI6Ii8zNjcwNDk4My8zNzU5MzAzNjMtNWYxMzlhZjQtNDMyNC00ZjIwLThhODQtNzUwMDJjNTE5ZjJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA2MTUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjNjM5NGVkNDMxNzhjMWFkMzFlYWExNWE4ZThjMDY2OTM5OGZlOWM3ZWQyOWVhOGE1YjQzNDBjMjRkOTg4N2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bLzkhwqPQnsM7QlO5b7ayM8u9_KXt1etyHL3js8-ZvM)
> > 尝试了下把映射的两个目录去掉后，启动报告依然会出现Error save settings open /etc/nginx-ui/app.ini: no such file or directory的错误
> > 最后：在手动进入容器内的目录新增 touch /etc/nginx-ui/app.ini 空白文件后，重启容器，一切恢复正常。但依旧80端口映射不了，默认还是9000
> 
> 这个9000端口不需要对外暴露,1你直接访问映射:80端口的就可以了,如果你修改了nginx-ui的端口,需要修改nginx-ui.conf ![image](https://private-user-images.githubusercontent.com/78746805/375930999-f56a2a46-ba2d-456e-bb8f-8ae1fa395850.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTQxOTYsIm5iZiI6MTcyODcxMzg5NiwicGF0aCI6Ii83ODc0NjgwNS8zNzU5MzA5OTktZjU2YTJhNDYtYmEyZC00NTZlLWJiOGYtOGFlMWZhMzk1ODUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA2MTgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkZTQ4YTFjMDMzNjI2MWQxM2MyYmExNWNjODM3NzY5MzIxZTgxOWMxYjgwZjM2MTdiY2IwYzhiNjZjM2VhN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._n-QRn2PY7eM_Q6677Lb14t1qcPN3A6Mj9FH42WeliA)

请你看清楚我的截图，里面访问80端口不了，9000才可以。且容器内的nginx.conf并没有配置nginx-ui的代理
![image](https://github.com/user-attachments/assets/d58a286b-e76f-4057-8cc9-8e0ead3b8f76)

**Comment by excaliburKongbai** [comment]
> > > > 并不是，直接访问80端口就可以访问 nginx-ui 做了反向代理了，如果不能访问，麻烦提供日志 谢谢
> > > 
> > > 
> > > 且访问后会初始化时会出现没有app.ini的报错，补充了一个app.ini后，又会提示无效的内存地址或零指针取消引用所以似乎不支持windows的docker ![图像](https://private-user-images.githubusercontent.com/36704983/375930149-1b27653d-aed5-4b86-be07-509f33934470.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTQwMzIsIm5iZiI6MTcyODcxMzczMiwicGF0aCI6Ii8zNjcwNDk4My8zNzU5MzAxNDktMWIyNzY1M2QtYWVkNS00Yjg2LWJlMDctNTA5ZjMzOTM0NDcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA2MTUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzMzc4NzI2M2Y1NzI5MDgyMzJiMjI4ZDdkM2MxODEzYWI5ODUwM2RhZGEwNDYyNGY5NWNiMjM1NTU2MWRhODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8WkqVuAIT8UPEMpWbMlfi-z4SSfQzgem-AZ6H1jAt1Y) ![图像](https://private-user-images.githubusercontent.com/36704983/375930167-86b66770-9fed-4a01-84c8-94d6221498ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTQwMzIsIm5iZiI6MTcyODcxMzczMiwicGF0aCI6Ii8zNjcwNDk4My8zNzU5MzAxNjctODZiNjY3NzAtOWZlZC00YTAxLTg0YzgtOTRkNjIyMTQ5OGFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA2MTUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4MTEzM2JmMzgxZjRiNThlZGIwZDNlZTQ3NDU5NTE2NjNjMDJjOTQwN2QwNDZmYTVlNzkyYzc3OWViYzdhMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fRsFwQSPF2c022zIkupczw55pNJnFMbyQ-xU9i0cJEU) ![图像](https://private-user-images.githubusercontent.com/36704983/375930247-8425c8bd-0c5d-4d84-943b-86485feb8099.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTQwMzIsIm5iZiI6MTcyODcxMzczMiwicGF0aCI6Ii8zNjcwNDk4My8zNzU5MzAyNDctODQyNWM4YmQtMGM1ZC00ZDg0LTk0M2ItODY0ODVmZWI4MDk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA2MTUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViNDk5YjdmZWI5ODEzNTQ3OGViYjVmOWE3ZTZmMzEwZDJiYTFlZDdhYjY1ODUxNzk4YmQ0YzUzMWU2NjQ4NzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UrEiNRFd06h5z5jvo7h66A5XcFTwHJed7i-Js-Z9JgA) ![图像](https://private-user-images.githubusercontent.com/36704983/375930363-5f139af4-4324-4f20-8a84-75002c519f2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTQwMzIsIm5iZiI6MTcyODcxMzczMiwicGF0aCI6Ii8zNjcwNDk4My8zNzU5MzAzNjMtNWYxMzlhZjQtNDMyNC00ZjIwLThhODQtNzUwMDJjNTE5ZjJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA2MTUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjNjM5NGVkNDMxNzhjMWFkMzFlYWExNWE4ZThjMDY2OTM5OGZlOWM3ZWQyOWVhOGE1YjQzNDBjMjRkOTg4N2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bLzkhwqPQnsM7QlO5b7ayM8u9_KXt1etyHL3js8-ZvM) 尝试了下把映射的两个目录去掉后，启动报告依然会出现Error save settings open /etc/nginx-ui/app.ini： no such file or directory的错误 最后：在手动进入容器内的目录新增 touch /etc/nginx-ui/app.ini 空白文件后，重启容器，一切恢复正常。但依旧80端口映射不了，默认还是9000
> > 
> > 
> > 这个9000端口不需要对外暴露，1你直接访问映射：80端口的就可以了，如果你修改了nginx-ui的端口，需要修改nginx-ui.conf![图像](https://private-user-images.githubusercontent.com/78746805/375930999-f56a2a46-ba2d-456e-bb8f-8ae1fa395850.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTQxOTYsIm5iZiI6MTcyODcxMzg5NiwicGF0aCI6Ii83ODc0NjgwNS8zNzU5MzA5OTktZjU2YTJhNDYtYmEyZC00NTZlLWJiOGYtOGFlMWZhMzk1ODUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA2MTgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkZTQ4YTFjMDMzNjI2MWQxM2MyYmExNWNjODM3NzY5MzIxZTgxOWMxYjgwZjM2MTdiY2IwYzhiNjZjM2VhN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._n-QRn2PY7eM_Q6677Lb14t1qcPN3A6Mj9FH42WeliA)
> 
> 请你看清楚我的截图，1.我跟着文档，映射的是8080到容器的80，且访问8080无效，9000才可以。且容器内的nginx.conf并没有配置nginx-ui的代理 ![image](https://private-user-images.githubusercontent.com/36704983/375931141-d58a286b-e76f-4057-8cc9-8e0ead3b8f76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTkyOTAsIm5iZiI6MTcyODcxODk5MCwicGF0aCI6Ii8zNjcwNDk4My8zNzU5MzExNDEtZDU4YTI4NmItZTc2Zi00MDU3LThjYzktOGUwZWFkM2I4Zjc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA3NDMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhNzI4ZWM5MTg0NTdhMGE0ODg3ZTRkZTkzYjA5YTYxMjJiNjZhZDdkOWQyYTlhN2Q3MTFkODk0OTllOTJmOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ruEXbJdcfwljm0heTslM30FXon092EsLpwVELbbNbtw)

1.我建议你看一下nginx的错误日志,
2.他那个反向代理是在/ete/nign/conf.d/里面的
3.你直接吧9000端映射出来也是能用的,相当于就是放弃反向代理

**Comment by YMingPro** [comment]
3. 确实
2. 目前来看，在win运行起来的docker镜像里，默认的/etc/nginx/conf.d目录下为空。
1. 就目前的情况下，看nginx的错误日志意义不大。

综上，其实问题我可以解决，在确定容器内的conf.d目录和nginx.conf文件都没反射代理9000端口情况下我可以手动处理，包括之前说的各种问题，我都可以手动处理解决。
但按文档来说理论上这一切应该是顺利的，但在win下处理这个就会出现了问题，看能不能定位或修复吧。

**Comment by 0xJacky** [comment]
> I'm getting this issue as well on the latest release, not sure why this was closed. I'm running debian 12, well Raspberry Pi OS. It was working fine until I installed nginx. After I installed nginx, nginx-ui didn't work at all, it just returned this error. I will try to troubleshoot via this issue and reading others. Hopefully the translation makes sense.

Please wait for the next beta version, we might address this issue.

**Comment by jflad17** [comment]
> > I'm getting this issue as well on the latest release, not sure why this was closed. I'm running debian 12, well Raspberry Pi OS. It was working fine until I installed nginx. After I installed nginx, nginx-ui didn't work at all, it just returned this error. I will try to troubleshoot via this issue and reading others. Hopefully the translation makes sense.
> 
> Please wait for the next beta version, we might address this issue.

Wow that was a fast reply, I did figure it out in https://github.com/0xJacky/nginx-ui/issues/131 from your comments. It seems when you change the port it doesn't auto redirect to install.
