### ISSUE TITLE
Docker部署怎么配置LogDirWhiteList选项

### ISSUE THREAD

**Issue by dingdian** [0xJacky/nginx-ui#622]
我用docker部署的nginx-ui ,从35 升级到 36版本，在线日志看不到了，但是我没找到哪里可以配置LogDirWhiteList

**Comment by 0xJacky** [comment]
请参考：https://github.com/0xJacky/nginx-ui/issues/606

**Comment by dingdian** [comment]
找不到设置位置

**Comment by 0xJacky** [comment]
展开讲讲

**Comment by dingdian** [comment]
我根据env.md文档中介绍的试着在docker compose配置中添加环境变量NGINX_UI_NGINX_LOG_DIR_WHITE_LIST，但是配置没有生效，然后我想去找配置文件却有不知配置文件在哪里。  现在找到了，app.ini因为做了持久化，所有文件没有更新，缺少这个字段，手动添加后可以了。问题已经解决，谢谢

**Comment by 0xJacky** [comment]
好的
