### ISSUE TITLE
is it normal that both 80 and 9000 point to the nginx ui web interfance?

### ISSUE THREAD

**Issue by LimLLL** [0xJacky/nginx-ui#623]
**Describe the bug**
I set up Nginx UI using Docker and noticed that the behavior on ports 80 and 9000 is the same. I'm not sure if this is normal since I'm still getting familiar with Nginx. The only experience I have is with Nginx Proxy Manager, where the web interface is accessible only through port 81 (equal to 9000) and 80 has a different behavior.

**To Reproduce**
1. set up by using docker (specify the image version to 2.0.0-beta.36)
2. try to access both 80 and 9000 port

**Expected behavior**
Like displaying a page of successful deployment?

**Screenshots**
<img width="797" alt="image" src="https://github.com/user-attachments/assets/ae435aec-616a-45e4-a8a3-43716f127bb1">
<img width="791" alt="image" src="https://github.com/user-attachments/assets/8d08c627-720b-4f2a-ad94-658b7fb2af9e">

**Info (please complete the following information):**
 - Server OS: Ubuntu 22.04
 - Server Arch: x86
 - Nginx UI Version: 2.0.0-beta.36 (2)
 - Your Browser: Chrome

**Comment by 0xJacky** [comment]
Hi @LimLLL ,

This behavior is normal, because we proxy nginx-ui(9000) in the default conf of nginx(80), so when you visit port 80, you will get the same result as port 9000. Normally, this should only happend when you use ip to visit the nginx.
