### ISSUE TITLE
The RSA 8192 SSL certificate is failing to sync to the cluster nodes, resulting in a 406 error.

### ISSUE THREAD

**Issue by LimLLL** [0xJacky/nginx-ui#626]
**Describe the bug**
a 406 error occurs (with `Requested with wrong parameters` prompt) when trying to sync an SSL cert with rsa8192 ker type to a cluster node, I am not sure whether this is designed behavior or a bug as I'm not very familiar with network kind of thing.

**To Reproduce**
1. request a RSA8192 cert
2. and try syncing this cert to any node on the cluster

**Expected behavior**

**Screenshots**
![CleanShot 2024-10-16 at 11 07 33@2x](https://github.com/user-attachments/assets/57a72051-b1f0-4378-9d49-4af1605cd7ab)
<img width="530" alt="CleanShot 2024-10-16 at 11 10 00@2x" src="https://github.com/user-attachments/assets/c832b296-a0b1-4015-a212-fca97e879e05">
<img width="988" alt="CleanShot 2024-10-16 at 11 10 34@2x" src="https://github.com/user-attachments/assets/de12c48e-64bb-4611-a534-5cfbb1c9529a">

![CleanShot 2024-10-16 at 11 08 25@2x](https://github.com/user-attachments/assets/3c16ff77-abbc-42b0-8af5-712fc98c1272)

**Info (please complete the following information):**
 - Server OS: Ubuntu 22.04 for both machines
 - Server Arch: x86
 - Nginx UI Version: 2.0.0-beta.36
 - Your Browser: Chrome

**Additional context**

**Comment by 0xJacky** [comment]
Thanks for your report, this issue has been fixed in [ef7be18](https://github.com/0xJacky/nginx-ui/commit/ef7be186c423f34bdb23a8019e4f309f22a3d1b1), and it will be released in v2-beta.37.
