### ISSUE TITLE
Can not generate certs via letsencrypt.

### ISSUE THREAD

**Issue by tranthibichhlieu** [0xJacky/nginx-ui#632]
Hi
I can not generate letsencrypt certificate for my site. The log said :

_nginx-ui[23175]: [admin.xxx] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized ::xx.xx.xx.xx: Invalid response from http://admin.xxx/.well-known/acme-challenge/a06FHfyvjHkCAa2O6w4fD0xhwesPcs_aYQOt0A2_F_c: 403_

I checked and see that the port : 9180 is not listening. 

Can u help?

**Comment by 0xJacky** [comment]
Hi @tranthibichhlieu,
Please add this location block to your config.
<img width="708" alt="image" src="https://github.com/user-attachments/assets/ea0f9518-3ad0-4d2e-bd3c-1080fb45229d">
<img width="545" alt="image" src="https://github.com/user-attachments/assets/143f84a4-0e36-4c94-a871-26d7bd1af37a">

Then save the config and try to obtain the certificate again.

**Comment by tranthibichhlieu** [comment]
hi, i did it but still get the same error. 
<img width="800" alt="image" src="https://github.com/user-attachments/assets/6bac5f9e-f989-4fa2-bf6b-eb1a88b4c5ab">
As I checked, there is no process listen on port 9180, which is using for HTTP chalenger

**Comment by 0xJacky** [comment]
9180 is only listened during http challenge

**Comment by caph1993** [comment]
For users having the same issue, this configuration exists as a template:

![Image](https://github.com/user-attachments/assets/19a5f466-2770-43b5-a8d4-c07e55a2a369)

I was desperately typing manually and copying-pasting configurations from https://github.com/0xJacky/nginx-ui/issues/167 without success. Then I used the template and it just worked.
