### ISSUE TITLE
This project can be used with more than one llm i guess so docs can be updated

### ISSUE THREAD

**Issue by Greatz08** [0xJacky/nginx-ui#635]
Since this project is giving users option to change BaseUrl, Model so it is possible to use litellm with it i guess ? LItellm supports more than 100+ LLM's and they create open ai compatible endpoint so i guess it is possible to use many more llm's as compared to single open ai which is the only one you mentioned in docs so you can test and update the text in docs and especially can mention that it supports open source llms too with litellm usage and  for small task like nginx conf generation its much better to use free open source llm rather than using paid api in my opinion

**Comment by 0xJacky** [comment]
You're right, last month I used https://github.com/mudler/LocalAI
to deploy a Llama model in my server, I just set the API Base URL in Nginx UI with the local endpoint and also the name of the model (type in), and then I used the Chatbot with Llama.
