### ISSUE TITLE
两台机器的nginx-ui版本相同，配置了集群，但是无法使用

### ISSUE THREAD

**Issue by zy2021314** [0xJacky/nginx-ui#642]
一个主机使用install脚本部署，为centos7.8，版本为 v2.0.0-beta.32
另一台主机使用可执行文件部署，为centos6.5，版本为 v2.0.0-beta.32
并且测试网络连通性OK，但使用集群功能：
显示远程 Nginx UI 版本与本地 Nginx UI版本不兼容。为避免意料之外的错误，请升级远程 Nginx UI，使其与本地版本一致。
想请问集群功能能达成什么效果，如何解决这个报错

**Comment by 0xJacky** [comment]
全部更新为最新版本即可，集群功能可以实现配置批量部署，证书推送等更多功能。

**Comment by zy2021314** [comment]
非常感谢，sry ，最后发现是秘钥需要输入节点自动生成的秘钥。

**Comment by 0xJacky** [comment]
好的
