### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by stig1102** [0xJacky/nginx-ui#665]
Program is starting  and some functions are functional. But error remains;

[GIN] 2024/10/26 - 15:37:35 | 200 |     319.265µs |  .... | GET      "/api/settings/server/name"
Oct 26 15:37:35 ..... nginx-ui[208766]: 2024-10-26 15:37:35        ERROR        router/middleware.go:16        runtime error: integer divide by zero

When going to terminal; 

Connection lost, please refresh the page.
 2024-10-26 15:38:42        ERROR        terminal/pty.go:29        start pty error: exec: no command

**Comment by 0xJacky** [comment]
Remove app.ini and restart nginx-ui agina, make sure that you are using beta.37-patch.2.

**Comment by 0xJacky** [comment]
The terminal issue has been fixed in beta.37-patch.3.
