### ISSUE TITLE
Divide by Zero

### ISSUE THREAD

**Issue by stig1102** [0xJacky/nginx-ui#666]
Everything seems to be working. Now and then de notification "Divide by Zero" (function Site List)

Oct 26 16:22:38 ... nginx-ui[223814]: [GIN] 2024/10/26 - 16:22:38 | 200 |   17.948798ms |  192.168.178.89 | GET      "/api/analytic/init"
Oct 26 16:22:40 ... nginx-ui[223814]: 2024-10-26 16:22:40        ERROR        router/middleware.go:16        runtime error: integer divide by zero
Oct 26 16:22:40 ... nginx-ui[223814]: goroutine 33 [running]:
Oct 26 16:22:40 ... nginx-ui[223814]: github.com/uozi-tech/cosy/router.Init.recovery.func2.1()

**Comment by 0xJacky** [comment]
Did you try to remove the app.ini and reinstall nginx-ui again? I'm sorry that I can not reproduce this issue.

**Comment by 0xJacky** [comment]
If you want to know why a "divide by zero" error occurred, the page size in the app section of app.ini is not set.

**Comment by stig1102** [comment]
Check, I've change it to something  like 1024 and the error is gone. What kind of value makes sense here?
________________________________
Van: Jacky ***@***.***>
Verzonden: zaterdag 26 oktober 2024 16:54
Aan: 0xJacky/nginx-ui ***@***.***>
CC: stig1102 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [0xJacky/nginx-ui] Divide by Zero (Issue #666)


If you want to know why a "divide by zero" error occurred, the page size in the app section of app.ini is not set.

**Comment by 0xJacky** [comment]
Normally we set it to 10 or 20, you can check this link for more details: https://nginxui.com/guide/config-app.html#pagesize.

**Comment by stig1102** [comment]
Oke, Its working thx for al your trouble.
________________________________
Van: Jacky ***@***.***>
Verzonden: zaterdag 26 oktober 2024 17:02
Aan: 0xJacky/nginx-ui ***@***.***>
CC: stig1102 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [0xJacky/nginx-ui] Divide by Zero (Issue #666)


Normally we set it to 10 or 20, you can check this link for more details: https://nginxui.com/guide/config-app.html#pagesize.
