### ISSUE TITLE
Terminal not ditable

### ISSUE THREAD

**Issue by ahmadmssm** [0xJacky/nginx-ui#67]
Hi,

Thank you for this nice GUI.
I have a strange problem, when I open the UI from the IP and port, everything looks nice, however when I use Nginx to forward the io and the port to a local domain the terminal is not editable ar all.

<img width="1248" alt="Screenshot 2023-01-20 at 2 51 30 PM" src="https://user-images.githubusercontent.com/26115953/213699619-f11819ea-04ea-4d2c-a3cd-c1049885bddb.png">

Thanks in advance.

**Comment by 0xJacky** [comment]
It seems that you haven't proxy websocket to nginx-ui?

Please refer to the following documentation for configuration.

https://github.com/0xJacky/nginx-ui#example-of-nginx-reverse-proxy-configuration

**Comment by ahmadmssm** [comment]
I'm not sure.

Here is my config

```
server {
    client_max_body_size 16G;
    listen 80;
    listen [::]:80;
    server_name xxx.yyy.zzz;
    root /var/www/xxx.yyy.zzz/html;
    index index.html index.htm index.nginx-debian.html;
    server_name www.xxx.yyy.zzz xxx.yyy.zzz;
    return 301 https://xxx.yyy.zzz$request_uri;
    location / {
        proxy_pass http://ip:9000/;
        try_files $uri $uri/ =404;
    }
}
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    client_max_body_size 16G;
    include snippets/self-signed.conf;
    include snippets/ssl-params.conf;
    root /var/www/server_ip;
    index index.html index.htm index.nginx-debian.html;
    server_name xxx.yyy.zzz;
    location / {
        proxy_pass http://ip:9000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
    }
}
```

**Comment by 0xJacky** [comment]
add the following content to the top of your configuaration
```
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}
```
and add the following content below `proxy_set_header Upgrade $http_upgrade;`
```
proxy_set_header Connection $connection_upgrade;
```

**Comment by ahmadmssm** [comment]
Fixed, Thank you very much
