### ISSUE TITLE
since beta.36 - error.log - invalid argument

### ISSUE THREAD

**Issue by jiriteach** [0xJacky/nginx-ui#674]
I also came across another bug - 

Since beta.36 - I occassionally see this for Nginx Logs > Error Logs

`seek /var/log/nginx/error.log: invalid argument
`

Rebooting seems to fix it and it shows the error logs but sometimes it will show this.
Any ideas why?

Thanks

**Comment by 0xJacky** [comment]
If the log file is empty it will show this message, maybe I should handle this error.
