### ISSUE TITLE
关于 配置管理 

### ISSUE THREAD

**Issue by surpassoneself** [0xJacky/nginx-ui#681]
您好  新版本发布后，我在个人本地发现一些与您的演示环境不一样的功能，请看截图，这个功能模块在哪里配置？

![image](https://github.com/user-attachments/assets/ea588ba3-89e2-46e7-8cb5-770502b4284d)

问题2：后台配置文件添加重载命令，但是web界面没有该选项。

**Comment by 0xJacky** [comment]
1. 在环境中添加你的其他节点即可
2. 具体是哪个命令，有无截图？

**Comment by 0xJacky** [comment]
由于安全策略，Web 界面不提供命令的直接设置。
由于您没有补充有关于这个 bug 的更多细节，因此我只能猜测是 Nginx 重载这个配置项，这个在我的测试环境中是正常的
<img width="791" alt="image" src="https://github.com/user-attachments/assets/474af81b-380f-4828-99b0-5b0a8663c6a8">
如果您有更多信息补充，请回复这个 issue。
