### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by liuhd92** [0xJacky/nginx-ui#682]
希望添加证书的强制https的开关，这样会简化一些配置操作，希望官网考虑一下

**Comment by liuhd92** [comment]
新增一个开关即可，有的需要强制，有的需要两个协议都有效，使用上会感觉简化很多操作
另外

**Comment by 0xJacky** [comment]
您好，这个已经有了
![image](https://github.com/user-attachments/assets/f64f672c-29e2-4c98-ae05-288f2f15a6cd)
