### ISSUE TITLE
证书列表问题

### ISSUE THREAD

**Issue by liuhd92** [0xJacky/nginx-ui#683]
<img width="1137" alt="image" src="https://github.com/user-attachments/assets/84f2e78a-e348-44d0-b9de-5e7d4cf3912d">
我申请了多个证书，为什么在证书列表中，只能看到最后一个申请的

**Comment by 0xJacky** [comment]
多个证书都是通过 Nginx UI 申请的吗

**Comment by liuhd92** [comment]
是的，我把消失的证书从站点中删除，然后重新添加，就可以出现了

**Comment by 0xJacky** [comment]
我这里无法复现这个问题噢
<img width="1196" alt="image" src="https://github.com/user-attachments/assets/43aa6060-3215-4dce-816e-9b35d8657614">

这两个证书都是 HTTP01 方式 Challenge 签发的，都是在 Nginx UI 中签发的。如果您之前目录中有证书，但是不是通过 Nginx UI 管理的，则需要手动导入。

**Comment by 0xJacky** [comment]
如果您有更多复现此问题的细节，请回复此 issue，感谢您的反馈。
