### ISSUE TITLE
复制站点；页面不会自动刷新

### ISSUE THREAD

**Issue by airsmon** [0xJacky/nginx-ui#684]
提一个UI改进
站点列表中复制后，页面不会自动刷新，持续停留在此页面；点击取消，手动刷新会显示一些warning，体验有些不好
1，建议复制成功后，页面自动刷新；
![image](https://github.com/user-attachments/assets/2e73f7f6-c492-4a2b-8c29-845fd363b9f2)

感谢大佬付出

**Comment by 0xJacky** [comment]
晚上好，请更新到最新版本。

**Comment by airsmon** [comment]
好的，谢谢大佬
