### ISSUE TITLE
多Nginx节点无法同步

### ISSUE THREAD

**Issue by a421101046** [0xJacky/nginx-ui#685]
问题：通过前台新增配置文件后 选中两个节点，点击保存。当前节点有同步，但是远端节点没有同步。

远端抓包结果如下：

![20241029190806](https://github.com/user-attachments/assets/6d6bbdfb-9354-48fe-ba38-6779f697d9cf)
![20241029190756](https://github.com/user-attachments/assets/096972e0-c7ca-405a-b371-e13cc68b6ae8)

**Comment by 0xJacky** [comment]
远端也要更新到最新版本

**Comment by a421101046** [comment]
远端已经是最新版本，与本机版本一致。

两台机器的Linux环境是均为  SUSE Linux Enterprise Server 12 SP5
![捕获](https://github.com/user-attachments/assets/c9635ec7-5356-467b-aa8a-184616189e6d)

**Comment by 0xJacky** [comment]
已修复，感谢您的反馈。全部更新至 v2.0.0-beta.39 即可。

**Comment by a421101046** [comment]
> 已修复，感谢您的反馈。全部更新至v2.0.0-beta.39即可。

经验证同步问题修复，但还存在问题。

现象： 要点击两次保存才能刷新远端节点的本地配置。 第一次点击“保存” 会写到本机对应文件中，第二次点击 “保存”才会 写到远端的对应文件中。
