### ISSUE TITLE
No notification of config syntax errors

### ISSUE THREAD

**Issue by pksml85** [0xJacky/nginx-ui#69]
First of all, thanks for writing this great software! It will help me manage my servers with ease.

I prefer to edit my site config files using the 'Manage Configs' link (because my configs get messed up by the auto-formatting when using the 'Manage Sites' --> 'Modify' method). Upon saving the file in 'Manage Configs', the changes take effect immediately, which is very nice. But if I forget a trailing semicolon or mess something else up, I am completely unaware of it. Nginx-UI just reports success on the save.

My suggestion would be: upon any config change, run 'nginx -t' to make sure the config is valid. If the config is not valid, don't save the file, but instead make a modal pop up with the error message(s) and give options like "Don't save" or "Save anyway."

Note: When clicking the 'reload nginx' graphic at the top of the UI, the same issue exists. It will report success, even if config errors are detected. Again, a modal would be wonderful indicating the error(s) and have the options "Don't reload" or "Reload anyway."

The problem with both of these features as they are is that a particular site (with syntax errors) may stop functioning and you won't be aware of it. Fixing this would make this software so much more helpful.

Thanks for your consideration!

**Comment by 0xJacky** [comment]
Thank you for your appreciation and feedback. This issue will be fixed in next version.
