### ISSUE TITLE
更新最新版后启动错误，无法进入UI

### ISSUE THREAD

**Issue by chung1912** [0xJacky/nginx-ui#691]
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.

 - using env:	export GIN_MODE=release

2024-11-01 13:49:42	FATAL	/home/runner/go/pkg/mod/github.com/uozi-tech/cosy@v1.9.12/model/model.go:61	malformed database schema (idx_sites_path) - invalid rootpage

 - using code:	gin.SetMode(gin.ReleaseMode)

2024/11/01 13:49:42 /home/runner/go/pkg/mod/github.com/uozi-tech/cosy@v1.9.12/model/model.go:51

[error] failed to initialize database, got error malformed database schema (idx_sites_path) - invalid rootpage

**Comment by 0xJacky** [comment]
参考这个解决：https://github.com/0xJacky/nginx-ui/issues/673

**Comment by chung1912** [comment]
> 参考这个解决：#673

先是出现错误：UNIQUE constraint failed: sites.path
我参照这个方法https://github.com/0xJacky/nginx-ui/issues/673，在database.db里面清空 了sites 表，结果就报我发出来的那个错误

**Comment by 0xJacky** [comment]
那可能 sqlite 文件损坏了，重新安装吧

**Comment by chung1912** [comment]
> 那可能 sqlite 文件损坏了，重新安装吧

我里面十几个站点，会需要重新配置？

**Comment by chung1912** [comment]
> 那可能 sqlite 文件损坏了，重新安装吧

重新安装进不去，用户名密码不正确，admin/admin进不去，原来的用户名密码也进不去

**Comment by 0xJacky** [comment]
删掉原来的db

**Comment by chung1912** [comment]
> 删掉原来的db

我直接删除了原来的db，其他配置参数不变，然后重新部署，使用admin/admin登录，提示用户名密码不正确，然后错误日志2024/11/01 14:24:18 /home/runner/work/nginx-ui/nginx-ui/internal/user/login.go:38 record not found

**Comment by chung1912** [comment]
> 删掉原来的db

解决了，要把那个app.ini文件也一并删除才行
