### ISSUE TITLE
unknown directive "geoip2" in /etc/nginx/nginx.conf

### ISSUE THREAD

**Issue by GateCross** [0xJacky/nginx-ui#695]
v2.0.0-beta.39 不支持geoip2吗？
nginx version: nginx/1.27.2
built by gcc 12.2.0 (Debian 12.2.0-14)
built with OpenSSL 3.0.11 19 Sep 2023 (running with OpenSSL 3.0.14 4 Jun 2024)
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-compat --with-file-aio --with-threads --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-http_v3_module --with-mail --with-mail_ssl_module --with-stream --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-cc-opt='-g -O2 -ffile-prefix-map=/data/builder/debuild/nginx-1.27.2/debian/debuild-base/nginx-1.27.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC' --with-ld-opt='-Wl,-z,relro -Wl,-z,now -Wl,--as-needed -pie'
没有看到ngx_http_geoip2_module，是否可以考虑重新编译nginx?

**Comment by Hintay** [comment]
目前 Nginx UI 的 Docker 镜像只会基于 Nginx 官方镜像编译。您可以关注管理单独 Nginx 容器的相关讨论：https://github.com/0xJacky/nginx-ui/discussions/689

当前如果想要定制 Nginx，建议使用 [Linux 安装脚本](https://nginxui.com/zh_CN/guide/install-script-linux.html) 直接管理宿主机的 Nginx。
