### ISSUE TITLE
磁盘IO情况统计不对

### ISSUE THREAD

**Issue by zhouzongyan** [0xJacky/nginx-ui#696]
**Describe the bug**
磁盘的IO一直未零，正常来说应该是不会这样的吧

**To Reproduce**
使用安装脚本（bash <(curl -L -s https://mirror.ghproxy.com/https://raw.githubusercontent.com/0xJacky/nginx-ui/master/install.sh) install -r https://mirror.ghproxy.com/）

后，就一直统计不对

**Expected behavior**
展示磁盘IO的正常情况

**Screenshots**
![image](https://github.com/user-attachments/assets/eb1b8145-7a14-4d59-939a-69ff5d45b530)

**Info (please complete the following information):**
 - Server OS: Debian 12
 - Server Arch: amd64
 - Nginx UI Version: 2.0.0-beta.36 (2)
 - Your Browser: Chrome

**Additional context**
无

**Comment by 0xJacky** [comment]
这是我刚刚安装的 Debian VM

<img width="1330" alt="image" src="https://github.com/user-attachments/assets/4049c6b9-d529-4b1f-8343-85b9069c09c3">

如果您认为 IO 统计有问题，麻烦检查一下 Nginx UI 的日志，看看是否有相关 Error。

**Comment by 0xJacky** [comment]
有尝试过刷新页面吗，我看网络统计居然统计到三天前了

**Comment by zhouzongyan** [comment]
肯定刷新过了，我都装了一个月了

**Comment by 0xJacky** [comment]
那你有试过重启 nginx-ui 吗

**Comment by zhouzongyan** [comment]
![image](https://github.com/user-attachments/assets/c080afc0-8500-4be6-a1fc-1a9db2e2ba05)
试过了，我看接口是有数据的

**Comment by 0xJacky** [comment]
不对，这个看起来 20 号的时候统计的协程就意外退出了

**Comment by zhouzongyan** [comment]
刚没仔细看截图，那应该是这个问题了，现在又重启目前是正常了
