### ISSUE TITLE
Support Cluster Management | 支持集群管理

### ISSUE THREAD

**Issue by zhushiyang** [0xJacky/nginx-ui#70]
产品如果可以支持维护Nginx集群，会让整个产品上升好几个level。比如添加多个节点，组成一个集群，配置存放到git上，修改配置后提交到git，并可以小流量更新到集群中nginx节点上等。
建议参考的产品设计：
1、携程的zeus：https://github.com/ctripcorp/zeus
2、点评的camel：https://github.com/dianping/camel
希望会有启发。。

——————————————-

If this product could support maintaining an Nginx cluster, it would elevate the entire product by several levels. For example, adding multiple nodes to form a cluster, storing configurations in Git, submitting configuration changes to Git, and performing rolling updates to the Nginx nodes in the cluster.

I recommend referring to the following product designs for inspiration:

1. Zeus by Ctrip: https://github.com/ctripcorp/zeus
2. Camel by Dianping: https://github.com/dianping/camel

I hope these will provide useful insights.

**Comment by 0xJacky** [comment]
下一个大版本应该会有优先考虑多节点管理的问题，我现在服务器多了用的也不是很方便，Git 的话得再等等看

**Comment by homegu** [comment]
启动LTS按钮有BUG，有时候点不动 F12控制台出现错误

**Comment by 0xJacky** [comment]
> 启动LTS按钮有BUG，有时候点不动 F12控制台出现错误

麻烦提供一下 nginxui 的版本，浏览器里显示的访问的完整 url以及控制台的错误

**Comment by homegu** [comment]
> > 启动LTS按钮有BUG，有时候点不动 F12控制台出现错误
> 
> 麻烦提供一下 nginxui 的版本，浏览器里显示的访问的完整 url以及控制台的错误

![image](https://user-images.githubusercontent.com/34022483/233527853-35394c06-88e4-4cc6-a3e3-ac8ba2980172.png)

这个bug，切换页面到证书列表，再切回来启动LTS就不会出现这个错误了

**Comment by homegu** [comment]
还有个问题大佬，请教 ，就是 那个证书 为啥不支持泛域 

![image](https://user-images.githubusercontent.com/34022483/233528035-18146b49-edce-4be0-a7a3-0e310c4476cc.png)

**Comment by 0xJacky** [comment]
acme 的限制，泛域名没法 challenge，可以尝试用 SAN 证书，就是 server_name中填写多个域名，以空格间隔

**Comment by 0xJacky** [comment]
> > > 启动LTS按钮有BUG，有时候点不动 F12控制台出现错误
> > 
> > 
> > 麻烦提供一下 nginxui 的版本，浏览器里显示的访问的完整 url以及控制台的错误
> 
> ![image](https://user-images.githubusercontent.com/34022483/233527853-35394c06-88e4-4cc6-a3e3-ac8ba2980172.png)
> 
> 这个bug，切换页面到证书列表，再切回来启动LTS就不会出现这个错误了

离谱，这好像是 antd vue 的锅

**Comment by homegu** [comment]
等待修复，东西很不错 支持，还有个疑问，我想尝试修改nginxui的api路径，但是没找到在哪，就是后台接口的api 我再想加一个层级 /xxx/api 现在是/api

**Comment by 0xJacky** [comment]
> 
确实是 ant design vue 的 issue，我尝试修复一下
https://github.com/vueComponent/ant-design-vue/issues/5763#issuecomment-1177231433

没法修改，你可以在nginx做反向代理的时候通过配置 location 来实现。

**Comment by homegu** [comment]
> > 
> 
> 确实是 ant design vue 的 issue，我尝试修复一下 [vueComponent/ant-design-vue#5763 (comment)](https://github.com/vueComponent/ant-design-vue/issues/5763#issuecomment-1177231433)
> 
> 没法修改，你可以在nginx做反向代理的时候通过配置 location 来实现。

好的 感谢

**Comment by 0xJacky** [comment]
> 

已在 v1.8.1 中修复，等 action 跑完就可以更新。

**Comment by homegu** [comment]
真有你的！

**Comment by homegu** [comment]
错误变了 

![image](https://user-images.githubusercontent.com/34022483/233560492-d2c438a8-faf1-4aef-b866-341cc19c6594.png)

**Comment by 0xJacky** [comment]
> 错误变了
> 
> ![image](https://user-images.githubusercontent.com/34022483/233560492-d2c438a8-faf1-4aef-b866-341cc19c6594.png)

已在 v1.8.2 中修复，如有其他问题请新开 issue 反馈

**Comment by 0xJacky** [comment]
Added in ca3d19a
