### ISSUE TITLE
Stuck at `Getting the certificate, please wait...`

### ISSUE THREAD

**Issue by FluffyDiscord** [0xJacky/nginx-ui#704]
**Describe the bug**
Nginx UI fails to send request to create SSL certificate if its run from Firefox.

**To Reproduce**
1. Create new site with custom config
3. Switch back from Advanced to Basic view
4. Try generating SSL certificate
5. Windows pops up and it gets stuck

**Expected behavior**
Certificate creates normally

**Screenshots**
![image](https://github.com/user-attachments/assets/3008d5df-4428-4d0c-b070-02c8cf218b9a)

**Info (please complete the following information):**
 - Server OS: OpenSuse Leap 15.6
 - Server Arch: x86
 - Nginx UI Version: 2.0.0-beta.39 (2) [Docker]
 - Your Browser: Firefox

**Additional context**
Works using Chrome.

**Comment by 0xJacky** [comment]
Hi @FluffyDiscord, did you run Nginx UI behind a reverse proxy?

**Comment by 0xJacky** [comment]
If so, please modify the configuration file to allow Nginx to handle WebSocket requests for Nginx UI.

```
server {
    listen          80;
    listen          [::]:80;

    server_name     <your_server_name>;
    rewrite ^(.*)$  https://$host$1 permanent;
}

map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

server {
    listen  443       ssl;
    listen  [::]:443  ssl;
    http2   on;

    server_name         <your_server_name>;

    ssl_certificate     /path/to/ssl_cert;
    ssl_certificate_key /path/to/ssl_cert_key;

    location / {
        proxy_set_header    Host                $host;
        proxy_set_header    X-Real-IP           $remote_addr;
        proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Proto   $scheme;
        proxy_http_version  1.1;
        proxy_set_header    Upgrade             $http_upgrade;
        proxy_set_header    Connection          $connection_upgrade;
        proxy_pass          http://127.0.0.1:9000/;
    }
}
```

**Comment by FluffyDiscord** [comment]
No, it's not run behind reverse proxy. Also I noticed that the error I sent in screenshot happens also on Chrome, but at random. Refreshing page helps.

**Comment by Hintay** [comment]
Hello, can you provide the running logs of the nginx ui at the time of this issue?

**Comment by FluffyDiscord** [comment]
Hi, there is nothing to send. It's a cors issue as mentioned before. You can see the only error on the screenshot. The request was blocked by browser apparently, so nginx doesn't even see it

**Comment by 0xJacky** [comment]
No, this is not a cors issue, it seems that your site configuration file name is not equal to the server_name. This is a known bug, and I will fix it later.

**Comment by 0xJacky** [comment]
I will fix it later.
