### ISSUE TITLE
/api/notifications/live 请求返回504，其他请求没问题。有无遇到过这种情况？

### ISSUE THREAD

**Issue by Ngwind** [0xJacky/nginx-ui#705]
**Describe the bug**

我使用的是docker部署，网络模式是host。
在日志中 发现"/api/notifications/live"这个请求处理了 1min 返回200, 但是在浏览器f12里看到是报504 网关超时。 

**Screenshots**
![image](https://github.com/user-attachments/assets/6931cd4c-9fe9-4aad-ad2f-8f9d1f70f0e6)

![image](https://github.com/user-attachments/assets/f06445c0-4b8b-4374-ae94-d835b6387c40)

**Info (please complete the following information):**
 - Server OS: [Debian 12 ]
 - Server Arch: [x86]
 - Nginx UI Version: 2.0.0-beta.39 (2)
 - Your Browser: [Chrome]

**Comment by 0xJacky** [comment]
正常的 不用管，后面考虑优化

**Comment by 0xJacky** [comment]
重新拉取一下 latest 镜像，已经优化了
