### ISSUE TITLE
首页/ 网站管理/ 站点列表 排序有问题

### ISSUE THREAD

**Issue by devefx** [0xJacky/nginx-ui#712]
**Describe the bug**
除了第一列“名称”，剩余的列排序实际上依然按照“名称”排序的

**To Reproduce**
路径：首页/ 网站管理/ 站点列表

**Expected behavior**
正确的排序

**Screenshots**

**Info (please complete the following information):**
 - Server OS: debian12
 - Server Arch: x32/64
 - Nginx UI Version: Version: 2.0.0-beta.39 (2)
 - Your Browser: [e.g. Chrome

**Additional context**

**Comment by 0xJacky** [comment]
感谢反馈，已在 902aa287 修复，下个版本发布。
