### ISSUE TITLE
证书怎么申请？

### ISSUE THREAD

**Issue by a506488043** [0xJacky/nginx-ui#713]
页面证书怎么申请？怎么自动续期？
看了文档没有说明呀。
证书还要自己申请的？

**Comment by 0xJacky** [comment]
新用户，建议从 网站管理/添加网站 跟随步骤，有自动证书。
高级用户，server 中含有 listen 443 ssl 等指令，会显示开关
![image](https://github.com/user-attachments/assets/08bfc947-d6f7-4821-9047-4a3b307831b0)

**Comment by a506488043** [comment]
> 新用户，建议从 网站管理/添加网站 跟随步骤，有自动证书。 高级用户，server 中含有 listen 443 ssl 等指令，会显示开关 ![image](https://private-user-images.githubusercontent.com/13096985/384695257-08bfc947-d6f7-4821-9047-4a3b307831b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNDgyOTksIm5iZiI6MTczMTI0Nzk5OSwicGF0aCI6Ii8xMzA5Njk4NS8zODQ2OTUyNTctMDhiZmM5NDctZDZmNy00ODIxLTkwNDctNGEzYjMwNzgzMWIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDE0MTMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzOGQxOTNjMmQwMGIwODgzZmRkMDQyOTQ4NzY0MDNhMzliYTRjY2ZlNjU4MWM4YjdlNzVmZGE4YmI3NzI2ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PiRnvZO_s56stqu1JzrUvyv_-ubidqonUxfAqnOJGYI)

网站的提示信息有点不太明确，已经有了证书了，应该提示开启证书续签。😀

**Comment by a506488043** [comment]
> 新用户，建议从 网站管理/添加网站 跟随步骤，有自动证书。 高级用户，server 中含有 listen 443 ssl 等指令，会显示开关 ![image](https://private-user-images.githubusercontent.com/13096985/384695257-08bfc947-d6f7-4821-9047-4a3b307831b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNTAzNzYsIm5iZiI6MTczMTI1MDA3NiwicGF0aCI6Ii8xMzA5Njk4NS8zODQ2OTUyNTctMDhiZmM5NDctZDZmNy00ODIxLTkwNDctNGEzYjMwNzgzMWIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDE0NDc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MWM3NjVjMWQ5MzFiYTk0NmUzODRlOTQxNzVlZTBkYmE4ODYzNGU1MjRjMjBiNzIzOTQ5OWU5ZjI3YjQwNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6KUHBBnZdjt95F022VR3kkEHgj9v1oIjZQHWDl4r9sk)

有怎么配置申请证书的文档吗？我配置的阿里云DNS 老是被拒绝呀；DNS 也不知道怎么加。
obtain certificate error: error: one or more domains had a problem: [cloud.saiita.cn] [cloud.saiita.cn] acme: error presenting token: alicloud: zone cn. not found in AliDNS for domain _acme-challenge.cloud.saiita.cn.
