### ISSUE TITLE
关于使用terminal的问题

### ISSUE THREAD

**Issue by jxs1211** [0xJacky/nginx-ui#714]
**Describe the bug**
- 打开terminal，显示输入user和password，不知道应该用什么user和password，没有任何提示
- 想要将登陆prompt设置成zsh，文档里面没说具体怎么设置

**To Reproduce**

**Expected behavior**
希望可以自定义登陆的prompt

**Screenshots**
```sh
e37e0c22191e login: 
Password: 

Login incorrect
e37e0c22191e login: 
Login timed out after 60 seconds.
```

**Info (please complete the following information):**
 - Server OS: [MacOS Sonoma 14.5]
 - Server Arch: [x86]
 - Nginx UI Version: [docker image: uozi/nginx-ui:latest]
 - Your Browser: [Chrome]

**Additional context**

**Comment by 0xJacky** [comment]
文档说了的 https://nginxui.com/zh_CN/guide/config-terminal.html
