### ISSUE TITLE
请支持一下RISC-V

### ISSUE THREAD

**Issue by Athlong** [0xJacky/nginx-ui#715]
**Describe the bug**
请支持一下RISC-V

**Comment by 0xJacky** [comment]
这个进度将会加快，如果有人赞助我们开发板的话（狗头

**Comment by 0xJacky** [comment]
已在 https://github.com/0xJacky/nginx-ui/pull/728 中新增 RISC-V 架构的构建，预计在 beta.40 中发布。

**Comment by Hintay** [comment]
@Athlong 我们已经发布了 beta.40，由于我们手边没有 RISC-V 的设备，如果可以的话请在测试后反馈结果给我们~

**Comment by Athlong** [comment]
yes it's work now

**Comment by Athlong** [comment]
![image](https://github.com/user-attachments/assets/b1861726-e24a-4cab-a922-b7c492dd9365)
Thanks
