### ISSUE TITLE
docker启动用户名和密码是多少

### ISSUE THREAD

**Issue by jxs1211** [0xJacky/nginx-ui#716]
**Describe the bug**
admin登陆失败: Incorrect username or password

**To Reproduce**
n/a

**Expected behavior**
可以正常登陆

**Screenshots**

**Info (please complete the following information):**
 - Server OS: [Mac sonoma 14.5]
 - Server Arch: [x64]
 - Nginx UI Version: [uozi/nginx-ui:latest]
 - Your Browser: [Chrome]

**Additional context**
```docker
version: '3'

services:
  nginx-ui:
    image: uozi/nginx-ui:latest
    container_name: nginx-ui
    # restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./nginx:/etc/nginx          # Changed to local directory
      - ./nginx-ui:/etc/nginx-ui    # Changed to local directory
      - ./www:/var/www             # Changed to local directory
    ports:
      - "8080:80"
      - "8443:443"
```

**Comment by 0xJacky** [comment]
访问 ip:port/#/install 完成安装步骤
