### ISSUE TITLE
可以通过casdoor给反代的服务加认证吗

### ISSUE THREAD

**Issue by 1amfine2333** [0xJacky/nginx-ui#719]
可以通过casdoor给反代的服务加认证吗

**Comment by 0xJacky** [comment]
如果你的服务支持 Casdoor 就可以直接接入，这个跟 Nginx UI 没有关系

**Comment by nomeguy** [comment]
@1amfine2333 CasWAF是Casbin社区推出的开源WAF + 反向代理组件，支持对反向代理流量强制完成基于Casdoor的身份认证：https://github.com/casbin/caswaf

**Comment by 1amfine2333** [comment]
> @1amfine2333 CasWAF是Casbin社区推出的开源WAF + 反向代理组件，支持对反向代理流量强制完成基于Casdoor的身份认证：https://github.com/casbin/caswaf

感谢，我去看下

**Comment by 1amfine2333** [comment]
> 如果你的服务支持 Casdoor 就可以直接接入，这个跟 Nginx UI 没有关系

了解了
