### ISSUE TITLE
Support other system init

### ISSUE THREAD

**Issue by mohamad-supangat** [0xJacky/nginx-ui#72]
Is it possible to support other init systems than systemd, such as openrc / dinit

Maybe a design like the custom nginx restart command, so you can easily restart nginx from the web ui

**Comment by 0xJacky** [comment]
Do you mean to support other init systems to control nginx? We just use `nginx -t`, `nginx -s reload` to send signal to nginx process. The reason we check whether `systemd` is available is that we want to use `systemd` to control nginx-ui.
