### ISSUE TITLE
考虑保证DockerHub上的latest版本是对外可用的

### ISSUE THREAD

**Issue by VictorZhang-1928** [0xJacky/nginx-ui#721]
一般从docker上拉取镜像都会使用大版本或者latest版本，所以希望后期能保证latest是对外可用的版本，测试等非对外可用版本考虑使用snapshot或者其他tag。
<img width="761" alt="image" src="https://github.com/user-attachments/assets/6e28dc93-b120-4a4b-b43e-0bc6adf009ea">

**Comment by Hintay** [comment]
已经修改 docker 镜像的标签，分为分支、SHA 值、Tag 以及最后发布的 release，下次发布后 latest 版本应该可以保证对外可用。
