### ISSUE TITLE
关于关闭TOTP二步验证

### ISSUE THREAD

**Issue by LiuMuAoo** [0xJacky/nginx-ui#722]
我觉得关闭TOTP与重置TOTP的入口应当区分开来，不应当都是用恢复代码来执行

**Comment by 0xJacky** [comment]
那应该用什么来认证？

**Comment by LiuMuAoo** [comment]
> 那应该用什么来认证？
我觉得是两个操作。
1. 重置TOTP
这个适用于我遗失掉了我的TOTP代码，使用恢复代码来强制重置TOTP。
2.关闭TOTP
比如我想停用TOTP的时候，不是直接使用恢复代码来强制重置。可以设置校验TOTP代码或者直接提供一个关闭按钮（因为登陆的时候就已经校验过一次）进行关闭。
