### ISSUE TITLE
证书更新不成功

### ISSUE THREAD

**Issue by ftyszyx** [0xJacky/nginx-ui#723]
无法获取证书了
issue cert get acme user error: get default user error: record not found
![image](https://github.com/user-attachments/assets/54663e70-fd3f-4f8c-89c3-a66d2a0ad34e)

**Comment by ftyszyx** [comment]
![image](https://github.com/user-attachments/assets/d576e8e2-0001-43a5-8991-e74d21aa05b7)

**Comment by 0xJacky** [comment]
如果提示系统默认用户不存在，请手动选定 ACME 用户JackyOn Nov 14, 2024, at 4:36 PM, ftyszyx ***@***.***> wrote:﻿
image.png (view on web)

**Comment by ftyszyx** [comment]
已经选了
![image](https://github.com/user-attachments/assets/cb7e9bf3-358f-43c1-8f8d-7fbf83d9695b)

**Comment by ftyszyx** [comment]
证书更新不成功，有解决方案吗？

**Comment by ftyszyx** [comment]
acme用户是有效的

**Comment by 0xJacky** [comment]
我会尝试复现这个问题，但是默认用户确实不见了，你有删过或者改过名字吗

**Comment by 0xJacky** [comment]
安装/更新之后系统没有自动创建默认用户吗，这个是你手动新建的？如果创建失败了可能是网络问题，一般重启会重新注册

**Comment by ftyszyx** [comment]
安装/更新之后系统没有自动创建默认用户吗?（忘了）
应该是手动新建的。不过已经稳定运行半年多了，所以之前的配置应该是没问题的。
网络问题，一般重启会重新注册。我重启了container，还是不行

**Comment by 0xJacky** [comment]
我晚些时候再回复

**Comment by 0xJacky** [comment]
Docker 镜像版本是最新的吗

**Comment by 0xJacky** [comment]
确实有 bug，用户没保存下来，我修复一下

**Comment by 0xJacky** [comment]
麻烦检查配置文件是否自动迁移成功，可能有些特殊情况下导致 Nginx UI 的配置从 v1 迁移到 v2 失败。
目前获取默认用户的逻辑就是

```
[cert]
Email = 用户邮箱
CADir = 自定义 CADir
```

用户邮箱+CADir（如果为空就是默认的 https://acme-v02.api.letsencrypt.org/directory）查找用户是否存在。

关于手动指定用户但是仍无法签发，这个是一个小 bug，临时解决方案是修改完 ACME User 后点击一次保存，再点击更新证书。

**Comment by ftyszyx** [comment]
![image](https://github.com/user-attachments/assets/c49a9439-bb0b-49e8-8e92-754b4b35de27)
已经清空，并重启了系统，但还是不行
![image](https://github.com/user-attachments/assets/69290a35-ebad-4ac9-ac30-96eec5c9226c)

**Comment by 0xJacky** [comment]
> ![image](https://github.com/user-attachments/assets/c49a9439-bb0b-49e8-8e92-754b4b35de27)
> 
> 已经清空，并重启了系统，但还是不行
> 
> ![image](https://github.com/user-attachments/assets/69290a35-ebad-4ac9-ac30-96eec5c9226c)
> 
> 

Email 设置一下，再重启 Nginx UI
