### ISSUE TITLE
无法新建文件 you are not allowed to rename a file outside of the nginx config path

### ISSUE THREAD

**Issue by xe5700** [0xJacky/nginx-ui#724]
**Describe the bug**
新建文件的文件位置错误

**To Reproduce**
1. 点击配置管理
2. 新建文件
3. 点击重命名，输入文件名，点确定。
4. 退出登录 提示 you are not allowed to rename a file outside of the nginx config path

**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
 - truenas scale 24.04.1.1
 - amd64
 - 2.0.0-beta.39 
 - microsoft edge

**Additional context**

**Comment by chenchaoyun0** [comment]
"I have also encountered this issue, how can I resolve it?"

**Comment by 0xJacky** [comment]
Hi @chenchaoyun0, please upgrade to the latest version, we had fixed it last weekend.
