### ISSUE TITLE
No code formatting for Manage Sites --> Advanced

### ISSUE THREAD

**Issue by pksml85** [0xJacky/nginx-ui#73]
First of all, thanks for getting Issue #69 tackled so quickly! Much appreciated.

When I go to Manage Sites --> Modify --> Advanced, my nginx code is automatically formatted. I have a rather complicated configuration for my site (complicated at least in the eyes of the parser), and the auto formatting breaks my config. (While I can modify my site config through Manage Configs, it's a bit more of a hassle.)

So **my proposal is when clicking the 'Advanced' toggle button in Manage Sites, don't automatically format the code**. This way advanced users won't have their config messed up. (I also really like white space in my config for ease of understanding and I lose this with auto formatting.)

You might consider having a button at the bottom of the screen to auto format like you do for Manage Configs for those who would like to use it. This would greatly improve usability. Thanks!

**Comment by 0xJacky** [comment]
We use [gonginx](https://github.com/tufanbarisyildirim/gonginx) to build the configuration content from the JSON object (ngx object). The ngx object is parsed by gonginx. When you edit the configuration in basic mode, you are actually editing the ngx object. When you click the "Advance" toggle button, the ngx object is sent to the backend, and the configuration content is rendered in the frontend, with automatic code formatting. However, gonginx may not always work as expected and cause issues in your environment.

I plan to add a setting option in the preference page that will force the use of advance mode in the site editing page, implementing your proposal. However, this will result in the loss of some functions in basic mode, such as "Encrypting the website with Let's Encrypt".

**Comment by tufanbarisyildirim** [comment]
Hi @pksml85 can I have your example config file to improve [gonginx](https://github.com/tufanbarisyildirim/gonginx)?

**Comment by 0xJacky** [comment]
Added in [defd814](https://github.com/0xJacky/nginx-ui/commit/defd81461e7fe70a98a10dabea46f3e5a08f22a3).

The system now will save your preference of edior mode. For example, after enabling advanced mode, the next time you enter the editor for this domain, it will use advanced mode by default.

But we still hope you can give us more information of the problems you met, thanks.

**Comment by pksml85** [comment]
> Hi @pksml85 can I have your example config file to improve [gonginx](https://github.com/tufanbarisyildirim/gonginx)?

Sorry for the delay... but here is the example. GoNginx destroys my location blocks.

Here is [my original config code](https://pastebin.com/aXW7e8tC) and here is the [mangled code from GoNginx](https://pastebin.com/tjFakDHE)

**Comment by 0xJacky** [comment]
Try to upgrade nginx-ui to v1.8.3? This issue might be fixed in previous version.

**Comment by tufanbarisyildirim** [comment]
Hi @0xJacky  and @pksml85  can you please test this https://github.com/tufanbarisyildirim/gonginx/pull/18 (issue-17 is the branch) to see if it works for your nginx conf?  Thanks again for finding it!

**Comment by 0xJacky** [comment]
Thanks for your work, now it works perfactly!

![截屏2023-05-08 下午9 08 52](https://user-images.githubusercontent.com/13096985/236832738-aa7e0b15-2667-45e6-8b60-c05f29234dce.png)

![截屏2023-05-08 下午9 09 01](https://user-images.githubusercontent.com/13096985/236832804-343b11ff-3f9a-4816-b07d-60094c090ba9.png)

**Comment by tufanbarisyildirim** [comment]
Thanks for that quick confirmation @0xJacky !
