### ISSUE TITLE
升级的时候他说找不到.nginx-ui.old

### ISSUE THREAD

**Issue by Hyperionml** [0xJacky/nginx-ui#732]
升级的时候他说找不到.nginx-ui.old

![image](https://github.com/user-attachments/assets/ddb8b85e-2826-465a-8419-170d0fe05322)
![image](https://github.com/user-attachments/assets/13f0267d-6f0c-4eb0-828d-23a877ce2f9d)

 - Server OS: debian 12.7
 - Server Arch: x86
 - Nginx UI Version: 2.0.0-beta.39 (4)

**Comment by 0xJacky** [comment]
很遗憾，如果遇到这个问题只能重新使用脚本安装（不会丢失数据）。

```
bash <(curl -L -s https://mirror.ghproxy.com/https://raw.githubusercontent.com/0xJacky/nginx-ui/master/install.sh) help
```
