### ISSUE TITLE
自动续期不工作 

### ISSUE THREAD

**Issue by hale177** [0xJacky/nginx-ui#74]
**版本 ：**  nginx-ui  v1.6.8 
**安装方式：** docker-compose 

业务访问提示非安全才发现证书过期了
如图所示，显示0天已过期，正常应该是到期前一个月就自动续期 

<img width="527" alt="1675391492(1)" src="https://user-images.githubusercontent.com/116779418/216498524-71b63a61-1416-48ab-80bc-6ecbfba5f075.png">

然后手动点击续期，续期流程正常没问题。
<img width="479" alt="1675391592" src="https://user-images.githubusercontent.com/116779418/216498747-175a3509-23d4-444a-8c0b-bbff24ca3900.png">

**Comment by 0xJacky** [comment]
如果是早期1.6版本之前开的自动续期，升级之后要手动重新打开续期，相关信息打印在了日志中。JackyOn Feb 3, 2023, at 10:35 AM, hale177 ***@***.***> wrote:﻿
业务直接非安全才发现证书过期了
如图所示，显示0天已过期，正常应该是到期前一个月就自动续期

如果手动点击续期，续期流程正常没问题。

**版本 ：**nginx-ui  v1.6.8
安装方式： docker-compose

**Comment by hale177** [comment]
并没有 ，我一种用的 1.6 以上版本 
有过一次升级，从1.6.3 docker image 升到1.6.8  ，没其他变动

**Comment by 0xJacky** [comment]
好的，我再看看能不能复现

**Comment by 0xJacky** [comment]
目前已经确认了一个问题，如果首次安装后从未重启过 nginx-ui，定时任务就不会启动，这个已经在 #bf3edfa 中修复了。
接下来将会优化证书模块，包括增加签发日志、优化 SAN，缩短续期间隔，这些改动将在 v1.7.6 发布。

**Comment by 0xJacky** [comment]
已在 #82  中修复
