### ISSUE TITLE
How can I see the affect with hot-reload after modified frontend code

### ISSUE THREAD

**Issue by jxs1211** [0xJacky/nginx-ui#740]
**Describe the bug**
I changed the frontend code, and need to re-build the code and reboot with `go run main.go` to see the affect on web, how can I see the affect with hot-reload?

**Comment by 0xJacky** [comment]
In the project root, execute the following commands:
```
cd app
pnpm install
pnpm dev
```
Then you can start the dev server of the frontend.

**Comment by jxs1211** [comment]
> In the project root, execute the following commands:
> 
> ```
> cd app
> pnpm install
> pnpm dev
> ```
> 
> Then you can start the dev server of the frontend.

I can't login in through the dev server listening on 3002:
```sh
Error: connect ECONNREFUSED 127.0.0.1:9001
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16)
7:42:16 PM [vite] http proxy error: /api/login
Error: connect ECONNREFUSED 127.0.0.1:9001
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16)
7:42:31 PM [vite] http proxy error: /api/login
Error: connect ECONNREFUSED 127.0.0.1:9001
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16) (x2)
```
but I can access server listening on 9000.
