### ISSUE TITLE
这个地方刷新也没作用，不知道为啥

### ISSUE THREAD

**Issue by zjqwll** [0xJacky/nginx-ui#741]
![1731994599210](https://github.com/user-attachments/assets/2b568a8e-6ae5-48bf-822c-d59829b29d6d)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
 - Server OS: [e.g. Ubuntu 22.04]
 - Server Arch: [e.g. x86, aach64]
 - Nginx UI Version: [e.g. 1.8.0]
 - Your Browser: [e.g. Chrome, Safari, Firefox]

**Additional context**

**Comment by zjqwll** [comment]
systemctl restart nginx-ui，已经重启过了

**Comment by zjqwll** [comment]
![1731994810265](https://github.com/user-attachments/assets/baa2825c-6e50-4131-b7e4-f492795e8a95)

**Comment by 0xJacky** [comment]
第一个问题，请确保已开启 WebSocket 的代理：https://nginxui.com/zh_CN/guide/nginx-proxy-example.html
第二个问题：https://nginxui.com/zh_CN/guide/config-nginx.html#logdirwhitelist

**Comment by zjqwll** [comment]
保持联系哦~

**Comment by zjqwll** [comment]
![1731996154893](https://github.com/user-attachments/assets/db75adb6-cbe2-4f18-bdbb-50a64b43cef4)
![1731996222692](https://github.com/user-attachments/assets/95e6b36a-cab4-45a7-9dea-6a4d5775c974)
