### ISSUE TITLE
适配IDP

### ISSUE THREAD

**Issue by Cikaros** [0xJacky/nginx-ui#743]
目前用户数据均由项目自行管理，这里可能出现的问题有很多，毕竟这不是一个专业化的用户管理系统。建议适配认证服务器，将数据托管给三方身份验证服务器。例如ZITADEL

**Comment by 0xJacky** [comment]
您好，现在已经适配 Casdoor 作为外部认证。

**Comment by Cikaros** [comment]
很抱歉，我并未从演示系统中找到对应的OAuth配置项

**Comment by Cikaros** [comment]
在安装配置中找到了，是需要在安装部署时指定配置，无法动态的追加OAuth配置

**Comment by 0xJacky** [comment]
https://nginxui.com/zh_CN/guide/config-casdoor.html
