### ISSUE TITLE
两个功能性小问题。配置和日志相关、已经查阅完官方手册但是其中并没有说明

### ISSUE THREAD

**Issue by myworld6** [0xJacky/nginx-ui#744]
1、我之前nginx就有网站。能否导入自己已经有的网站呢？
2、仪表盘内显示的流量统计是以什么为单位啊？是以本次开机到现在时间吗？

**Comment by 0xJacky** [comment]
第一个问题，文档已经说明了
<img width="740" alt="image" src="https://github.com/user-attachments/assets/607b06ee-02fc-4fce-98a9-5f592edfdd1a">

第二个问题，是以本次开机到现在。
