### ISSUE TITLE
请求docker镜像中的nginx添加webdav增强模块 nginx-dav-ext-module

### ISSUE THREAD

**Issue by bigoovip** [0xJacky/nginx-ui#745]
请求为docker镜像中的nginx添加webdav增强模块 nginx-dav-ext-module

nginx自己的webdav模块 `ngx_http_dav_module` 没有完整的支持webdav，请求在制作docker镜像时，为nginx添加webdav增强模块 `nginx-dav-ext-module`，该模块项目为 [https://github.com/mid1221213/nginx-dav-ext-module/](https://github.com/mid1221213/nginx-dav-ext-module/)，可为nginx 的 webdav 添加 `ROPFIND,OPTIONS,LOCK,UNLOCK` 支持。

**使用方法可参考[项目文档](https://github.com/mid1221213/nginx-dav-ext-module)**

使用模块构建 `nginx` （**编译时要同时添加`ngx_http_dav_module`模块 ：`--with-http_dav_module`** ）：
```
# static module
$ ./configure --with-http_dav_module --add-module=/path/to/nginx-dav-ext-module

# dynamic module
$ ./configure --with-http_dav_module --add-dynamic-module=/path/to/nginx-dav-ext-module
```

**Comment by 0xJacky** [comment]
您好，由于 docker 使用 apt 直接安装的 nginx，我们目前没有使用自编译 Nginx 的计划，https://github.com/0xJacky/nginx-ui/issues/607。

这种情况下更推荐您使用宿主机的 Nginx。
