### ISSUE TITLE
能否增加一个服务器日志路径的配置？

### ISSUE THREAD

**Issue by jinlin-teck** [0xJacky/nginx-ui#746]
首先感谢开发人员写了这么优秀的软件。
我使用的是openwrt系统，直接二进制运行的，写了openwrt启动服务，运行良好。
就是nginx-ui的日志默认就直接打印到控制台了，这导致我openwrt的系统日志太多了影响查阅正常的系统运行日志。
能否在app.ini里添加一个日志路径的配置，方便专门管理日志？
谢谢！

**Comment by Hintay** [comment]
请使用OpenWrt的服务来管理日志

**Comment by jinlin-teck** [comment]
ok
