### ISSUE TITLE
Streams configs in the browser are not shown correctly

### ISSUE THREAD

**Issue by bitsky6** [0xJacky/nginx-ui#752]
**Describe the bug**
Frontend is not loading/displaying correctly the Streams configs after saved.

**To Reproduce**
1. Go to 'Manage Streams'
2. Click on 'Any of the streams'
3. Go to 'Advanced mode'

**Expected behavior**
After I save the config to show me as it is, currently it flattens it and many of the lines disapears.

**Screenshots**
![image](https://github.com/user-attachments/assets/5908fdb8-2267-4c88-8d9a-6d138cc8c75f)
![image](https://github.com/user-attachments/assets/4809996b-78ff-43e7-ba46-91336fa84c4f)

**Info (please complete the following information):**
 - Server OS: Docker
 - Nginx UI Version: v2.0.0-b40
 - Your Browser: Chrome

**Additional context**

**Comment by 0xJacky** [comment]
Hi @bitsky6, you should not use the `stream` directive to wrap all your servers. You should put the `stream` directive in nginx.conf like:

```
http {
   //...
}

stream {
     include /etc/nginx/stream-enabled/*;
}
```

Next, you can create a config file with multiple servers in `/etc/nginx/stream-available`. 

With these changes, it should work as we expect.
