### ISSUE TITLE
上传一个最新版的配置文件可好？

### ISSUE THREAD

**Issue by accerror** [0xJacky/nginx-ui#756]
我在配置的时候看了手册。发现有很多对不上现在项目的配置文件内容。上传一个最新版的配置可以么？这样方便大家对照手册来修改配置文件。另外这个密码忘记了只能重新配置么？

**Comment by 0xJacky** [comment]
你好，现在手册就是最新版的配置文件。另外，忘记密码只能重新配置。

**Comment by 0xJacky** [comment]
dev 分支的配置文件请参考：https://github.com/0xJacky/nginx-ui/blob/dev/app.example.ini
