### ISSUE TITLE
请教下这个证书为啥同步不过来？

### ISSUE THREAD

**Issue by zjqwll** [0xJacky/nginx-ui#767]
![1732773450156](https://github.com/user-attachments/assets/c0b42a56-66c5-4b2e-aa94-f1d34996052e)
![1732773515311](https://github.com/user-attachments/assets/c06ededd-1944-4c78-b3fb-bd0d61d3c8a5)

**Comment by 0xJacky** [comment]
手动添加的吗

**Comment by zjqwll** [comment]
> 手动添加的吗

我在app.ini配置了路径，但是页面没读出来，然后手动添加就是上面图上的样子。

**Comment by 0xJacky** [comment]
系统不会自动读取已存在的证书的，只能通过手动添加，具体添加之后不显示的问题，这边暂时没法复现。

**Comment by zjqwll** [comment]
> 系统不会自动读取已存在的证书的，只能通过手动添加，具体添加之后不显示的问题，这边暂时没法复现。
手动添加证书，保存后弹出提示：
ssl_certificate_path: /usr/local/soft/cert/16086330_api.baidu.com_nginx/api.baidu.com.pem is not under the nginx conf path: /usr/local/soft/nginx
但是实际上，我的证书的确是在/usr/local/soft/cert/16086330_api.baidu.com_nginx/目录下

**Comment by zjqwll** [comment]
> 系统不会自动读取已存在的证书的，只能通过手动添加，具体添加之后不显示的问题，这边暂时没法复现。

是不是证书一定要放在nginx目录下面？

**Comment by 0xJacky** [comment]
> > 系统不会自动读取已存在的证书的，只能通过手动添加，具体添加之后不显示的问题，这边暂时没法复现。
> 
> 
> 
> 是不是证书一定要放在nginx目录下面？

是的，这个是为了安全。

**Comment by zjqwll** [comment]
> > > 系统不会自动读取已存在的证书的，只能通过手动添加，具体添加之后不显示的问题，这边暂时没法复现。
> > 
> > 
> > 是不是证书一定要放在nginx目录下面？
> 
> 是的，这个是为了安全。

原来如此，那么是放在哪个目录呢，我移动下

**Comment by 0xJacky** [comment]
> > > > 系统不会自动读取已存在的证书的，只能通过手动添加，具体添加之后不显示的问题，这边暂时没法复现。
> > > 
> > > 
> > > 是不是证书一定要放在nginx目录下面？
> > 
> > 
> > 是的，这个是为了安全。
> 
> 原来如此，那么是放在哪个目录呢，我移动下
放在 Nginx 的目录下啊

**Comment by zjqwll** [comment]
> > > > > 系统不会自动读取已存在的证书的，只能通过手动添加，具体添加之后不显示的问题，这边暂时没法复现。
> > > > 
> > > > 
> > > > 是不是证书一定要放在nginx目录下面？
> > > 
> > > 
> > > 是的，这个是为了安全。
> > 
> > 
> > 原来如此，那么是放在哪个目录呢，我移动下
> 
> 放在 Nginx 的目录下啊

好的，我试试

**Comment by zjqwll** [comment]
可以了，谢谢。
