### ISSUE TITLE
Why can't I see http requests that coming in and out 

### ISSUE THREAD

**Issue by Jobians** [0xJacky/nginx-ui#768]

**Comment by 0xJacky** [comment]
Hi @Jobians, I am sorry that I didn't understand your question. Can you provide me more details like screenshots or logs?

**Comment by Jobians** [comment]
I mean like http requests monitoring

**Comment by Jobians** [comment]
Like if someone send http requests to my website I will see if it successful or not

**Comment by 0xJacky** [comment]
Sorry, Nginx UI is not a traffic monitor.

**Comment by Jobians** [comment]
But can you implement traffic monitor?
