### ISSUE TITLE
怎么识别手动安装的nginx

### ISSUE THREAD

**Issue by hehe210417** [0xJacky/nginx-ui#770]
服务器上的nginx是手动安装的，安装的目录为/usr/local/nginx，怎么才能设置这个目录，谢谢

**Comment by 0xJacky** [comment]
如果正确配置了环境变量，nginx-ui 将会自动检测，如果检测不到，请根据文档手动指定目录 https://nginxui.com/zh_CN/guide/config-nginx.html，配置文件 app.ini，脚本安装的话在 /usr/local/etc/nginx-ui 下
