### ISSUE TITLE
关于配置的一些疑问

### ISSUE THREAD

**Issue by tengyinan1994** [0xJacky/nginx-ui#773]
1. 我修改配置文件和在页面上配置不是同步的吗，例如我在页面添加一个server后，配置文件里不会更新吗，反之，我更新配置文件后，页面上的站点列表不会更新吗？
2. 没有批量导入功能吗，否则我非常多的server，一个一个新建太麻烦了。 

样式很好看，可以格式化配置文件的功能也很满足我的需求，我非常希望我的团队可以使用😄

**Comment by 0xJacky** [comment]
第一点，我不太明白您的使用场景和配置，正常来说是同步的，本质上列表就是读了配置文件夹里的文件

第二点，请查看 https://nginxui.com/zh_CN/guide/getting-started.html#%E4%BD%BF%E7%94%A8%E5%89%8D%E6%B3%A8%E6%84%8F

组织文件夹的架构，nginx ui 就能自动识别。

**Comment by tengyinan1994** [comment]
感谢您的解答，我差不多理解了，在添加站点上建的所有server会在sites-available目录中，在nginx.conf通过include导入所有，所以我在nginx.config中不会看到我配置的所有server，但其实已经导入了，是这个意思吧？
之后我需要做导入的时候，我只需要在sites-available目录下按照其他文件的格式新建文件就可以同步到站点了是吧

**Comment by 0xJacky** [comment]
include 其实算是引用吧，这只是为了精简 nginx.conf 的内容，你应该在网站管理里查看不同的配置文件（网站）。
