### ISSUE TITLE
同步文件到远程节点失败

### ISSUE THREAD

**Issue by jearton** [0xJacky/nginx-ui#775]
Version: 2.0.0-beta.41

{"code":406,"errors":{"name":"required"},"message":"Requested with wrong parameters"}

![image](https://github.com/user-attachments/assets/84fc709e-ff89-4e32-a2a3-0f7cc60d90b0)

**Comment by 0xJacky** [comment]
能稳定复现吗，我这里测不出来

**Comment by jearton** [comment]
可以稳定复现，会不会和文件权限有关？你同步的是文件流还是文件里的内容？

![image](https://github.com/user-attachments/assets/decc4a2b-1f0c-4642-a078-a14fb4255948)

![image](https://github.com/user-attachments/assets/42db35b2-1773-4f20-ab53-eed3f9f53a62)

![image](https://github.com/user-attachments/assets/f374c07e-3631-4b59-8aad-daefcd85d163)

**Comment by jearton** [comment]
还需要我提供什么？

**Comment by jearton** [comment]
nginx  | 2024-12-11 15:53:56    ERROR   /home/runner/go/pkg/mod/github.com/uozi-tech/cosy@v1.9.14/validate.go:134        bind err Key: 'Name' Error:Field validation for 'Name' failed on the 'required' tag

这是被控节点的报错日志

**Comment by 0xJacky** [comment]
我这边只测出来过一次，刷新页面就正常了，我再继续看看怎么能触发的

**Comment by 0xJacky** [comment]
你好，方便看一下 sqlite 中的 configs 表，看看截图中同步的 path 对应的那一行中的 name 是否为空字符串？

**Comment by 0xJacky** [comment]
然后就是 F12 检查网络请求，看一下 `GET /api/configs/文件相对路径` 这个请求的的 response bodyd

**Comment by 0xJacky** [comment]
已修复
