### ISSUE TITLE
同步配置文件 到 节点失败，响应：{"message":"runtime error: invalid memory address or nil pointer dereference"}

### ISSUE THREAD

**Issue by zhangjianyf** [0xJacky/nginx-ui#778]
主控节点信息：
![image](https://github.com/user-attachments/assets/7c7c3763-6055-4f72-97d2-64070de98e1f)
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.6 LTS"

Node信息：
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.6 LTS"

![image](https://github.com/user-attachments/assets/7196a355-f3d1-4f61-833d-accff0ad1416)

节点的nginx-ui日志信息：
Dec 12 14:30:21 hz-idc-test-front-admin-02 nginx-ui[1936]: 2024-12-12 14:30:21        ERROR        router/middleware.go:16        runtime error: invalid memory address or nil pointer dereference
Dec 12 14:30:21 hz-idc-test-front-admin-02 nginx-ui[1936]: goroutine 122 [running]:
Dec 12 14:30:21 hz-idc-test-front-admin-02 nginx-ui[1936]: github.com/uozi-tech/cosy/router.Init.recovery.func2.1()
Dec 12 14:30:21 hz-idc-test-front-admin-02 nginx-ui[1936]:         /home/runner/go/pkg/mod/github.com/uozi-tech/cosy@v1.9.14/router/middleware.go:15 +0x65
Dec 12 14:30:21 hz-idc-test-front-admin-02 nginx-ui[1936]: panic({0x38deca0?, 0x79f73f0?})
Dec 12 14:30:21 hz-idc-test-front-admin-02 nginx-ui[1936]:         /opt/hostedtoolcache/go/1.23.3/x64/src/runtime/panic.go:785 +0x132
Dec 12 14:30:21 hz-idc-test-front-admin-02 nginx-ui[1936]: github.com/0xJacky/Nginx-UI/api/config.AddConfig(0xc001d21600)
Dec 12 14:30:21 hz-idc-test-front-admin-02 nginx-ui[1936]:         /home/runner/work/nginx-ui/nginx-ui/api/config/add.go:74 +0x259
Dec 12 14:30:21 hz-idc-test-front-admin-02 nginx-ui[1936]: github.com/gin-gonic/gin.(*Context).Next(0xc001d21600)
Dec 12 14:30:21 hz-idc-test-front-admin-02 nginx-ui[1936]:         /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185 +0x2b
Dec 12 14:30:21 hz-idc-test-front-admin-02 nginx-ui[1936]: github.com/0xJacky/Nginx-UI/router.InitRouter.Proxy.func6(0xc001d21600)
Dec 12 14:30:21 hz-idc-test-front-admin-02 nginx-ui[1936]:         /home/runner/work/nginx-ui/nginx-ui/internal/middleware/proxy.go:18 +0x165
Dec 12 14:30:21 hz-idc-test-front-admin-02 nginx-ui[1936]: github.com/gin-gonic/gin.(*Context).Next(0xc001d21600)
Dec 12 14:30:21 hz-idc-test-front-admin-02 nginx-ui[1936]:         /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185 +0x2b
Dec 12 14:30:21 hz-idc-test-front-admin-02 nginx-ui[1936]: github.com/0xJacky/Nginx-UI/router.InitRouter.AuthRequired.func5(0xc001d21600)
Dec 12 14:30:21 hz-idc-test-front-admin-02 nginx-ui[1936]:         /home/runner/work/nginx-ui/nginx-ui/internal/middleware/middleware.go:29 +0xcf
Dec 12 14:30:21 hz-idc-test-front-admin-02 nginx-ui[1936]: github.com/gin-gonic/gin.(*Context).Next(0xc001d21
相关截图：
![QQ20241212-143308](https://github.com/user-attachments/assets/f4a21cb4-dd5b-4ef3-bed9-dbd2fcf6a1d4)

**Comment by 0xJacky** [comment]
被控节点有配置 Node.SkipInstallation = true 吗

**Comment by zhangjianyf** [comment]
> 被控节点有配置 Node.SkipInstallation = true 吗
没有的，默认：false；我改成true试试看

**Comment by 0xJacky** [comment]
要改成 true，要不就手动在节点上执行安装

**Comment by zhangjianyf** [comment]
![image](https://github.com/user-attachments/assets/cc0fd1c3-efe9-4559-bd20-d4e6a5300e7e)

**Comment by 0xJacky** [comment]
可以先用网站编辑里的同步功能。这个问题我看看JackyOn Dec 12, 2024, at 3:15 PM, zhangjianyf ***@***.***> wrote:﻿

被控节点有配置 Node.SkipInstallation = true 吗
没有的，默认：false；我改成true试试看

**Comment by zhangjianyf** [comment]
> 可以先用网站编辑里的同步功能。这个问题我看看JackyOn Dec 12, 2024, at 3:15 PM, zhangjianyf ***@***.***> wrote:﻿ 被控节点有配置 Node.SkipInstallation = true 吗 没有的，默认：false；我改成true试试看 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

恩恩，好的，非常感谢

**Comment by jearton** [comment]
被控节点配置了 Node.SkipInstallation = true

**Comment by 0xJacky** [comment]
已在 [2f29598](https://github.com/0xJacky/nginx-ui/commit/2f295984f29653be4aecbc7602539c9d27274070) 中修复，将会随 v2.0.0-beta.42 发布，感谢您的反馈。
