### ISSUE TITLE
Debugging problem

### ISSUE THREAD

**Issue by BiancaIonascu** [0xJacky/nginx-ui#779]
I tried to debug the project in Goland and it doesn't work no matter what I do it doesn't hit the breakpoint.

**Info (please complete the following information):**
 - Server OS:  Ubuntu 22.04
 - Server Arch: x86_64
 - Nginx UI Version: 1.8.0
 - Your Browser: Firefox

**Comment by 0xJacky** [comment]
Hi @BiancaIonascu,

Can you provide us with more details, such as the file path and row number for which you set the breakpoint?
