### ISSUE TITLE
希望增加公安备案和ICP备案的网页底部标签

### ISSUE THREAD

**Issue by KanekiYuto** [0xJacky/nginx-ui#780]
最近收到了工信部和公安部的要求要加底部标签，但是如果需要改的话需要自己重新打包镜像

**Comment by 0xJacky** [comment]
你是直接挂在 www. 或者 @ 记录下用的？

**Comment by KanekiYuto** [comment]
> 你是直接挂在[www](http://www)。 或者@记录下用的？

不是的它的域名前缀是nginx.*，但是网安说只要是暴露在互联网上的都必须挂

**Comment by 0xJacky** [comment]
可以吧，后面还计划加这个功能 #739 确实要做个设置。

**Comment by 0xJacky** [comment]
已在 [e326f5e](https://github.com/0xJacky/nginx-ui/commit/e326f5e93063cd12b20f5b0fde8b537a5fd6ca17) 中添加，将会在 beta.42 中发布

**Comment by KanekiYuto** [comment]
> 已在[e326f5e](https://github.com/0xJacky/nginx-ui/commit/e326f5e93063cd12b20f5b0fde8b537a5fd6ca17)中添加，将于beta.42中发布

非常感谢
