### ISSUE TITLE
面板反代后，在面板中不能进行证书的签发、面板的升级等操作

### ISSUE THREAD

**Issue by hkfires** [0xJacky/nginx-ui#781]
使用nginx反代nginxui面板后，在面板中不能进行证书的签发、面板的升级等操作，界面会直接卡住

**Comment by 0xJacky** [comment]
你好，这个是经典问题，请确保你的反代支持 WebSocket，谢谢。具体配置请参考：https://nginxui.com/zh_CN/guide/nginx-proxy-example.html
