### ISSUE TITLE
No connection on terminal and error on reinstall

### ISSUE THREAD

**Issue by gadonski** [0xJacky/nginx-ui#785]
**Describe the bug**
After update from beta 37 to beta 42, the terminal shows a message "Connection lost, please refesh the page"

I've tried to reinstall, but the core upgrade freeze on upgrade modal.

**To Reproduce**
Steps to reproduce the behavior bug os terminal:
1. Go to terminal
2. See the error message

Steps to reproduce the behavior bug os terminal:
1. Go to system > upgrade
2. Click on Reinstall button
3. Modal freezes with no error

**Expected behavior**
I tried using the terminal, but since it was giving an error, I thought that updating using the interface would solve the problem.

**Screenshots**
![image](https://github.com/user-attachments/assets/b3991b05-1c37-40a0-8656-f284928711c2)

![image](https://github.com/user-attachments/assets/0ce0b102-c58c-4f09-8fc8-fe04f4cb15ce)

**Info (please complete the following information):**
 - Server OS: Ubuntu 22.04
 - Server Arch: amd64
 - Nginx UI Version: v2.0.0-beta.42
 - Your Browser: Chrome

**Additional context**

**Comment by 0xJacky** [comment]
Please ensure you have configured the nginx support handling WebSocket request: https://nginxui.com/guide/nginx-proxy-example.html.
