### ISSUE TITLE
自动更新有点慢，能否增加一些国内的线路

### ISSUE THREAD

**Issue by 858622025** [0xJacky/nginx-ui#787]
RT

**Comment by 858622025** [comment]
或者UI上增加一个上传更新包的按钮，这样操作方便些

**Comment by 0xJacky** [comment]
你好，Nginx UI 支持配置 GitHub 镜像：https://nginxui.com/zh_CN/guide/config-http.html#githubproxy

你可以在偏好设置>基本中配置 GitHub 镜像，也可以修改配置文件。

由于系统安全性策略的限制，我们**不考虑**增加上传二进制文件进行更新。

关于线路，目前您可以使用市面上的镜像源或者自建。我们也欢迎大家捐助我们：https://github.com/sponsors/nginxui 捐款将用于服务器的维护和线路质量的提升。
