### ISSUE TITLE
database is locked

### ISSUE THREAD

**Issue by MickMo** [0xJacky/nginx-ui#79]
The webui show ‘Server error’, and it won't start

Here is the logs
`2023/02/11 19:55:17 /home/runner/work/nginx-ui/nginx-ui/server/model/model.go:43 database is locked
[5005.834ms] [rows:0] CREATE TABLE `config_backups` (`id` integer,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`name` text,`file_path` text,`content` text,PRIMARY KEY (`id`))
2023/02/11 19:55:17 database is locked
2023/02/11 19:55:18 [notice] 9#9: using the "epoll" event method
2023/02/11 19:55:18 [notice] 9#9: nginx/1.23.1
2023/02/11 19:55:18 [notice] 9#9: built by gcc 10.2.1 20210110 (Debian 10.2.1-6) 
2023/02/11 19:55:18 [notice] 9#9: OS: Linux 5.10.0-13-amd64
2023/02/11 19:55:18 [notice] 9#9: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2023/02/11 19:55:18 [notice] 17#17: start worker processes
2023/02/11 19:55:18 [notice] 17#17: start worker process 18
2023/02/11 19:55:18 [notice] 17#17: start worker process 19
2023/02/11 19:55:18 [notice] 17#17: start worker process 20
2023/02/11 19:55:18 [notice] 17#17: start worker process 21
2023/02/11 19:55:18 Nginx config dir path: /etc/nginx

2023/02/11 19:55:18 /home/runner/go/pkg/mod/gorm.io/driver/sqlite@v1.1.4/migrator.go:32
[1.026ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="config_backups"

2023/02/11 19:55:23 /home/runner/work/nginx-ui/nginx-ui/server/model/model.go:43 database is locked
[5005.234ms] [rows:0] CREATE TABLE `config_backups` (`id` integer,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`name` text,`file_path` text,`content` text,PRIMARY KEY (`id`))
2023/02/11 19:55:23 database is locked
2023/02/11 19:55:24 [notice] 8#8: using the "epoll" event method
2023/02/11 19:55:24 [notice] 8#8: nginx/1.23.1
2023/02/11 19:55:24 [notice] 8#8: built by gcc 10.2.1 20210110 (Debian 10.2.1-6) 
2023/02/11 19:55:24 [notice] 8#8: OS: Linux 5.10.0-13-amd64
2023/02/11 19:55:24 [notice] 8#8: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2023/02/11 19:55:24 [notice] 16#16: start worker processes
2023/02/11 19:55:24 [notice] 16#16: start worker process 17
2023/02/11 19:55:24 [notice] 16#16: start worker process 18
2023/02/11 19:55:24 [notice] 16#16: start worker process 19
2023/02/11 19:55:24 [notice] 16#16: start worker process 20
2023/02/11 19:55:24 Nginx config dir path: /etc/nginx

2023/02/11 19:55:24 /home/runner/go/pkg/mod/gorm.io/driver/sqlite@v1.1.4/migrator.go:32`

**Comment by 0xJacky** [comment]
Have you try to delete the database.db and restart the nginx-ui?

**Comment by MickMo** [comment]
woops,It did not support cifs mount, it work just fine when using host directory
