### ISSUE TITLE
错误的跳转

### ISSUE THREAD

**Issue by KanekiYuto** [0xJacky/nginx-ui#794]
1. 当我有三个网站部署在nginx上是禁用其它两个后访问这两个域名会重定向到启用的那个站点
2. 我希望它是不会跳转的没有启用就是直接禁止
3. 希望增加404/403/502等基础模板

**Comment by 0xJacky** [comment]
1., 2., 这个是 Nginx 的特性，你可以适当的配置
3. 这个以后会考虑

**Comment by KanekiYuto** [comment]
> 1., 2., 这个是 Nginx 的特性，你可以适当的配置 3. 这个以后会考虑

是否可以增加一个开放平台可以通过restful去推送配置或是远程重启/重载nginx

**Comment by 0xJacky** [comment]
现在 api 就是 RestFul 的，您可以F12 检查网络请求。因为目前还是 beta 阶段，接口还会有修改，所以暂时不会考虑。

**Comment by KanekiYuto** [comment]
> 现在 api 就是 RestFul 的，您可以F12 检查网络请求。因为目前还是 beta 阶段，接口还会有修改，所以暂时不会考虑。

好的，感谢你的回复，我会持续关注的，谢谢
