### ISSUE TITLE
家里的局域网是申请不了通配符证书的吗？

### ISSUE THREAD

**Issue by a506488043** [0xJacky/nginx-ui#797]
用的阿里云 DNS ；
刚部署的时候，还能申请到通配符证书；现在是不行了吗？
还有通配符证书续期都是失败；
![image](https://github.com/user-attachments/assets/759df3ba-d8af-4ac0-b8a4-7e8663d0bb24)

**Comment by 0xJacky** [comment]
设置一下这个证书的 ACME 用户，保存，再手动续期一次看看

**Comment by a506488043** [comment]
> 设置一下这个证书的 ACME 用户，保存，再手动续期一次看看

 不行。key 没有用 RAM 用户；

**Comment by 0xJacky** [comment]
不用 RAM 用户，那些选项不是都必填的，填 AccessKey 和 AccessKey Secret 就可

**Comment by a506488043** [comment]
> 不用 RAM 用户，那些选项不是都必填的，填 AccessKey 和 AccessKey Secret 就可
是填了AccessKey ID，AccessKey Secret；其他没有填；
![image](https://github.com/user-attachments/assets/66c8113b-a564-4ea9-9068-fe7d8251b598)

**Comment by 0xJacky** [comment]
<img width="705" alt="image" src="https://github.com/user-attachments/assets/a99978bc-6803-4c39-8840-f1a515d788fe" />
这里，设置一下

**Comment by a506488043** [comment]
> <img alt="image" width="705" src="https://private-user-images.githubusercontent.com/13096985/399162383-a99978bc-6803-4c39-8840-f1a515d788fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU0NzgzNDksIm5iZiI6MTczNTQ3ODA0OSwicGF0aCI6Ii8xMzA5Njk4NS8zOTkxNjIzODMtYTk5OTc4YmMtNjgwMy00YzM5LTg4NDAtZjFhNTE1ZDc4OGZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI5VDEzMTQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkODU4ZjRlNWM5YmZhYjM5YTgwZGI4MjBhNDI1YmIwYWIwYmZlYTA2ZTVkZWFiZWJkMTk5ZjFhZDIzZGMxZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.D8o8LR7peMr3onf4uw02M9buUglqjkOO0c5_61T4gfA"> 这里，设置一下

啥情况？为什么我这没有啊；

**Comment by 0xJacky** [comment]
看不到你的图

**Comment by a506488043** [comment]
> 看不到你的图

我清缓存后，有DNS 凭证了； 没清缓存之前是只有DNS提供商，没有DNS凭证；

**Comment by 0xJacky** [comment]
那不清楚了，看不到图，现在问题解决了么

**Comment by a506488043** [comment]
> 那不清楚了，看不到图，现在问题解决了么

问题解决了，证书是申请了，但是谷歌浏览器不认证书；

**Comment by 0xJacky** [comment]
可以截个图看看错误信息吗

**Comment by 0xJacky** [comment]
你用的是 staging 的 CA ？
