### ISSUE TITLE
[Question] Terminal Login without Password

### ISSUE THREAD

**Issue by aldinokemal** [0xJacky/nginx-ui#81]
How can we configure our Web Terminal login method with an SSH key?

**Comment by 0xJacky** [comment]
Currently, using SSH key to login is not supported. If you want to use Terminal without password, you can change the ‘StartCmd’ which is in config.ini, to ‘bash’ and then restart nginx-ui.

**Comment by aldinokemal** [comment]
nice, actually we just need to set root password and do login with user root
it's working now

for example:
- `sudo su`
- `passwd` -> enter you root password (ex: 1234)

then login via web terminal
- user: `root`
- password: `1234`
