### ISSUE TITLE
Network Statistics display problem

### ISSUE THREAD

**Issue by LSOIVNE** [0xJacky/nginx-ui#86]
## Problem
Network Total Receive value display as scientific notation after reach 1TB.

<img width="291" alt="Screenshot_20230301_035651" src="https://user-images.githubusercontent.com/30148130/222078409-a62b6169-9993-407d-b6fc-2e0e68a01e1d.png">

## System Info
OS: ubuntu 20.04 (linux 5.4.0-139-generic x86_64)

Current Version: v1.7.6

Arch: amd64

Executable Path: /usr/local/bin/nginx-ui

## ipconfig
`root@localhost:~# ifconfig`
`eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500`
`        inet 205.xxx.xxx.xxx  netmask 255.255.255.0  broadcast 205.xxx.xxx.255`
`        inet6 fe80::216:48ff:fe53:c34f  prefixlen 64  scopeid 0x20<link>`
`        inet6 2605:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx  prefixlen 48  scopeid 0x0<global>`
`        ether 00:16:48:53:c3:4f  txqueuelen 1000  (Ethernet)`
`        RX packets 698314908  bytes 1095708028756 (1.0 TB)`
`        RX errors 0  dropped 256196  overruns 0  frame 0`
`        TX packets 267555078  bytes 648603774866 (648.6 GB)`
`        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0`

**Comment by 0xJacky** [comment]
Thanks for your report.

It seems like a unit conversion issue. But it will become normal when the value increases.

![image](https://user-images.githubusercontent.com/13096985/222081624-c2b7347e-4f03-4920-aafd-40268ad81a03.png)

I will try to optimize the conversion in next version.

**Comment by LSOIVNE** [comment]
Ok, thank you.
