### ISSUE TITLE
运行错误 runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by yesicoo** [0xJacky/nginx-ui#9]
您好，我在mac上编译成win exe 控制台运行报以下错误

2021/11/05 17:02:52 /******/go/pkg/mod/gorm.io/driver/sqlite@v1.1.4/migrator.go:32
[0.000ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="config_backups"
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x3cfbce]

**Comment by 0xJacky** [comment]
您好，我手头上没有暂时没有Win的设备，可能暂时测不了，在mac上能正常运行吗

Jacky

**Comment by yesicoo** [comment]
mac 上可以的 非常好

**Comment by 0xJacky** [comment]
好的 我下周看看，有可能是 sql driver 的锅

Jacky

**Comment by 0xJacky** [comment]
应该是 gorm sqlite driver 的锅，注释掉 server/model/models.go 的迁移代码是可以跑的。

**Comment by 0xJacky** [comment]
您好，这个问题应该是没有启用CGO编译导致的。
请先用 `brew install mingw-w64` 安装依赖
再使用 
```
CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ GOOS=windows GOARCH=amd64 go build main.go
```
编译 Windows 版本
