### ISSUE TITLE
Does support grpc ?

### ISSUE THREAD

**Issue by UMUTBAYGUT** [0xJacky/nginx-ui#90]
Hello , 
does support grpc proxy ? 
Can you show example if support ?

**Comment by 0xJacky** [comment]
Do you mean the configuration template of grpc proxy?

**Comment by UMUTBAYGUT** [comment]
Yes , can you show configuration template of grpc proxy ?

**Comment by 0xJacky** [comment]
Here is an example of an nginx configuration template for a gRPC proxy:

perl
Copy code
http {
  upstream grpc_backend {
    server backend1:9000;
    server backend2:9000;
    server backend3:9000;
  }

  server {
    listen 80;
    server_name grpc.example.com;

    location / {
      grpc_pass grpc://grpc_backend;
      error_log /var/log/nginx/grpc.error.log;
      access_log /var/log/nginx/grpc.access.log;
      grpc_set_header Host $http_host;
      grpc_set_header X-Real-IP $remote_addr;
      grpc_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      grpc_set_header X-Forwarded-Proto $scheme;
    }
  }
}
In this configuration, the upstream block defines the gRPC backend servers, and the server block defines the proxy server. The location block specifies that gRPC traffic should be passed to the backend servers via the grpc_pass directive, and sets various headers for the gRPC requests.

Note that this is just an example configuration, and you may need to modify it to suit your specific use case.
