### ISSUE TITLE
部署掉linux后: nginx-ui服务自己就挂掉了 

### ISSUE THREAD

**Issue by yuhongqiang** [0xJacky/nginx-ui#92]
可能是linux原因:  但是我部署了3台不同的linux服务器 都出现了这个情况
您那边发生过吗?

**Comment by 0xJacky** [comment]
可以看一下日志吗
systemctl status nginx-hi

**Comment by 0xJacky** [comment]
我这边的话跑了4台服务器，都没挂过了，麻烦提供一下详细日志

```
journalctl -u nginx-ui
```

**Comment by yuhongqiang** [comment]
[GIN] 2023/03/13 - 19:44:24 | 200 |      44.376µs |   10.20.198.128 | GET      "/"
[GIN] 2023/03/13 - 19:44:39 | 200 |      49.975µs |   10.20.198.128 | GET      "/"
[GIN] 2023/03/13 - 19:44:54 | 200 |      77.827µs |   10.20.198.128 | GET      "/"
[GIN] 2023/03/13 - 19:45:09 | 200 |      40.901µs |   10.20.198.128 | GET      "/"
[GIN] 2023/03/13 - 19:45:24 | 200 |      51.847µs |   10.20.198.128 | GET      "/"
[GIN] 2023/03/13 - 19:45:39 | 200 |      42.513µs |   10.20.198.128 | GET      "/"
[GIN] 2023/03/13 - 19:45:54 | 200 |      89.038µs |   10.20.198.128 | GET      "/"
[GIN] 2023/03/13 - 19:46:09 | 200 |      60.461µs |   10.20.198.128 | GET      "/"

19:47挂的:   我得linux是6  没有journalctl命令 
上面的是我nohup ./nginx-ui -config app.ini  > /applog/nginx-ui/nginx-ui.log 2>&1 & 
打印出的最后几行日志  (日志没问题)

那应该就是我服务器的问题 我在排查下吧

**Comment by 0xJacky** [comment]
可以再观察一下，有错误日志发上来就行，我会尽快解决

**Comment by yuhongqiang** [comment]
好的

**Comment by yuhongqiang** [comment]
2023/03/14 15:51:09 [Error] analytic WriteJSON write tcp 10.0.8.9:9000->154.31.112.39:42648: write: broken pipe

这个会有影响吗?  
还是 linux得设置下哪里 才可以 我部署到我自己的腾讯云服务器上一天 也自己就突然挂掉了

**Comment by yuhongqiang** [comment]
2023/03/14 13:37:21 [AutoCert] Recover runtime error: invalid memory address or nil pointer dereference

往前翻  还发现了这样一个error

**Comment by 0xJacky** [comment]
> 2023/03/14 15:51:09 [Error] analytic WriteJSON write tcp 10.0.8.9:9000->154.31.112.39:42648: write: broken pipe
> 
> 这个会有影响吗? 还是 linux得设置下哪里 才可以 我部署到我自己的腾讯云服务器上一天 也自己就突然挂掉了

这个没有影响

**Comment by 0xJacky** [comment]
> 

这个话目前应该是没啥问题，写了recovery，一般来说不会卡死主进程，而且你后面都有请求了，请问您方便提供一下运行环境吗，比如系统，架构。

如果可以的话也可以提供脱敏后的database.db, app.ini 启动参数等到我的邮箱 me@jackyu.cn

**Comment by yuhongqiang** [comment]
已发送

**Comment by 0xJacky** [comment]
好的 我过两天研究一下，这两天有点忙JackyOn Mar 17, 2023, at 11:15 AM, yuhongqiang ***@***.***> wrote:﻿
已发送

**Comment by yuhongqiang** [comment]
嗯嗯  不急不急

**Comment by 0xJacky** [comment]
有试过 release 版本的吗，看看能不能正常使用

**Comment by yuhongqiang** [comment]
用过:  也是服务突然就挂了

**Comment by 0xJacky** [comment]
嗯好的

**Comment by yuhongqiang** [comment]
我猜是不是您那里的linux服务器做了什么操作配置  服务才不会挂   我这都试了   就突然就挂

**Comment by 0xJacky** [comment]
https://github.com/0xJacky/nginx-ui/blob/ba87f02a53f3ec62ae95cb9bdc383f218215055c/install.sh#L269-L272

我这边用的 systemd，做了 restart on failure，那可能确实程序的bug，我这边观察一下，感谢您的反馈

**Comment by 0xJacky** [comment]
对了，我再确认一下，是目前最新的版本v1.7.7也会出现这个问题是吧

**Comment by yuhongqiang** [comment]
我现在用的是v1.7.6   之前用 v1.7.5  都有这个问题    1.7.7 没有用过

**Comment by 0xJacky** [comment]
麻烦升级一下看看

**Comment by yuhongqiang** [comment]
嗯   升级之后 还有问题我再反馈

**Comment by 0xJacky** [comment]
好嘞，我这边也测测看

**Comment by 0xJacky** [comment]
我这边在 Ubuntu 22.04 上跑了几天了，一直没重启。您那边是什么发行版的 Linux 呢

**Comment by yuhongqiang** [comment]
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Comment by yuhongqiang** [comment]
Linux version 3.10.0-1160.31.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Thu Jun 10 13:32:12 UTC 2021

**Comment by yuhongqiang** [comment]
我这边用我的mac m1 放了几天   也没有挂  就上linux挂了

**Comment by 0xJacky** [comment]
看看系统日志，是不是 OOM 了然后被 kill 了JackyOn Mar 20, 2023, at 2:47 PM, yuhongqiang ***@***.***> wrote:﻿
我这边用我的mac m1 放了几天   也没有挂  就上linux挂了

**Comment by yuhongqiang** [comment]
我这边还是突然中断,不是oom问题, 我这边目的是可视化 不需要编辑  所以就上了守护进程  也不影响使用

**Comment by 0xJacky** [comment]
嗯，好的
