### ISSUE TITLE
docker 二次部署以后，web界面无法展示

### ISSUE THREAD

**Issue by AutschHa** [0xJacky/nginx-ui#95]
docker部署以后，重启或者停止容器删除容器重新部署就无法访问当前项目，但log是正常的，也在运行。
永远是第一次可用。尝试删除所有映射文件以及镜像重新拉取安装也是一样，经过排查找到容器内部nginx-ui文件夹下app.ini文件不存在。
下面是部署内容
docker run -dit \
  --name=nginx-ui \
  --restart=always \
  -e TZ=Asia/Shanghai \
  -v /mnt/user/appdata/nginx:/etc/nginx \
  -v /mnt/user/appdata/nginx-ui:/etc/nginx-ui \
  -p 8080:8080 -p 8443:8443 \
  uozi/nginx-ui:latest

**Comment by 0xJacky** [comment]
收到，我这边尝试一下看看能否复现

**Comment by 0xJacky** [comment]
暂时无法复现您的问题，我尝试使用
```
docker run -dit \                              ░▒▓ ✔ │ root@1003 ▓▒░
  --name=nginx-ui \
  --restart=always \
  -e TZ=Asia/Shanghai \
  -v /root/playground/nginx:/etc/nginx \
  -v /root/playground/nginx-ui:/etc/nginx-ui \
  -v /var/www:/var/www \
  -p 8080:80 -p 9443:443 \
  uozi/nginx-ui:latest
```

进行部署。首次部署完成后，我执行了 restart，删除镜像重新创建容器 后依然可以正常访问，

**Comment by AutschHa** [comment]
删除宿主机 /mnt/user/ 文件夹
删除宿主机 /var/www
删除宿主机/etc/nginx
停止容器，删除容器，删除镜像
映射的配置全删了，还是不行还是容器内nginx-ui缺 ini
`docker run -dit \
  --name=nginx-ui \
  --restart=always \
  -e TZ=Asia/Shanghai \
  -v /mnt/user/appdata/nginx:/etc/nginx \
  -v /mnt/user/appdata/nginx-ui:/etc/nginx-ui \
  -v /var/www:/var/www \
  -p 8080:8080 -p 8443:8443 \
  uozi/nginx-ui:latest`

部分log
`[GIN-debug] DELETE /api/auto_cert/:name      --> github.com/0xJacky/Nginx-UI/server/api.RemoveDomainFromAutoCert (6 handlers)
[GIN-debug] GET    /api/pty                  --> github.com/0xJacky/Nginx-UI/server/api.Pty (6 handlers)
[GIN-debug] GET    /api/nginx_log            --> github.com/0xJacky/Nginx-UI/server/api.NginxLog (6 handlers)
[GIN-debug] POST   /api/nginx_log            --> github.com/0xJacky/Nginx-UI/server/api.GetNginxLogPage (6 handlers)
[GIN-debug] GET    /api/settings             --> github.com/0xJacky/Nginx-UI/server/api.GetSettings (6 handlers)
[GIN-debug] POST   /api/settings             --> github.com/0xJacky/Nginx-UI/server/api.SaveSettings (6 handlers)
[GIN-debug] GET    /api/upgrade/release      --> github.com/0xJacky/Nginx-UI/server/api.GetRelease (6 handlers)
[GIN-debug] GET    /api/upgrade/current      --> github.com/0xJacky/Nginx-UI/server/api.GetCurrentVersion (6 handlers)
[GIN-debug] GET    /api/upgrade/perform      --> github.com/0xJacky/Nginx-UI/server/api.PerformCoreUpgrade (6 handlers)
[GIN-debug] POST   /api/chat_gpt             --> github.com/0xJacky/Nginx-UI/server/api.MakeChatCompletionRequest (6 handlers)
2023/03/30 15:44:34 [Nginx UI] RecordServerAnalytic Started
[GIN-debug] POST   /api/chat_gpt_record      --> github.com/0xJacky/Nginx-UI/server/api.StoreChatGPTRecord (6 handlers)`
显示也正常

简短的找文件
`[root@k8s-master ~]# docker exec -it 46368e163eda /bin/bash
root@46368e163eda:/app# ls
nginx-ui  start.sh
root@46368e163eda:/app# cd ..
root@46368e163eda:/# ls
app  boot  docker-entrypoint.d   etc   lib    media  opt   root  sbin  sys  usr
bin  dev   docker-entrypoint.sh  home  lib64  mnt    proc  run   srv   tmp  var
root@46368e163eda:/# cd /etc/
root@46368e163eda:/etc# ls
adduser.conf            debian_version  group-     issue.net      motd           passwd     rc6.d        ssl
alternatives            default         gshadow    kernel         mtab           passwd-    rcS.d        subgid
apt                     deluser.conf    gshadow-   ld.so.cache    netconfig      profile    resolv.conf  subuid
bash.bashrc             dpkg            gss        ld.so.conf     nginx          profile.d  rmt          systemd
bindresvport.blacklist  e2scrub.conf    host.conf  ld.so.conf.d   nginx-ui       rc0.d      security     terminfo
ca-certificates         environment     hostname   libaudit.conf  nsswitch.conf  rc1.d      selinux      timezone
ca-certificates.conf    fonts           hosts      localtime      opt            rc2.d      shadow       ucf.conf
cron.d                  fstab           init.d     login.defs     os-release     rc3.d      shadow-      update-motd.d
cron.daily              gai.conf        inputrc    logrotate.d    pam.conf       rc4.d      shells       xattr.conf
debconf.conf            group           issue      mke2fs.conf    pam.d          rc5.d      skel
root@46368e163eda:/etc# cd nginx-ui/
root@46368e163eda:/etc/nginx-ui# ls
root@46368e163eda:/etc/nginx-ui# ls 
root@46368e163eda:/etc/nginx-ui# cd ..
root@46368e163eda:/etc# cd nginx
root@46368e163eda:/etc/nginx# ls
conf.d  fastcgi_params  mime.types  modules  nginx.conf  scgi_params  sites-available  sites-enabled  uwsgi_params
root@46368e163eda:/etc/nginx# 
`

**Comment by 0xJacky** [comment]
是不是因为宿主机不存在  /mnt 这个目录，你试试目录映射呢？比如 /usr/local/etc/nginx-ui

**Comment by AutschHa** [comment]
换路径也是一样，缺少app.ini，nginx-ui文件夹下没内容，如果方便远程看看？

**Comment by AutschHa** [comment]
`[GIN-debug] POST   /api/cert                 --> github.com/0xJacky/Nginx-UI/server/api.AddCert (6 handlers)
[GIN-debug] POST   /api/cert/:id             --> github.com/0xJacky/Nginx-UI/server/api.ModifyCert (6 handlers)
[GIN-debug] DELETE /api/cert/:id             --> github.com/0xJacky/Nginx-UI/server/api.RemoveCert (6 handlers)
[GIN-debug] POST   /api/auto_cert/:name      --> github.com/0xJacky/Nginx-UI/server/api.AddDomainToAutoCert (6 handlers)
[GIN-debug] DELETE /api/auto_cert/:name      --> github.com/0xJacky/Nginx-UI/server/api.RemoveDomainFromAutoCert (6 handlers)
2023/03/31 15:44:40 [AutoCert] Recover runtime error: invalid memory address or nil pointer dereference
[GIN-debug] GET    /api/pty                  --> github.com/0xJacky/Nginx-UI/server/api.Pty (6 handlers)
[GIN-debug] GET    /api/nginx_log            --> github.com/0xJacky/Nginx-UI/server/api.NginxLog (6 handlers)
[GIN-debug] POST   /api/nginx_log            --> github.com/0xJacky/Nginx-UI/server/api.GetNginxLogPage (6 handlers)
[GIN-debug] GET    /api/settings             --> github.com/0xJacky/Nginx-UI/server/api.GetSettings (6 handlers)
[GIN-debug] POST   /api/settings             --> github.com/0xJacky/Nginx-UI/server/api.SaveSettings (6 handlers)
[GIN-debug] GET    /api/upgrade/release      --> github.com/0xJacky/Nginx-UI/server/api.GetRelease (6 handlers)
[GIN-debug] GET    /api/upgrade/current      --> github.com/0xJacky/Nginx-UI/server/api.GetCurrentVersion (6 handlers)
[GIN-debug] GET    /api/upgrade/perform      --> github.com/0xJacky/Nginx-UI/server/api.PerformCoreUpgrade (6 handlers)
2023/03/31 15:44:40 [Nginx UI] RecordServerAnalytic Started
[GIN-debug] POST   /api/chat_gpt             --> github.com/0xJacky/Nginx-UI/server/api.MakeChatCompletionRequest (6 handlers)
[GIN-debug] POST   /api/chat_gpt_record      --> github.com/0xJacky/Nginx-UI/server/api.StoreChatGPTRecord (6 handlers)
2023/03/31 16:14:40 [AutoCert] Start
2023/03/31 16:14:40 [AutoCert] Recover runtime error: invalid memory address or nil pointer dereference
2023/03/31 16:44:40 [AutoCert] Start
2023/03/31 16:44:40 [AutoCert] Recover runtime error: invalid memory address or nil pointer dereference
2023/03/31 17:14:40 [AutoCert] Start
2023/03/31 17:14:40 [AutoCert] Recover runtime error: invalid memory address or nil pointer dereference
2023/03/31 17:44:40 [AutoCert] Start
2023/03/31 17:44:40 [AutoCert] Recover runtime error: invalid memory address or nil pointer dereference
`

**Comment by 0xJacky** [comment]
nginx-ui 文件夹是放配置文件和数据库的，首次使用的时候访问 `https://{ip}:{port}/install` 安装之后才会有配置文件

**Comment by AutschHa** [comment]
目前解决一半，可以访问了，但是报错
`2023/04/03 10:54:06 http: panic serving 127.0.0.1:40016: runtime error: invalid memory address or nil pointer dereference
goroutine 33 [running]:
net/http.(*conn).serve.func1()
        /opt/hostedtoolcache/go/1.20.2/x64/src/net/http/server.go:1854 +0xbf
panic({0xdca0a0, 0x1bc0530})
        /opt/hostedtoolcache/go/1.20.2/x64/src/runtime/panic.go:890 +0x263
gorm.io/gorm.(*DB).getInstance(0xc000100800?)
        /home/runner/go/pkg/mod/gorm.io/gorm@v1.24.6/gorm.go:374 +0x18
gorm.io/gorm.(*DB).Model(...)
        /home/runner/go/pkg/mod/gorm.io/gorm@v1.24.6/chainable_api.go:19
github.com/0xJacky/Nginx-UI/server/model.GetUserList(0x1?, {0xd8a8e0?, 0xc0005136c8?})
        /home/runner/work/nginx-ui/nginx-ui/server/model/auth.go:36 +0x9a
github.com/0xJacky/Nginx-UI/server/api.GetUsers(0xc000615800?)
        /home/runner/work/nginx-ui/nginx-ui/server/api/user.go:13 +0x5c
github.com/gin-gonic/gin.(*Context).Next(...)
        /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1(0xc000615800)
        /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/logger.go:240 +0xe7
github.com/gin-gonic/gin.(*Context).Next(...)
        /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc00008e000, 0xc000615800)
        /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:620 +0x66b
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc00008e000, {0x148eb50?, 0xc0004f2ee0}, 0xc000615700)
        /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:576 +0x1dd
net/http.serverHandler.ServeHTTP({0xc000525dd0?}, {0x148eb50, 0xc0004f2ee0}, 0xc000615700)
        /opt/hostedtoolcache/go/1.20.2/x64/src/net/http/server.go:2936 +0x316
net/http.(*conn).serve(0xc0003a54d0, {0x148f898, 0xc0003af950})
        /opt/hostedtoolcache/go/1.20.2/x64/src/net/http/server.go:1995 +0x612
created by net/http.(*Server).Serve
        /opt/hostedtoolcache/go/1.20.2/x64/src/net/http/server.go:3089 +0x5ed
2023/04/03 10:54:06 [error] 16#16: *5 upstream prematurely closed connection while reading response header from upstream, client: 192.168.1.148, server: localhost, request: "GET /api/users HTTP/1.1", upstream: "http://127.0.0.1:9000/api/users", host: "192.168.1.150:8080", referrer: "http://192.168.1.150:8080/"
192.168.1.148 - - [03/Apr/2023:10:54:06 +0800] "GET /api/users HTTP/1.1" 502 559 "http://192.168.1.150:8080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36" "-"
2023/04/03 10:54:07 runtime error: invalid memory address or nil pointer dereference
[GIN-debug] [WARNING] Headers were already written. Wanted to override status code 500 with 200
[GIN] 2023/04/03 - 10:54:07 | 500 |    2.049812ms |   192.168.1.148 | GET      "/api/analytic/init"
192.168.1.148 - - [03/Apr/2023:10:54:07 +0800] "GET /api/analytic/init HTTP/1.1" 500 37475 "http://192.168.1.150:8080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36" "-"
`

**Comment by AutschHa** [comment]
已解决，感谢博主

**Comment by 0xJacky** [comment]
蚌，那我关掉这个issue了
