### ISSUE TITLE
Dark Mode Reinstall Text White

### ISSUE THREAD

**Issue by cpjet64** [0xJacky/nginx-ui#99]
**Describe the bug**
The text in the popup window when reinstalling is white

**To Reproduce**
1. Be in Dark Mode
2. Click on Reinstall
3. See White Text

**Expected behavior**
Text should be Black

**Screenshots**
![image](https://user-images.githubusercontent.com/38527447/232155328-fd1cc9c2-0e87-4990-8fc6-e3dfbdffc41f.png)
![image](https://user-images.githubusercontent.com/38527447/232155387-77ed2bf1-77a8-4e11-b062-6371e5b57de6.png)
![image](https://user-images.githubusercontent.com/38527447/232155107-3dfcb9c0-83a6-4d83-a876-4e4616c86cc4.png)

**Info (please complete the following information):**
 - Server OS:Ubuntu 22.04
 - Server Arch: amd64
 - Nginx UI Version: v1.7.9
 - Your Browser: Brave [Version 1.50.114 Chromium: 112.0.5615.49 (Official Build) (64-bit)](https://brave.com/latest/)

**Additional context**

**Comment by 0xJacky** [comment]
Thanks for your report, fixed in #4ea3366
